-- Code generated by tsq-v4.10.0. DO NOT EDIT.

-- Dialect: sqlite

-- Table: todos

CREATE TABLE IF NOT EXISTS "todos" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "done" BOOLEAN NOT NULL,
    "title" VARCHAR(200) NOT NULL
);
