// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"fmt"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/tmoeish/tsq/v5"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableCourse implements the tsq.Table interface for Course.
//
// The Course__Cols argument is never read. It makes this variable depend on the
// column slice so that Go initializes the slice first: Cols reaches it through an
// interface method, which package initialization ordering cannot see. Without it a
// package-level query variable in a file sorting before this one can observe
// Course__Cols fully sized with nil elements.
var TableCourse tsq.Table = tsq.DeclareTable(Course{}, Course__Cols)

// TSQOwner marks Course as a TSQ owner.
func (c Course) TSQOwner() {}

// TableName returns the database table name for Course.
func (c Course) TableName() string { return "course" }

// Cols returns all generated columns for Course.
func (c Course) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(Course__Cols...)
}

// SearchColumns returns columns that support keyword search for Course.
func (c Course) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{
		Course_Title,
		Course_Summary,
	}
}

// PrimaryKey returns the primary key column for Course.
func (c Course) PrimaryKey() string {
	return "id"
}

// AutoIncrement reports whether Course uses an auto-increment primary key.
func (c Course) AutoIncrement() bool { return true }

// ManagedColumns returns the columns TSQ maintains for Course.
func (c Course) ManagedColumns() tsq.ManagedColumns {
	return tsq.ManagedColumns{
		CreatedAt: "created_at",
	}
}

// Column definitions for Course table.
var (
	Course_CreatedAt      = tsq.NewColumn("created_at", "created_at", func(t *Course) *null.Time { return &t.CreatedAt })
	Course_ID             = tsq.NewColumn("id", "id", func(t *Course) *int64 { return &t.ID })
	Course_InstructorID   = tsq.NewColumn("instructor_id", "instructor_id", func(t *Course) *int64 { return &t.InstructorID })
	Course_Level          = tsq.NewColumn("level", "level", func(t *Course) *CourseLevel { return &t.Level })
	Course_ListPriceCents = tsq.NewColumn("list_price_cents", "list_price_cents", func(t *Course) *int64 { return &t.ListPriceCents })
	Course_PrerequisiteID = tsq.NewColumn("prerequisite_id", "prerequisite_id", func(t *Course) *int64 { return &t.PrerequisiteID })
	Course_Published      = tsq.NewColumn("published", "published", func(t *Course) *bool { return &t.Published })
	Course_Summary        = tsq.NewColumn("summary", "summary", func(t *Course) *string { return &t.Summary })
	Course_Title          = tsq.NewColumn("title", "title", func(t *Course) *string { return &t.Title })
	Course_TrackID        = tsq.NewColumn("track_id", "track_id", func(t *Course) *int64 { return &t.TrackID })
)

// Course__Cols is the list of all selectable columns for Course table.
var Course__Cols = []tsq.BoundColumn[Course]{
	Course_CreatedAt,
	Course_ID,
	Course_InstructorID,
	Course_Level,
	Course_ListPriceCents,
	Course_PrerequisiteID,
	Course_Published,
	Course_Summary,
	Course_Title,
	Course_TrackID,
}

// =============================================================================
// Query by Primary Key
// =============================================================================
// QueryCourseByID stores the generated primary-key lookup query for Course.
var QueryCourseByID = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_ID.EQVar(),
	).
	MustBuild()

// QueryCourseByIDIn stores the generated primary-key IN lookup query for Course.
var QueryCourseByIDIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_ID.InVar(),
	).
	MustBuild()

// FetchCourseByID returns the Course rows whose ID is one of the given
// values, in the order given. It fails with an error wrapping sql.ErrNoRows when
// any of them is missing.
func FetchCourseByID(
	ctx context.Context,
	db tsq.Executor,
	iDs ...int64,
) ([]*Course, error) {
	list, err := QueryCourseByIDIn.List(ctx, db, iDs)
	if err != nil {
		return nil, fmt.Errorf("fetch Course by ID: %w", err)
	}

	ordered, missing := matchByInputOrder(iDs, list, func(row *Course) int64 {
		return row.ID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Course by ID %v: %w", missing, tsqsql.ErrNoRows)
	}
	return ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
// QueryCourseByTitle stores the generated unique-index lookup query for Course.
var QueryCourseByTitle = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_Title.EQVar(),
	).
	MustBuild()

// FetchCourseByTitle returns the Course rows matching unique index ux_course_title, one per
// Title value, in the order given. It fails with an error wrapping
// sql.ErrNoRows when any of them is missing.
func FetchCourseByTitle(
	ctx context.Context,
	db tsq.Executor,
	titles ...string,
) ([]*Course, error) {
	list, err := QueryCourseByTitleIn.List(ctx, db,
		titles,
	)
	if err != nil {
		return nil, fmt.Errorf("fetch Course by Title: %w", err)
	}

	ordered, missing := matchByInputOrderKey(titles, list,
		func(row *Course) string { return lookupKey(row.Title) },
		func(input string) string { return lookupKey(input) },
	)
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Course by Title %v: %w", missing, tsqsql.ErrNoRows)
	}
	return ordered, nil
}

// =============================================================================
// Query by Indexes
// =============================================================================
// QueryCourseByInstructorID stores the generated index query for Course.
var QueryCourseByInstructorID = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Search(TableCourse.SearchColumns()...).
	Where(
		Course_InstructorID.EQVar(),
	).
	MustBuild()

// QueryCourseByInstructorIDIn stores the generated index query for Course.
var QueryCourseByInstructorIDIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_InstructorID.InVar(),
	).
	MustBuild()

// QueryCourseByPrerequisiteID stores the generated index query for Course.
var QueryCourseByPrerequisiteID = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Search(TableCourse.SearchColumns()...).
	Where(
		Course_PrerequisiteID.EQVar(),
	).
	MustBuild()

// QueryCourseByPrerequisiteIDIn stores the generated index query for Course.
var QueryCourseByPrerequisiteIDIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_PrerequisiteID.InVar(),
	).
	MustBuild()

// QueryCourseByTitleIn stores the generated index query for Course.
var QueryCourseByTitleIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_Title.InVar(),
	).
	MustBuild()

// QueryCourseByTrackID stores the generated index query for Course.
var QueryCourseByTrackID = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Search(TableCourse.SearchColumns()...).
	Where(
		Course_TrackID.EQVar(),
	).
	MustBuild()

// QueryCourseByTrackIDIn stores the generated index query for Course.
var QueryCourseByTrackIDIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_TrackID.InVar(),
	).
	MustBuild()

// =============================================================================
// List All Records
// =============================================================================
// QueryCourse stores the generated list-all query for Course.
var QueryCourse = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Search(TableCourse.SearchColumns()...).
	MustBuild()

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Course record.
func (c *Course) Insert(
	ctx context.Context,
	db tsq.Executor,
) error {
	if !c.CreatedAt.Valid {
		c.CreatedAt = null.TimeFrom(tsqtime.Now())
	}
	err := tsq.Insert(ctx, db, c)
	if err != nil {
		return fmt.Errorf("insert Course: %w", err)
	}
	return nil
}

// Update updates an existing Course record.
func (c *Course) Update(
	ctx context.Context,
	db tsq.Executor,
) error {
	err := tsq.Update(ctx, db, c)
	if err != nil {
		return fmt.Errorf("update Course ID=%v: %w", c.ID, err)
	}
	return nil
}

// Delete removes a Course record from the database.
//
// Course declares no deleted_at column, so Delete and HardDelete are the
// same operation.
func (c *Course) Delete(
	ctx context.Context,
	db tsq.Executor,
) error {
	err := tsq.Delete(ctx, db, c)
	if err != nil {
		return fmt.Errorf("delete Course ID=%v: %w", c.ID, err)
	}
	return nil
}

// HardDelete removes a Course record from the database.
func (c *Course) HardDelete(
	ctx context.Context,
	db tsq.Executor,
) error {
	err := tsq.HardDelete(ctx, db, c)
	if err != nil {
		return fmt.Errorf("hard-delete Course ID=%v: %w", c.ID, err)
	}
	return nil
}
