// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"fmt"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
	null "gopkg.in/nullbio/null.v6"
)

// tsqCourseTable is TableCourse before its definition; columns are declared on it.
var tsqCourseTable = tsq.NewTable[Course]("course")

// Columns of Course.
var (
	Course_CreatedAt      = tsq.NewColumn(tsqCourseTable, "created_at", "created_at", func(r *Course) *null.Time { return &r.CreatedAt })
	Course_ID             = tsq.NewColumn(tsqCourseTable, "id", "id", func(r *Course) *int64 { return &r.ID })
	Course_InstructorID   = tsq.NewColumn(tsqCourseTable, "instructor_id", "instructor_id", func(r *Course) *int64 { return &r.InstructorID })
	Course_Level          = tsq.NewColumn(tsqCourseTable, "level", "level", func(r *Course) *CourseLevel { return &r.Level })
	Course_ListPriceCents = tsq.NewColumn(tsqCourseTable, "list_price_cents", "list_price_cents", func(r *Course) *int64 { return &r.ListPriceCents })
	Course_PrerequisiteID = tsq.NewColumn(tsqCourseTable, "prerequisite_id", "prerequisite_id", func(r *Course) *int64 { return &r.PrerequisiteID })
	Course_Published      = tsq.NewColumn(tsqCourseTable, "published", "published", func(r *Course) *bool { return &r.Published })
	Course_Summary        = tsq.NewColumn(tsqCourseTable, "summary", "summary", func(r *Course) *string { return &r.Summary })
	Course_Title          = tsq.NewColumn(tsqCourseTable, "title", "title", func(r *Course) *string { return &r.Title })
	Course_TrackID        = tsq.NewColumn(tsqCourseTable, "track_id", "track_id", func(r *Course) *int64 { return &r.TrackID })
)

// TableCourse is the table descriptor of Course. It depends on every column, so
// package initialization completes the table before any query uses it.
var TableCourse = tsqCourseTable.Define(tsq.TableSpec[Course]{
	Columns: []tsq.BoundColumn[Course]{
		Course_CreatedAt,
		Course_ID,
		Course_InstructorID,
		Course_Level,
		Course_ListPriceCents,
		Course_PrerequisiteID,
		Course_Published,
		Course_Summary,
		Course_Title,
		Course_TrackID,
	},
	PrimaryKey:    Course_ID,
	AutoIncrement: true,
	CreatedAt:     Course_CreatedAt,
	Search: []tsq.SearchColumn{
		tsq.Searchable(Course_Title),
		tsq.Searchable(Course_Summary),
	},
	Schema: []tsqdialect.ColumnSpec{
		{
			Name: "id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
			PrimaryKey:    true,
			AutoIncrement: true,
		},
		{
			Name: "created_at",
			Type: tsqdialect.ColumnType{
				Kind:     tsqdialect.KindTime,
				Nullable: true,
			},
		},
		{
			Name: "instructor_id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "level",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 32,
			},
		},
		{
			Name: "list_price_cents",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "prerequisite_id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "published",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindBool,
			},
		},
		{
			Name: "summary",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 4096,
			},
		},
		{
			Name: "title",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 160,
			},
		},
		{
			Name: "track_id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
	},
	Indexes: []tsq.TableIndex{
		{Name: "ux_course_title", Unique: true, Fields: []string{"title"}},
		{Name: "idx_course_instructor_id", Fields: []string{"instructor_id"}},
		{Name: "idx_course_prerequisite_id", Fields: []string{"prerequisite_id"}},
		{Name: "idx_course_track_id", Fields: []string{"track_id"}},
	},
})

// Course__Cols lists every column of Course, for Select.
var Course__Cols = TableCourse.Columns()

// QueryCourseByID reads one Course by primary key; bind Course_ID.
var QueryCourseByID = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_ID.EQ(Course_ID.Param()),
	).
	MustBuild()

// QueryCourseByIDIn reads Course rows by a list of primary keys; bind Course_ID with BindList.
var QueryCourseByIDIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_ID.In(Course_ID.ListParam()),
	).
	MustBuild()

// FetchCourseByID returns the Course rows with the given primary keys,
// in the order given. It fails with an error wrapping sql.ErrNoRows when any of
// them is missing.
func FetchCourseByID(
	ctx context.Context,
	db tsq.Executor,
	iDs ...int64,
) ([]*Course, error) {
	list, err := QueryCourseByIDIn.List(ctx, db, Course_ID.BindList(iDs...))
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrder(iDs, list, func(row *Course) int64 {
		return row.ID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Course by ID %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryCourseByTitle reads one Course by unique index ux_course_title.
var QueryCourseByTitle = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_Title.EQ(Course_Title.Param()),
	).
	MustBuild()

// QueryCourseByTitleIn reads Course rows by unique index ux_course_title, one per
// Title value; bind Course_Title with BindList.
var QueryCourseByTitleIn = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Where(
		Course_Title.In(Course_Title.ListParam()),
	).
	MustBuild()

// FetchCourseByTitle returns the Course rows matching unique index ux_course_title,
// one per Title value, in the order given. It fails with an error wrapping
// sql.ErrNoRows when any of them is missing.
func FetchCourseByTitle(
	ctx context.Context,
	db tsq.Executor,
	titles ...string,
) ([]*Course, error) {
	list, err := QueryCourseByTitleIn.List(ctx, db,
		Course_Title.BindList(titles...),
	)
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrderKey(titles, list,
		func(row *Course) string { return lookupKey(row.Title) },
		func(input string) string { return lookupKey(input) },
	)
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Course by Title %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryCourse reads every Course row; Page matches its search columns.
var QueryCourse = tsq.
	Select(Course__Cols...).
	From(TableCourse).
	Search(TableCourse.SearchColumns()...).
	MustBuild()

// Insert inserts the row; see tsq.TableOf.Insert.
func (c *Course) Insert(ctx context.Context, db tsq.Executor) error {
	return TableCourse.Insert(ctx, db, c)
}

// Update updates the row; see tsq.TableOf.Update.
func (c *Course) Update(ctx context.Context, db tsq.Executor) error {
	return TableCourse.Update(ctx, db, c)
}

// Delete removes the row. Course has no deleted_at column, so Delete and
// HardDelete are the same.
func (c *Course) Delete(ctx context.Context, db tsq.Executor) error {
	return TableCourse.Delete(ctx, db, c)
}

// HardDelete removes the row from the table.
func (c *Course) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableCourse.HardDelete(ctx, db, c)
}
