// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// EnrollmentTable is the enrollment table: the descriptor of Enrollment rows, with one field
// per column.
type EnrollmentTable struct {
	*tsq.SoftDeleteTableOf[Enrollment, int64]

	CourseID  tsq.Column[Enrollment, int64]
	CreatedAt tsq.Column[Enrollment, tsqtime.Time]
	DeletedAt tsq.Column[Enrollment, int64]
	FeeCents  tsq.Column[Enrollment, int64]
	LearnerID tsq.Column[Enrollment, int64]
	Score     tsq.Column[Enrollment, int64]
	Status    tsq.Column[Enrollment, EnrollmentStatus]
	UID       tsq.Column[Enrollment, int64]
	UpdatedAt tsq.NullColumn[Enrollment, tsqtime.Time]
	Version   tsq.Column[Enrollment, int64]
}

// TableEnrollment is the enrollment table.
var TableEnrollment = newEnrollmentTable()

// newEnrollmentTable declares the table, its columns, then its definition, so that
// anything naming TableEnrollment is initialized after the table is complete.
func newEnrollmentTable() EnrollmentTable {
	t := tsq.NewSoftDeleteTable[Enrollment, int64]("enrollment")
	c := EnrollmentTable{
		SoftDeleteTableOf: t,
		CourseID:          tsq.NewColumn(t.TableOf, "course_id", "course_id", func(r *Enrollment) *int64 { return &r.CourseID }),
		CreatedAt:         tsq.NewColumn(t.TableOf, "created_at", "created_at", func(r *Enrollment) *tsqtime.Time { return &r.CreatedAt }),
		DeletedAt:         tsq.NewColumn(t.TableOf, "deleted_at", "deleted_at", func(r *Enrollment) *int64 { return &r.DeletedAt }),
		FeeCents:          tsq.NewColumn(t.TableOf, "fee_cents", "fee_cents", func(r *Enrollment) *int64 { return &r.FeeCents }),
		LearnerID:         tsq.NewColumn(t.TableOf, "learner_id", "learner_id", func(r *Enrollment) *int64 { return &r.LearnerID }),
		Score:             tsq.NewColumn(t.TableOf, "score", "score", func(r *Enrollment) *int64 { return &r.Score }),
		Status:            tsq.NewColumn(t.TableOf, "status", "status", func(r *Enrollment) *EnrollmentStatus { return &r.Status }),
		UID:               tsq.NewColumn(t.TableOf, "uid", "uid", func(r *Enrollment) *int64 { return &r.UID }),
		UpdatedAt:         tsq.NewNullColumn[tsqtime.Time](t.TableOf, "updated_at", "updated_at", func(r *Enrollment) *tsqsql.Null[tsqtime.Time] { return &r.UpdatedAt }),
		Version:           tsq.NewColumn(t.TableOf, "version", "version", func(r *Enrollment) *int64 { return &r.Version }),
	}

	t.Define(tsq.TableSpec[Enrollment, int64]{
		Columns: []tsq.BoundColumn[Enrollment]{
			c.CourseID,
			c.CreatedAt,
			c.DeletedAt,
			c.FeeCents,
			c.LearnerID,
			c.Score,
			c.Status,
			c.UID,
			c.UpdatedAt,
			c.Version,
		},
		PrimaryKey:    c.UID,
		AutoIncrement: true,
		Version:       c.Version,
		CreatedAt:     c.CreatedAt,
		UpdatedAt:     c.UpdatedAt,
		ColumnSpecs: []tsqdialect.ColumnSpec{
			{
				Name: "uid",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				PrimaryKey:    true,
				AutoIncrement: true,
			},
			{
				Name: "created_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindTime,
				},
				Default: "CURRENT_TIMESTAMP",
			},
			{
				Name: "updated_at",
				Type: tsqdialect.ColumnType{
					Kind:     tsqdialect.KindTime,
					Nullable: true,
				},
			},
			{
				Name: "deleted_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				Default: "0",
			},
			{
				Name: "version",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				Default: "1",
			},
			{
				Name: "course_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "fee_cents",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "learner_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "score",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "status",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 32,
				},
			},
		},
		Indexes: []tsq.TableIndex{
			{Name: "idx_enrollment_course_id", Columns: []string{"deleted_at", "course_id"}},
			{Name: "idx_enrollment_learner_id_course_id", Columns: []string{"deleted_at", "learner_id", "course_id"}},
			{Name: "idx_enrollment_status", Columns: []string{"deleted_at", "status"}},
		},
	}, c.DeletedAt)

	return c
}

// As returns the table under alias, with every column bound to the alias, for
// joining the table more than once.
func (t EnrollmentTable) As(alias string) EnrollmentTable {
	a := t.SoftDeleteTableOf.As(alias)

	return EnrollmentTable{
		SoftDeleteTableOf: a,
		CourseID:          t.CourseID.WithTable(a),
		CreatedAt:         t.CreatedAt.WithTable(a),
		DeletedAt:         t.DeletedAt.WithTable(a),
		FeeCents:          t.FeeCents.WithTable(a),
		LearnerID:         t.LearnerID.WithTable(a),
		Score:             t.Score.WithTable(a),
		Status:            t.Status.WithTable(a),
		UID:               t.UID.WithTable(a),
		UpdatedAt:         t.UpdatedAt.WithTable(a).(tsq.NullColumn[Enrollment, tsqtime.Time]),
		Version:           t.Version.WithTable(a),
	}
}

// WithDeleted returns the table without its live-row filter; see
// tsq.SoftDeleteTableOf.WithDeleted.
func (t EnrollmentTable) WithDeleted() EnrollmentTable {
	t.SoftDeleteTableOf = t.SoftDeleteTableOf.WithDeleted()

	return t
}

// Insert inserts the row; see tsq.TableOf.Insert.
func (e *Enrollment) Insert(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.Insert(ctx, db, e)
}

// Update writes the row, or only cols when given; see tsq.TableOf.Update.
func (e *Enrollment) Update(ctx context.Context, db tsq.Executor, cols ...tsq.BoundColumn[Enrollment]) error {
	return TableEnrollment.Update(ctx, db, e, cols...)
}

// Delete soft-deletes the row by stamping DeletedAt; queries naming the
// table leave it out from then on. See tsq.SoftDeleteTableOf.Delete.
func (e *Enrollment) Delete(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.Delete(ctx, db, e)
}

// HardDelete removes the row from the table. Unlike a soft delete, it cannot be undone.
func (e *Enrollment) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.HardDelete(ctx, db, e)
}

// Restore clears the row's tombstone; see tsq.SoftDeleteTableOf.Restore.
func (e *Enrollment) Restore(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.Restore(ctx, db, e)
}

// Active reports whether the row is not soft-deleted.
func (e *Enrollment) Active() bool {
	return e.DeletedAt == 0
}
