// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	"fmt"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/tmoeish/tsq/v4"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableEnrollment implements the tsq.Table interface for Enrollment.
//
// The Enrollment__Cols argument is never read. It makes this variable depend on the
// column slice so that Go initializes the slice first: Cols reaches it through an
// interface method, which package initialization ordering cannot see. Without it a
// package-level query variable in a file sorting before this one can observe
// Enrollment__Cols fully sized with nil elements.
var TableEnrollment tsq.Table = tsq.TableWithCols(Enrollment{}, Enrollment__Cols)

// TSQOwner marks Enrollment as a TSQ owner.
func (e Enrollment) TSQOwner() {}

// Table returns the database table name for Enrollment.
func (e Enrollment) Table() string { return "enrollment" }

// Cols returns all generated columns for Enrollment.
func (e Enrollment) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(Enrollment__Cols...)
}

// SearchColumns returns columns that support keyword search for Enrollment.
func (e Enrollment) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{}
}

// PrimaryKey returns the primary key column for Enrollment.
func (e Enrollment) PrimaryKey() string {
	return "uid"
}

// AutoIncrement reports whether Enrollment uses an auto-increment primary key.
func (e Enrollment) AutoIncrement() bool { return true }

// ManagedColumns returns the columns TSQ maintains for Enrollment.
func (e Enrollment) ManagedColumns() tsq.ManagedColumns {
	return tsq.ManagedColumns{
		Version:   "version",
		CreatedAt: "created_at",
		UpdatedAt: "updated_at",
		DeletedAt: "deleted_at",
	}
}

// Active returns true if the Enrollment record is not soft-deleted.
func (e *Enrollment) Active() bool {
	return e.DeletedAt == 0
}

// Column definitions for Enrollment table.
var (
	Enrollment_CourseID  = tsq.NewCol("course_id", "course_id", func(t *Enrollment) *int64 { return &t.CourseID })
	Enrollment_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *Enrollment) *tsqtime.Time { return &t.CreatedAt })
	Enrollment_DeletedAt = tsq.NewCol("deleted_at", "deleted_at", func(t *Enrollment) *int64 { return &t.DeletedAt })
	Enrollment_FeeCents  = tsq.NewCol("fee_cents", "fee_cents", func(t *Enrollment) *int64 { return &t.FeeCents })
	Enrollment_LearnerID = tsq.NewCol("learner_id", "learner_id", func(t *Enrollment) *int64 { return &t.LearnerID })
	Enrollment_Score     = tsq.NewCol("score", "score", func(t *Enrollment) *int64 { return &t.Score })
	Enrollment_Status    = tsq.NewCol("status", "status", func(t *Enrollment) *EnrollmentStatus { return &t.Status })
	Enrollment_UID       = tsq.NewCol("uid", "uid", func(t *Enrollment) *int64 { return &t.UID })
	Enrollment_UpdatedAt = tsq.NewCol("updated_at", "updated_at", func(t *Enrollment) *null.Time { return &t.UpdatedAt })
	Enrollment_Version   = tsq.NewCol("version", "version", func(t *Enrollment) *int64 { return &t.Version })
)

// Enrollment__Cols is the list of all selectable columns for Enrollment table.
var Enrollment__Cols = []tsq.BoundColumn[Enrollment]{
	Enrollment_CourseID,
	Enrollment_CreatedAt,
	Enrollment_DeletedAt,
	Enrollment_FeeCents,
	Enrollment_LearnerID,
	Enrollment_Score,
	Enrollment_Status,
	Enrollment_UID,
	Enrollment_UpdatedAt,
	Enrollment_Version,
}

// =============================================================================
// Query by Primary Key
// =============================================================================
// QueryEnrollmentByUID stores the generated primary-key lookup query for Enrollment.
var QueryEnrollmentByUID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_UID.EQVar(),
	).
	MustBuild()

// QueryEnrollmentByUIDIn stores the generated primary-key IN lookup query for Enrollment.
var QueryEnrollmentByUIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_UID.InVar(),
	).
	MustBuild()

// ListEnrollmentByUIDInOrErr retrieves multiple Enrollment records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListEnrollmentByUIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	uIDs ...int64,
) ([]*Enrollment, error) {
	list, err := QueryEnrollmentByUIDIn.List(ctx, db, uIDs)
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrder(uIDs, list, func(row *Enrollment) int64 {
		return row.UID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("records not found: %v", missing)
	}
	return ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================

// =============================================================================
// Query by Indexes
// =============================================================================
// QueryEnrollmentByCourseID stores the generated index query for Enrollment.
var QueryEnrollmentByCourseID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Search(TableEnrollment.SearchColumns()...).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_CourseID.EQVar(),
	).
	MustBuild()

// QueryEnrollmentByCourseIDIn stores the generated index query for Enrollment.
var QueryEnrollmentByCourseIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_CourseID.InVar(),
	).
	MustBuild()

// QueryEnrollmentByLearnerID stores the generated index query for Enrollment.
var QueryEnrollmentByLearnerID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Search(TableEnrollment.SearchColumns()...).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.EQVar(),
	).
	MustBuild()

// QueryEnrollmentByLearnerIDAndCourseID stores the generated index query for Enrollment.
var QueryEnrollmentByLearnerIDAndCourseID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Search(TableEnrollment.SearchColumns()...).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.EQVar(),
		Enrollment_CourseID.EQVar(),
	).
	MustBuild()

// QueryEnrollmentByLearnerIDAndCourseIDIn stores the generated index query for Enrollment.
var QueryEnrollmentByLearnerIDAndCourseIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.EQVar(),
		Enrollment_CourseID.InVar(),
	).
	MustBuild()

// QueryEnrollmentByLearnerIDIn stores the generated index query for Enrollment.
var QueryEnrollmentByLearnerIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.InVar(),
	).
	MustBuild()

// QueryEnrollmentByStatus stores the generated index query for Enrollment.
var QueryEnrollmentByStatus = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Search(TableEnrollment.SearchColumns()...).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_Status.EQVar(),
	).
	MustBuild()

// QueryEnrollmentByStatusIn stores the generated index query for Enrollment.
var QueryEnrollmentByStatusIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_Status.InVar(),
	).
	MustBuild()

// =============================================================================
// List All Records
// =============================================================================
// QueryEnrollment stores the generated list-all query for Enrollment.
var QueryEnrollment = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Search(TableEnrollment.SearchColumns()...).
	Where(Enrollment_DeletedAt.EQVal(0)).
	MustBuild()

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Enrollment record.
func (e *Enrollment) Insert(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	if e.CreatedAt.IsZero() {
		e.CreatedAt = tsqtime.Now()
	}
	if !e.UpdatedAt.Valid {
		e.UpdatedAt = null.TimeFrom(tsqtime.Now())
	}
	err := tsq.Insert(ctx, db, e)
	if err != nil {
		return fmt.Errorf("insert Enrollment: %s: %w", compactJSON(e), err)
	}
	return nil
}

// Update updates an existing Enrollment record.
func (e *Enrollment) Update(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	e.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Update(ctx, db, e)
	if err != nil {
		return fmt.Errorf("update Enrollment: %s: %w", compactJSON(e), err)
	}
	return nil
}

// Delete soft-deletes a Enrollment record by stamping DeletedAt.
//
// The row stays in the table and drops out of every generated query. Use
// HardDelete to remove it from the database.
func (e *Enrollment) Delete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Delete(ctx, db, e)
	if err != nil {
		return fmt.Errorf("delete Enrollment: %s: %w", compactJSON(e), err)
	}
	return nil
}

// HardDelete removes a Enrollment record from the database.
//
// This is not reversible: a soft-deleted row can be restored by clearing
// DeletedAt, a hard-deleted one cannot.
func (e *Enrollment) HardDelete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.HardDelete(ctx, db, e)
	if err != nil {
		return fmt.Errorf("hard-delete Enrollment: %s: %w", compactJSON(e), err)
	}
	return nil
}
