// Code generated by tsq-v3.7.1. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableEnrollment implements the tsq.Table interface for Enrollment.
var TableEnrollment tsq.Table = Enrollment{}

// TSQOwner marks Enrollment as a TSQ owner.
func (e Enrollment) TSQOwner() {}

// Table returns the database table name for Enrollment.
func (e Enrollment) Table() string { return "enrollment" }

// Cols returns all generated columns for Enrollment.
func (e Enrollment) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(Enrollment__Cols...)
}

// SearchColumns returns columns that support keyword search for Enrollment.
func (e Enrollment) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{}
}

// PrimaryKeys returns the primary key columns for Enrollment.
func (e Enrollment) PrimaryKeys() []string {
	return []string{"uid"}
}

// AutoIncrement reports whether Enrollment uses an auto-increment primary key.
func (e Enrollment) AutoIncrement() bool { return true }

// VersionColumn returns the optimistic-lock version column for Enrollment, if any.
func (e Enrollment) VersionColumn() string {
	return "version"
}

// Active returns true if the Enrollment record is not soft-deleted.
func (e *Enrollment) Active() bool {
	return e.DeletedAt == 0
}

// Column definitions for Enrollment table.
var (
	Enrollment_CourseID  = tsq.NewCol("course_id", "course_id", func(t *Enrollment) *int64 { return &t.CourseID })
	Enrollment_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *Enrollment) *tsqtime.Time { return &t.CreatedAt })
	Enrollment_DeletedAt = tsq.NewCol("deleted_at", "deleted_at", func(t *Enrollment) *int64 { return &t.DeletedAt })
	Enrollment_FeeCents  = tsq.NewCol("fee_cents", "fee_cents", func(t *Enrollment) *int64 { return &t.FeeCents })
	Enrollment_LearnerID = tsq.NewCol("learner_id", "learner_id", func(t *Enrollment) *int64 { return &t.LearnerID })
	Enrollment_Score     = tsq.NewCol("score", "score", func(t *Enrollment) *int64 { return &t.Score })
	Enrollment_Status    = tsq.NewCol("status", "status", func(t *Enrollment) *EnrollmentStatus { return &t.Status })
	Enrollment_UID       = tsq.NewCol("uid", "uid", func(t *Enrollment) *int64 { return &t.UID })
	Enrollment_UpdatedAt = tsq.NewCol("updated_at", "updated_at", func(t *Enrollment) *null.Time { return &t.UpdatedAt })
	Enrollment_Version   = tsq.NewCol("version", "version", func(t *Enrollment) *int64 { return &t.Version })
)

// Enrollment__Cols is the list of all selectable columns for Enrollment table.
var Enrollment__Cols = []tsq.BoundColumn[Enrollment]{
	Enrollment_CourseID,
	Enrollment_CreatedAt,
	Enrollment_DeletedAt,
	Enrollment_FeeCents,
	Enrollment_LearnerID,
	Enrollment_Score,
	Enrollment_Status,
	Enrollment_UID,
	Enrollment_UpdatedAt,
	Enrollment_Version,
}

// =============================================================================
// Table Registration and Index Initialization
// =============================================================================

func init() {
	tsq.RegisterTable(
		TableEnrollment,
		func(db *tsq.Engine) error {
			// Upsert non-unique indexes.
			if err := tsq.UpsertIndex(db, "enrollment", false, "idx_enrollment_course_id", []string{"deleted_at", "course_id"}); err != nil {
				return errors.Annotate(err, "upsert idx_enrollment_course_id@enrollment")
			}
			if err := tsq.UpsertIndex(db, "enrollment", false, "idx_enrollment_learner_id_course_id", []string{"deleted_at", "learner_id", "course_id"}); err != nil {
				return errors.Annotate(err, "upsert idx_enrollment_learner_id_course_id@enrollment")
			}
			if err := tsq.UpsertIndex(db, "enrollment", false, "idx_enrollment_status", []string{"deleted_at", "status"}); err != nil {
				return errors.Annotate(err, "upsert idx_enrollment_status@enrollment")
			}
			return nil
		},
	)
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getEnrollmentByUIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	getEnrollmentByUIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(Enrollment_UID.EQVar()).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getEnrollmentByUIDQuery"))
	}
}

// GetEnrollmentByUID retrieves a Enrollment record by its primary key.
// Returns (nil, nil) if the record is not found.
func GetEnrollmentByUID(
	ctx context.Context,
	db tsq.SQLExecutor,
	uID int64,
) (*Enrollment, error) {
	row := &Enrollment{}
	err := getEnrollmentByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetEnrollmentByUIDOrErr retrieves a Enrollment record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetEnrollmentByUIDOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	uID int64,
) (*Enrollment, error) {
	row := &Enrollment{}
	err := getEnrollmentByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ListEnrollmentByUIDIn retrieves multiple Enrollment records by a set of primary key values.
// Records not found are silently ignored.
func ListEnrollmentByUIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	uIDs ...int64,
) ([]*Enrollment, error) {
	query, err := tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(Enrollment_UID.In(uIDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}
	return tsq.List(ctx, db, query)
}

// ListEnrollmentByUIDInOrErr retrieves multiple Enrollment records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListEnrollmentByUIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	uIDs ...int64,
) ([]*Enrollment, error) {
	query, err := tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(Enrollment_UID.In(uIDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(uIDs, list, func(row *Enrollment) int64 {
		return row.UID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Enrollment(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// Query Active Records by Primary Key
// =============================================================================
var getActiveEnrollmentByUIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	getActiveEnrollmentByUIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_UID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getActiveEnrollmentByUIDQuery"))
	}
}

// GetActiveEnrollmentByUID retrieves an active Enrollment record by its primary key.
// Returns (nil, nil) if the record is not found or has been soft-deleted.
func GetActiveEnrollmentByUID(
	ctx context.Context,
	db tsq.SQLExecutor,
	uID int64,
) (*Enrollment, error) {
	row := &Enrollment{}
	err := getActiveEnrollmentByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetActiveEnrollmentByUIDOrErr retrieves an active Enrollment record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found or has been soft-deleted.
func GetActiveEnrollmentByUIDOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	uID int64,
) (*Enrollment, error) {
	row := &Enrollment{}
	err := getActiveEnrollmentByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ListActiveEnrollmentByUIDIn retrieves multiple active Enrollment records by a set of primary key values.
// Records not found or soft-deleted are silently ignored.
func ListActiveEnrollmentByUIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	uIDs ...int64,
) ([]*Enrollment, error) {
	query, err := tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_UID.In(uIDs...),
		).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}
	return tsq.List(ctx, db, query)
}

// ListActiveEnrollmentByUIDInOrErr retrieves multiple active Enrollment records by a set of primary key values.
// Returns an error if any of the specified active records are not found.
func ListActiveEnrollmentByUIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	uIDs ...int64,
) ([]*Enrollment, error) {
	query, err := tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_UID.In(uIDs...),
		).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}
	match := tsq.MatchByInputOrder(uIDs, list, func(row *Enrollment) int64 {
		return row.UID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Enrollment(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
// =============================================================================
// Query Active Records by Unique Indexes
// =============================================================================

// =============================================================================
// Query by Indexes
// =============================================================================
var ListEnrollmentByCourseIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByCourseIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_CourseID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByCourseIDQuery"))
	}
}

// CountEnrollmentByCourseID returns the count of Enrollment records matching index idx_enrollment_course_id.
func CountEnrollmentByCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	courseID int64,
) (int, error) {
	rs, err := ListEnrollmentByCourseIDQuery.Count(
		ctx, db,
		courseID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return rs, nil
}

// ListEnrollmentByCourseID retrieves Enrollment records by index idx_enrollment_course_id.
func ListEnrollmentByCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	courseID int64,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, ListEnrollmentByCourseIDQuery,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return data, nil
}

// PageEnrollmentByCourseID retrieves Enrollment records by index idx_enrollment_course_id with pagination.
func PageEnrollmentByCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	courseID int64,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, ListEnrollmentByCourseIDQuery,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return rs, nil
}

var ListEnrollmentByCourseIDInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByCourseIDInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_CourseID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByCourseIDInQuery"))
	}
}

// ListEnrollmentByCourseIDIn retrieves multiple Enrollment records by index idx_enrollment_course_id using an IN clause.
func ListEnrollmentByCourseIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	courseIDs ...int64,
) ([]*Enrollment, error) {
	list, err := tsq.List(
		ctx, db, ListEnrollmentByCourseIDInQuery,
		courseIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return list, nil
}

var ListEnrollmentByLearnerIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByLearnerIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_LearnerID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByLearnerIDQuery"))
	}
}

// CountEnrollmentByLearnerID returns the count of Enrollment records matching index idx_enrollment_learner_id_course_id.
func CountEnrollmentByLearnerID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
) (int, error) {
	rs, err := ListEnrollmentByLearnerIDQuery.Count(
		ctx, db,
		learnerID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

// ListEnrollmentByLearnerID retrieves Enrollment records by index idx_enrollment_learner_id_course_id.
func ListEnrollmentByLearnerID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, ListEnrollmentByLearnerIDQuery,
		learnerID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return data, nil
}

// PageEnrollmentByLearnerID retrieves Enrollment records by index idx_enrollment_learner_id_course_id with pagination.
func PageEnrollmentByLearnerID(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	learnerID int64,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, ListEnrollmentByLearnerIDQuery,
		learnerID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

var ListEnrollmentByLearnerIDAndCourseIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByLearnerIDAndCourseIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_LearnerID.EQVar(),
			Enrollment_CourseID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByLearnerIDAndCourseIDQuery"))
	}
}

// CountEnrollmentByLearnerIDAndCourseID returns the count of Enrollment records matching index idx_enrollment_learner_id_course_id.
func CountEnrollmentByLearnerIDAndCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
	courseID int64,
) (int, error) {
	rs, err := ListEnrollmentByLearnerIDAndCourseIDQuery.Count(
		ctx, db,
		learnerID,
		courseID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

// ListEnrollmentByLearnerIDAndCourseID retrieves Enrollment records by index idx_enrollment_learner_id_course_id.
func ListEnrollmentByLearnerIDAndCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
	courseID int64,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, ListEnrollmentByLearnerIDAndCourseIDQuery,
		learnerID,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return data, nil
}

// PageEnrollmentByLearnerIDAndCourseID retrieves Enrollment records by index idx_enrollment_learner_id_course_id with pagination.
func PageEnrollmentByLearnerIDAndCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	learnerID int64,
	courseID int64,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, ListEnrollmentByLearnerIDAndCourseIDQuery,
		learnerID,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

var ListEnrollmentByLearnerIDAndCourseIDInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByLearnerIDAndCourseIDInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_LearnerID.EQVar(),
			Enrollment_CourseID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByLearnerIDAndCourseIDInQuery"))
	}
}

// ListEnrollmentByLearnerIDAndCourseIDIn retrieves multiple Enrollment records by index idx_enrollment_learner_id_course_id using an IN clause.
func ListEnrollmentByLearnerIDAndCourseIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
	courseIDs ...int64,
) ([]*Enrollment, error) {
	list, err := tsq.List(
		ctx, db, ListEnrollmentByLearnerIDAndCourseIDInQuery,
		learnerID,
		courseIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return list, nil
}

var ListEnrollmentByLearnerIDInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByLearnerIDInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_LearnerID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByLearnerIDInQuery"))
	}
}

// ListEnrollmentByLearnerIDIn retrieves multiple Enrollment records by index idx_enrollment_learner_id_course_id using an IN clause.
func ListEnrollmentByLearnerIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerIDs ...int64,
) ([]*Enrollment, error) {
	list, err := tsq.List(
		ctx, db, ListEnrollmentByLearnerIDInQuery,
		learnerIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return list, nil
}

var ListEnrollmentByStatusQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByStatusQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_Status.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByStatusQuery"))
	}
}

// CountEnrollmentByStatus returns the count of Enrollment records matching index idx_enrollment_status.
func CountEnrollmentByStatus(
	ctx context.Context,
	db tsq.SQLExecutor,
	status EnrollmentStatus,
) (int, error) {
	rs, err := ListEnrollmentByStatusQuery.Count(
		ctx, db,
		status,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return rs, nil
}

// ListEnrollmentByStatus retrieves Enrollment records by index idx_enrollment_status.
func ListEnrollmentByStatus(
	ctx context.Context,
	db tsq.SQLExecutor,
	status EnrollmentStatus,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, ListEnrollmentByStatusQuery,
		status,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return data, nil
}

// PageEnrollmentByStatus retrieves Enrollment records by index idx_enrollment_status with pagination.
func PageEnrollmentByStatus(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	status EnrollmentStatus,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, ListEnrollmentByStatusQuery,
		status,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return rs, nil
}

var ListEnrollmentByStatusInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListEnrollmentByStatusInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_Status.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListEnrollmentByStatusInQuery"))
	}
}

// ListEnrollmentByStatusIn retrieves multiple Enrollment records by index idx_enrollment_status using an IN clause.
func ListEnrollmentByStatusIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	statuss ...EnrollmentStatus,
) ([]*Enrollment, error) {
	list, err := tsq.List(
		ctx, db, ListEnrollmentByStatusInQuery,
		statuss,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return list, nil
}

// =============================================================================
// Query Active Records by Indexes
// =============================================================================
var listActiveEnrollmentByCourseIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	listActiveEnrollmentByCourseIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_CourseID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveEnrollmentByCourseIDQuery"))
	}
}

// CountActiveEnrollmentByCourseID returns the count of active Enrollment records matching index idx_enrollment_course_id.
func CountActiveEnrollmentByCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	courseID int64,
) (int, error) {
	rs, err := listActiveEnrollmentByCourseIDQuery.Count(
		ctx, db,
		courseID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return rs, nil
}

// ListActiveEnrollmentByCourseID retrieves active Enrollment records by index idx_enrollment_course_id.
func ListActiveEnrollmentByCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	courseID int64,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, listActiveEnrollmentByCourseIDQuery,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return data, nil
}

// PageActiveEnrollmentByCourseID retrieves active Enrollment records by index idx_enrollment_course_id with pagination.
func PageActiveEnrollmentByCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	courseID int64,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, listActiveEnrollmentByCourseIDQuery,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return rs, nil
}

var ListActiveEnrollmentByCourseIDInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListActiveEnrollmentByCourseIDInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_CourseID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveEnrollmentByCourseIDInQuery"))
	}
}

// ListActiveEnrollmentByCourseIDIn retrieves active Enrollment records by index idx_enrollment_course_id using an IN clause.
func ListActiveEnrollmentByCourseIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	courseIDs ...int64,
) ([]*Enrollment, error) {
	query := ListActiveEnrollmentByCourseIDInQuery
	list, err := tsq.List(
		ctx, db, query,
		courseIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_course_id")
	}
	return list, nil
}

var listActiveEnrollmentByLearnerIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	listActiveEnrollmentByLearnerIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_LearnerID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveEnrollmentByLearnerIDQuery"))
	}
}

// CountActiveEnrollmentByLearnerID returns the count of active Enrollment records matching index idx_enrollment_learner_id_course_id.
func CountActiveEnrollmentByLearnerID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
) (int, error) {
	rs, err := listActiveEnrollmentByLearnerIDQuery.Count(
		ctx, db,
		learnerID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

// ListActiveEnrollmentByLearnerID retrieves active Enrollment records by index idx_enrollment_learner_id_course_id.
func ListActiveEnrollmentByLearnerID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, listActiveEnrollmentByLearnerIDQuery,
		learnerID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return data, nil
}

// PageActiveEnrollmentByLearnerID retrieves active Enrollment records by index idx_enrollment_learner_id_course_id with pagination.
func PageActiveEnrollmentByLearnerID(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	learnerID int64,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, listActiveEnrollmentByLearnerIDQuery,
		learnerID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

var listActiveEnrollmentByLearnerIDAndCourseIDQuery *tsq.Query[Enrollment]

func init() {
	var err error
	listActiveEnrollmentByLearnerIDAndCourseIDQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_LearnerID.EQVar(),
			Enrollment_CourseID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveEnrollmentByLearnerIDAndCourseIDQuery"))
	}
}

// CountActiveEnrollmentByLearnerIDAndCourseID returns the count of active Enrollment records matching index idx_enrollment_learner_id_course_id.
func CountActiveEnrollmentByLearnerIDAndCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
	courseID int64,
) (int, error) {
	rs, err := listActiveEnrollmentByLearnerIDAndCourseIDQuery.Count(
		ctx, db,
		learnerID,
		courseID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

// ListActiveEnrollmentByLearnerIDAndCourseID retrieves active Enrollment records by index idx_enrollment_learner_id_course_id.
func ListActiveEnrollmentByLearnerIDAndCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
	courseID int64,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, listActiveEnrollmentByLearnerIDAndCourseIDQuery,
		learnerID,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return data, nil
}

// PageActiveEnrollmentByLearnerIDAndCourseID retrieves active Enrollment records by index idx_enrollment_learner_id_course_id with pagination.
func PageActiveEnrollmentByLearnerIDAndCourseID(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	learnerID int64,
	courseID int64,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, listActiveEnrollmentByLearnerIDAndCourseIDQuery,
		learnerID,
		courseID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return rs, nil
}

var ListActiveEnrollmentByLearnerIDAndCourseIDInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListActiveEnrollmentByLearnerIDAndCourseIDInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_LearnerID.EQVar(),
			Enrollment_CourseID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveEnrollmentByLearnerIDAndCourseIDInQuery"))
	}
}

// ListActiveEnrollmentByLearnerIDAndCourseIDIn retrieves active Enrollment records by index idx_enrollment_learner_id_course_id using an IN clause.
func ListActiveEnrollmentByLearnerIDAndCourseIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerID int64,
	courseIDs ...int64,
) ([]*Enrollment, error) {
	query := ListActiveEnrollmentByLearnerIDAndCourseIDInQuery
	list, err := tsq.List(
		ctx, db, query,
		learnerID,
		courseIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return list, nil
}

var ListActiveEnrollmentByLearnerIDInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListActiveEnrollmentByLearnerIDInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_LearnerID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveEnrollmentByLearnerIDInQuery"))
	}
}

// ListActiveEnrollmentByLearnerIDIn retrieves active Enrollment records by index idx_enrollment_learner_id_course_id using an IN clause.
func ListActiveEnrollmentByLearnerIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	learnerIDs ...int64,
) ([]*Enrollment, error) {
	query := ListActiveEnrollmentByLearnerIDInQuery
	list, err := tsq.List(
		ctx, db, query,
		learnerIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_learner_id_course_id")
	}
	return list, nil
}

var listActiveEnrollmentByStatusQuery *tsq.Query[Enrollment]

func init() {
	var err error
	listActiveEnrollmentByStatusQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_Status.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveEnrollmentByStatusQuery"))
	}
}

// CountActiveEnrollmentByStatus returns the count of active Enrollment records matching index idx_enrollment_status.
func CountActiveEnrollmentByStatus(
	ctx context.Context,
	db tsq.SQLExecutor,
	status EnrollmentStatus,
) (int, error) {
	rs, err := listActiveEnrollmentByStatusQuery.Count(
		ctx, db,
		status,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return rs, nil
}

// ListActiveEnrollmentByStatus retrieves active Enrollment records by index idx_enrollment_status.
func ListActiveEnrollmentByStatus(
	ctx context.Context,
	db tsq.SQLExecutor,
	status EnrollmentStatus,
) ([]*Enrollment, error) {
	data, err := tsq.List(
		ctx, db, listActiveEnrollmentByStatusQuery,
		status,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return data, nil
}

// PageActiveEnrollmentByStatus retrieves active Enrollment records by index idx_enrollment_status with pagination.
func PageActiveEnrollmentByStatus(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	status EnrollmentStatus,
) (*tsq.PageResp[Enrollment], error) {
	rs, err := tsq.Page(
		ctx, db, page, listActiveEnrollmentByStatusQuery,
		status,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return rs, nil
}

var ListActiveEnrollmentByStatusInQuery *tsq.Query[Enrollment]

func init() {
	var err error
	ListActiveEnrollmentByStatusInQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Where(
			Enrollment_DeletedAt.EQ(0),
			Enrollment_Status.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveEnrollmentByStatusInQuery"))
	}
}

// ListActiveEnrollmentByStatusIn retrieves active Enrollment records by index idx_enrollment_status using an IN clause.
func ListActiveEnrollmentByStatusIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	statuss ...EnrollmentStatus,
) ([]*Enrollment, error) {
	query := ListActiveEnrollmentByStatusInQuery
	list, err := tsq.List(
		ctx, db, query,
		statuss,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_enrollment_status")
	}
	return list, nil
}

// =============================================================================
// List All Records
// =============================================================================
var listEnrollmentQuery *tsq.Query[Enrollment]

func init() {
	var err error
	listEnrollmentQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listEnrollmentQuery"))
	}
}

// CountEnrollment returns the total count of Enrollment records.
func CountEnrollment(
	ctx context.Context,
	tx tsq.SQLExecutor,
) (int, error) {
	return listEnrollmentQuery.Count(ctx, tx)
}

// ListEnrollment retrieves all Enrollment records.
func ListEnrollment(
	ctx context.Context,
	tx tsq.SQLExecutor,
) ([]*Enrollment, error) {
	return tsq.List(ctx, tx, listEnrollmentQuery)
}

// PageEnrollment retrieves Enrollment records with pagination.
func PageEnrollment(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Enrollment], error) {
	return tsq.Page(ctx, tx, page, listEnrollmentQuery)
}

// =============================================================================
// List Active Records
// =============================================================================
var listActiveEnrollmentQuery *tsq.Query[Enrollment]

func init() {
	var err error
	listActiveEnrollmentQuery, err = tsq.
		Select(Enrollment__Cols...).
		From(TableEnrollment).
		Search(TableEnrollment.SearchColumns()...).
		Where(Enrollment_DeletedAt.EQ(0)).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveEnrollmentQuery"))
	}
}

// CountActiveEnrollment returns the count of active Enrollment records.
func CountActiveEnrollment(
	ctx context.Context,
	tx tsq.SQLExecutor,
) (int, error) {
	return listActiveEnrollmentQuery.Count(ctx, tx)
}

// ListActiveEnrollment retrieves all active Enrollment records.
func ListActiveEnrollment(
	ctx context.Context,
	tx tsq.SQLExecutor,
) ([]*Enrollment, error) {
	return tsq.List(ctx, tx, listActiveEnrollmentQuery)
}

// PageActiveEnrollment retrieves active Enrollment records with pagination.
func PageActiveEnrollment(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Enrollment], error) {
	return tsq.Page(ctx, tx, page, listActiveEnrollmentQuery)
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Enrollment record.
func (e *Enrollment) Insert(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	e.CreatedAt = tsqtime.Now()
	e.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, e)
	if err != nil {
		return errors.Annotatef(err, "insert Enrollment: %s", tsq.CompactJSON(e))
	}
	return nil
}

// Update updates an existing Enrollment record.
func (e *Enrollment) Update(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	e.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Update(ctx, db, e)
	if err != nil {
		return errors.Annotatef(err, "update Enrollment: %s", tsq.CompactJSON(e))
	}
	return nil
}

// Delete permanently removes a Enrollment record.
func (e *Enrollment) Delete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Delete(ctx, db, e)
	if err != nil {
		return errors.Annotatef(err, "delete Enrollment: %s", tsq.CompactJSON(e))
	}
	return nil
}

// SoftDelete marks a Enrollment record as deleted.
func (e *Enrollment) SoftDelete(
	ctx context.Context,
	db tsq.SQLExecutor,
	dt int64,
) error {
	if dt != 0 {
		e.DeletedAt = dt
	} else {
		e.DeletedAt = tsqtime.Now().UnixNano()
	}
	e.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Update(ctx, db, e)
	if err != nil {
		return errors.Annotatef(err, "soft-delete Enrollment: %s", tsq.CompactJSON(e))
	}
	return nil
}

// =============================================================================
// Custom Query Helpers
// =============================================================================
// ListEnrollmentByQuery executes a custom query to retrieve a list of Enrollment records.
func ListEnrollmentByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	qb *tsq.Query[Enrollment],
	args ...any,
) ([]*Enrollment, error) {
	return tsq.List(ctx, tx, qb, args...)
}

// PageEnrollmentByQuery executes a custom query to retrieve a page of Enrollment records.
func PageEnrollmentByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
	qb *tsq.Query[Enrollment],
	args ...any,
) (*tsq.PageResp[Enrollment], error) {
	return tsq.Page(ctx, tx, page, qb, args...)
}
