// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"fmt"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// tsqEnrollmentTable is TableEnrollment before its definition; columns are declared on it.
var tsqEnrollmentTable = tsq.NewTable[Enrollment]("enrollment")

// Columns of Enrollment.
var (
	Enrollment_CourseID  = tsq.NewColumn(tsqEnrollmentTable, "course_id", "course_id", func(r *Enrollment) *int64 { return &r.CourseID })
	Enrollment_CreatedAt = tsq.NewColumn(tsqEnrollmentTable, "created_at", "created_at", func(r *Enrollment) *tsqtime.Time { return &r.CreatedAt })
	Enrollment_DeletedAt = tsq.NewColumn(tsqEnrollmentTable, "deleted_at", "deleted_at", func(r *Enrollment) *int64 { return &r.DeletedAt })
	Enrollment_FeeCents  = tsq.NewColumn(tsqEnrollmentTable, "fee_cents", "fee_cents", func(r *Enrollment) *int64 { return &r.FeeCents })
	Enrollment_LearnerID = tsq.NewColumn(tsqEnrollmentTable, "learner_id", "learner_id", func(r *Enrollment) *int64 { return &r.LearnerID })
	Enrollment_Score     = tsq.NewColumn(tsqEnrollmentTable, "score", "score", func(r *Enrollment) *int64 { return &r.Score })
	Enrollment_Status    = tsq.NewColumn(tsqEnrollmentTable, "status", "status", func(r *Enrollment) *EnrollmentStatus { return &r.Status })
	Enrollment_UID       = tsq.NewColumn(tsqEnrollmentTable, "uid", "uid", func(r *Enrollment) *int64 { return &r.UID })
	Enrollment_UpdatedAt = tsq.NewColumn(tsqEnrollmentTable, "updated_at", "updated_at", func(r *Enrollment) *null.Time { return &r.UpdatedAt })
	Enrollment_Version   = tsq.NewColumn(tsqEnrollmentTable, "version", "version", func(r *Enrollment) *int64 { return &r.Version })
)

// TableEnrollment is the table descriptor of Enrollment. It depends on every column, so
// package initialization completes the table before any query uses it.
var TableEnrollment = tsqEnrollmentTable.Define(tsq.TableSpec[Enrollment]{
	Columns: []tsq.BoundColumn[Enrollment]{
		Enrollment_CourseID,
		Enrollment_CreatedAt,
		Enrollment_DeletedAt,
		Enrollment_FeeCents,
		Enrollment_LearnerID,
		Enrollment_Score,
		Enrollment_Status,
		Enrollment_UID,
		Enrollment_UpdatedAt,
		Enrollment_Version,
	},
	PrimaryKey:    Enrollment_UID,
	AutoIncrement: true,
	Version:       Enrollment_Version,
	CreatedAt:     Enrollment_CreatedAt,
	UpdatedAt:     Enrollment_UpdatedAt,
	DeletedAt:     Enrollment_DeletedAt,
	Schema: []tsqdialect.ColumnSpec{
		{
			Name: "uid",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
			PrimaryKey:    true,
			AutoIncrement: true,
		},
		{
			Name: "created_at",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindTime,
			},
			Default: "CURRENT_TIMESTAMP",
		},
		{
			Name: "updated_at",
			Type: tsqdialect.ColumnType{
				Kind:     tsqdialect.KindTime,
				Nullable: true,
			},
		},
		{
			Name: "deleted_at",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
			Default: "0",
		},
		{
			Name: "version",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
			Default: "1",
		},
		{
			Name: "course_id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "fee_cents",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "learner_id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "score",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
		},
		{
			Name: "status",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 32,
			},
		},
	},
	Indexes: []tsq.TableIndex{
		{Name: "idx_enrollment_course_id", Fields: []string{"deleted_at", "course_id"}},
		{Name: "idx_enrollment_learner_id_course_id", Fields: []string{"deleted_at", "learner_id", "course_id"}},
		{Name: "idx_enrollment_status", Fields: []string{"deleted_at", "status"}},
	},
})

// Enrollment__Cols lists every column of Enrollment, for Select.
var Enrollment__Cols = TableEnrollment.Columns()

// QueryEnrollmentByUID reads one Enrollment by primary key; bind Enrollment_UID.
var QueryEnrollmentByUID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_UID.EQ(Enrollment_UID.Param()),
	).
	MustBuild()

// QueryEnrollmentByUIDIn reads Enrollment rows by a list of primary keys; bind Enrollment_UID with BindList.
var QueryEnrollmentByUIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_UID.In(Enrollment_UID.ListParam()),
	).
	MustBuild()

// FetchEnrollmentByUID returns the Enrollment rows with the given primary keys,
// in the order given. It fails with an error wrapping sql.ErrNoRows when any of
// them is missing.
func FetchEnrollmentByUID(
	ctx context.Context,
	db tsq.Executor,
	uIDs ...int64,
) ([]*Enrollment, error) {
	list, err := QueryEnrollmentByUIDIn.List(ctx, db, Enrollment_UID.BindList(uIDs...))
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrder(uIDs, list, func(row *Enrollment) int64 {
		return row.UID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Enrollment by UID %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryEnrollmentByCourseID reads Enrollment rows by index idx_enrollment_course_id.
var QueryEnrollmentByCourseID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_CourseID.EQ(Enrollment_CourseID.Param()),
	).
	MustBuild()

// QueryEnrollmentByCourseIDIn reads Enrollment rows by index idx_enrollment_course_id.
var QueryEnrollmentByCourseIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_CourseID.In(Enrollment_CourseID.ListParam()),
	).
	MustBuild()

// QueryEnrollmentByLearnerID reads Enrollment rows by index idx_enrollment_learner_id_course_id.
var QueryEnrollmentByLearnerID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.EQ(Enrollment_LearnerID.Param()),
	).
	MustBuild()

// QueryEnrollmentByLearnerIDAndCourseID reads Enrollment rows by index idx_enrollment_learner_id_course_id.
var QueryEnrollmentByLearnerIDAndCourseID = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.EQ(Enrollment_LearnerID.Param()),
		Enrollment_CourseID.EQ(Enrollment_CourseID.Param()),
	).
	MustBuild()

// QueryEnrollmentByLearnerIDAndCourseIDIn reads Enrollment rows by index idx_enrollment_learner_id_course_id.
var QueryEnrollmentByLearnerIDAndCourseIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.EQ(Enrollment_LearnerID.Param()),
		Enrollment_CourseID.In(Enrollment_CourseID.ListParam()),
	).
	MustBuild()

// QueryEnrollmentByLearnerIDIn reads Enrollment rows by index idx_enrollment_learner_id_course_id.
var QueryEnrollmentByLearnerIDIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_LearnerID.In(Enrollment_LearnerID.ListParam()),
	).
	MustBuild()

// QueryEnrollmentByStatus reads Enrollment rows by index idx_enrollment_status.
var QueryEnrollmentByStatus = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_Status.EQ(Enrollment_Status.Param()),
	).
	MustBuild()

// QueryEnrollmentByStatusIn reads Enrollment rows by index idx_enrollment_status.
var QueryEnrollmentByStatusIn = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(
		Enrollment_DeletedAt.EQVal(0),
		Enrollment_Status.In(Enrollment_Status.ListParam()),
	).
	MustBuild()

// QueryEnrollment reads every Enrollment row that is not deleted; Page matches its search columns.
var QueryEnrollment = tsq.
	Select(Enrollment__Cols...).
	From(TableEnrollment).
	Where(Enrollment_DeletedAt.EQVal(0)).
	MustBuild()

// Insert inserts the row; see tsq.TableOf.Insert.
func (e *Enrollment) Insert(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.Insert(ctx, db, e)
}

// Update updates the row; see tsq.TableOf.Update.
func (e *Enrollment) Update(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.Update(ctx, db, e)
}

// Delete soft-deletes the row by stamping DeletedAt; it drops out of every
// generated query. See tsq.TableOf.Delete.
func (e *Enrollment) Delete(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.Delete(ctx, db, e)
}

// HardDelete removes the row from the table. Unlike a soft delete, it cannot be undone.
func (e *Enrollment) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableEnrollment.HardDelete(ctx, db, e)
}

// Active reports whether the row is not soft-deleted.
func (e *Enrollment) Active() bool {
	return e.DeletedAt == 0
}
