// Code generated by tsq-v4.1.10. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"errors"
	"fmt"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/tmoeish/tsq/v4"
)

// InstructorGeneratedQuery wraps a generated query and preserves any init-time build error.
type InstructorGeneratedQuery struct {
	query *tsq.Query[Instructor]
	err   error
}

func (g InstructorGeneratedQuery) resolved() (*tsq.Query[Instructor], error) {
	if g.err != nil {
		return nil, g.err
	}

	if g.query == nil {
		return nil, errors.New("generated query is not initialized")
	}

	return g.query, nil
}

// Load executes the generated query and scans one Instructor row into holder.
func (g InstructorGeneratedQuery) Load(ctx context.Context, db tsq.SQLExecutor, holder *Instructor, args ...any) error {
	query, err := g.resolved()
	if err != nil {
		return err
	}

	return query.Load(ctx, db, holder, args...)
}

// Exists reports whether the generated query matches at least one Instructor row.
func (g InstructorGeneratedQuery) Exists(ctx context.Context, db tsq.SQLExecutor, args ...any) (bool, error) {
	query, err := g.resolved()
	if err != nil {
		return false, err
	}

	return query.Exists(ctx, db, args...)
}

// Count returns the number of Instructor rows matched by the generated query.
func (g InstructorGeneratedQuery) Count(ctx context.Context, db tsq.SQLExecutor, args ...any) (int, error) {
	query, err := g.resolved()
	if err != nil {
		return 0, err
	}

	return query.Count(ctx, db, args...)
}

// List executes the generated query and returns all matching Instructor rows.
func (g InstructorGeneratedQuery) List(ctx context.Context, db tsq.SQLExecutor, args ...any) ([]*Instructor, error) {
	query, err := g.resolved()
	if err != nil {
		return nil, err
	}

	return tsq.List(ctx, db, query, args...)
}

// Page executes the generated query with paging and returns a paged Instructor result.
func (g InstructorGeneratedQuery) Page(ctx context.Context, db tsq.SQLExecutor, page *tsq.PageRequest, args ...any) (*tsq.PageResponse[Instructor], error) {
	query, err := g.resolved()
	if err != nil {
		return nil, err
	}

	return tsq.Page(ctx, db, page, query, args...)
}

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableInstructor implements the tsq.Table interface for Instructor.
var TableInstructor tsq.Table = Instructor{}

// TSQOwner marks Instructor as a TSQ owner.
func (i Instructor) TSQOwner() {}

// Table returns the database table name for Instructor.
func (i Instructor) Table() string { return "instructor" }

// Cols returns all generated columns for Instructor.
func (i Instructor) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(Instructor__Cols...)
}

// SearchColumns returns columns that support keyword search for Instructor.
func (i Instructor) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{
		Instructor_Name,
		Instructor_Specialty,
		Instructor_Bio,
	}
}

// PrimaryKeys returns the primary key columns for Instructor.
func (i Instructor) PrimaryKeys() []string {
	return []string{"id"}
}

// AutoIncrement reports whether Instructor uses an auto-increment primary key.
func (i Instructor) AutoIncrement() bool { return true }

// VersionColumn returns the optimistic-lock version column for Instructor, if any.
func (i Instructor) VersionColumn() string {
	return ""
}

// Column definitions for Instructor table.
var (
	Instructor_Bio       = tsq.NewCol("bio", "bio", func(t *Instructor) *string { return &t.Bio })
	Instructor_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *Instructor) *null.Time { return &t.CreatedAt })
	Instructor_Email     = tsq.NewCol("email", "email", func(t *Instructor) *string { return &t.Email })
	Instructor_ID        = tsq.NewCol("id", "id", func(t *Instructor) *int64 { return &t.ID })
	Instructor_Name      = tsq.NewCol("name", "name", func(t *Instructor) *string { return &t.Name })
	Instructor_Specialty = tsq.NewCol("specialty", "specialty", func(t *Instructor) *string { return &t.Specialty })
)

// Instructor__Cols is the list of all selectable columns for Instructor table.
var Instructor__Cols = []tsq.BoundColumn[Instructor]{
	Instructor_Bio,
	Instructor_CreatedAt,
	Instructor_Email,
	Instructor_ID,
	Instructor_Name,
	Instructor_Specialty,
}

// =============================================================================
// Query by Primary Key
// =============================================================================
// getInstructorByIDQuery stores the generated primary-key lookup query for Instructor.
var getInstructorByIDQuery InstructorGeneratedQuery

func init() {
	var err error
	getInstructorByIDQuery.query, err = tsq.
		Select(Instructor__Cols...).
		From(TableInstructor).
		Where(Instructor_ID.EQVar()).
		Build()
	if err != nil {
		getInstructorByIDQuery.err = fmt.Errorf("%s: %w", "initialize getInstructorByIDQuery", err)
	}
}

// GetInstructorByID retrieves a Instructor record by its primary key.
// Returns (nil, nil) if the record is not found.
func GetInstructorByID(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*Instructor, error) {
	row := &Instructor{}
	err := getInstructorByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return row, nil
}

// GetInstructorByIDOrErr retrieves a Instructor record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetInstructorByIDOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*Instructor, error) {
	row := &Instructor{}
	err := getInstructorByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		return nil, err
	}
	return row, nil
}

// ListInstructorByIDIn retrieves multiple Instructor records by a set of primary key values.
// Records not found are silently ignored.
func ListInstructorByIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*Instructor, error) {
	query, err := tsq.
		Select(Instructor__Cols...).
		From(TableInstructor).
		Where(Instructor_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "build query", err)
	}
	return tsq.List(ctx, db, query)
}

// ListInstructorByIDInOrErr retrieves multiple Instructor records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListInstructorByIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*Instructor, error) {
	query, err := tsq.
		Select(Instructor__Cols...).
		From(TableInstructor).
		Where(Instructor_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "build query", err)
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, err
	}

	ordered, missing := tsq.MatchByInputOrder(iDs, list, func(row *Instructor) int64 {
		return row.ID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("records not found: %v", missing)
	}
	return ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
// getInstructorByEmailQuery stores the generated unique-index lookup query for Instructor.
var getInstructorByEmailQuery InstructorGeneratedQuery

func init() {
	var err error
	getInstructorByEmailQuery.query, err = tsq.
		Select(Instructor__Cols...).
		From(TableInstructor).
		Search(TableInstructor.SearchColumns()...).
		Where(
			Instructor_Email.EQVar(),
		).
		Build()
	if err != nil {
		getInstructorByEmailQuery.err = fmt.Errorf("%s: %w", "initialize getInstructorByEmailQuery", err)
	}
}

// GetInstructorByEmail retrieves a Instructor record by unique index ux_instructor_email.
// Returns (nil, nil) if the record is not found.
func GetInstructorByEmail(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (*Instructor, error) {
	row := &Instructor{}
	err := getInstructorByEmailQuery.Load(
		ctx, db, row,
		email,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return row, nil
}

// GetInstructorByEmailOrErr retrieves a Instructor record by unique index ux_instructor_email.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetInstructorByEmailOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (*Instructor, error) {
	row := &Instructor{}
	err := getInstructorByEmailQuery.Load(
		ctx, db, row,
		email,
	)
	if err != nil {
		return nil, err
	}
	return row, nil
}

// ExistsInstructorByEmail checks if a Instructor record exists by unique index ux_instructor_email.
func ExistsInstructorByEmail(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (bool, error) {
	rs, err := getInstructorByEmailQuery.Exists(
		ctx, db,
		email,
	)
	return rs, err
}

// =============================================================================
// Query by Indexes
// =============================================================================

// =============================================================================
// List All Records
// =============================================================================
// listInstructorQuery stores the generated list-all query for Instructor.
var listInstructorQuery InstructorGeneratedQuery

func init() {
	var err error
	listInstructorQuery.query, err = tsq.
		Select(Instructor__Cols...).
		From(TableInstructor).
		Search(TableInstructor.SearchColumns()...).
		Build()
	if err != nil {
		listInstructorQuery.err = fmt.Errorf("%s: %w", "initialize listInstructorQuery", err)
	}
}

// CountInstructor returns the total count of Instructor records.
func CountInstructor(
	ctx context.Context,
	tx tsq.SQLExecutor,
) (int, error) {
	return listInstructorQuery.Count(ctx, tx)
}

// ListInstructor retrieves all Instructor records.
func ListInstructor(
	ctx context.Context,
	tx tsq.SQLExecutor,
) ([]*Instructor, error) {
	return listInstructorQuery.List(ctx, tx)
}

// PageInstructor retrieves Instructor records with pagination.
func PageInstructor(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageRequest,
) (*tsq.PageResponse[Instructor], error) {
	return listInstructorQuery.Page(ctx, tx, page)
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Instructor record.
func (i *Instructor) Insert(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	i.CreatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, i)
	if err != nil {
		return fmt.Errorf("insert Instructor: %s: %w", tsq.CompactJSON(i), err)
	}
	return nil
}

// Update updates an existing Instructor record.
func (i *Instructor) Update(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Update(ctx, db, i)
	if err != nil {
		return fmt.Errorf("update Instructor: %s: %w", tsq.CompactJSON(i), err)
	}
	return nil
}

// Delete permanently removes a Instructor record.
func (i *Instructor) Delete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Delete(ctx, db, i)
	if err != nil {
		return fmt.Errorf("delete Instructor: %s: %w", tsq.CompactJSON(i), err)
	}
	return nil
}

// =============================================================================
// Custom Query Helpers
// =============================================================================
// ListInstructorByQuery executes a custom query to retrieve a list of Instructor records.
func ListInstructorByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	qb *tsq.Query[Instructor],
	args ...any,
) ([]*Instructor, error) {
	return tsq.List(ctx, tx, qb, args...)
}

// PageInstructorByQuery executes a custom query to retrieve a page of Instructor records.
func PageInstructorByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageRequest,
	qb *tsq.Query[Instructor],
	args ...any,
) (*tsq.PageResponse[Instructor], error) {
	return tsq.Page(ctx, tx, page, qb, args...)
}
