// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"fmt"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
	null "gopkg.in/nullbio/null.v6"
)

// tsqInstructorTable is TableInstructor before its definition; columns are declared on it.
var tsqInstructorTable = tsq.NewTable[Instructor]("instructor")

// Columns of Instructor.
var (
	Instructor_Bio       = tsq.NewColumn(tsqInstructorTable, "bio", "bio", func(r *Instructor) *string { return &r.Bio })
	Instructor_CreatedAt = tsq.NewColumn(tsqInstructorTable, "created_at", "created_at", func(r *Instructor) *null.Time { return &r.CreatedAt })
	Instructor_Email     = tsq.NewColumn(tsqInstructorTable, "email", "email", func(r *Instructor) *string { return &r.Email })
	Instructor_ID        = tsq.NewColumn(tsqInstructorTable, "id", "id", func(r *Instructor) *int64 { return &r.ID })
	Instructor_Name      = tsq.NewColumn(tsqInstructorTable, "name", "name", func(r *Instructor) *string { return &r.Name })
	Instructor_Specialty = tsq.NewColumn(tsqInstructorTable, "specialty", "specialty", func(r *Instructor) *string { return &r.Specialty })
)

// TableInstructor is the table descriptor of Instructor. It depends on every column, so
// package initialization completes the table before any query uses it.
var TableInstructor = tsqInstructorTable.Define(tsq.TableSpec[Instructor]{
	Columns: []tsq.BoundColumn[Instructor]{
		Instructor_Bio,
		Instructor_CreatedAt,
		Instructor_Email,
		Instructor_ID,
		Instructor_Name,
		Instructor_Specialty,
	},
	PrimaryKey:    Instructor_ID,
	AutoIncrement: true,
	CreatedAt:     Instructor_CreatedAt,
	Search: []tsq.SearchColumn{
		Instructor_Name,
		Instructor_Specialty,
		Instructor_Bio,
	},
	Schema: []tsqdialect.ColumnSpec{
		{
			Name: "id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
			PrimaryKey:    true,
			AutoIncrement: true,
		},
		{
			Name: "created_at",
			Type: tsqdialect.ColumnType{
				Kind:     tsqdialect.KindTime,
				Nullable: true,
			},
		},
		{
			Name: "bio",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 2048,
			},
		},
		{
			Name: "email",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 160,
			},
		},
		{
			Name: "name",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 120,
			},
		},
		{
			Name: "specialty",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 160,
			},
		},
	},
	Indexes: []tsq.TableIndex{
		{Name: "ux_instructor_email", Unique: true, Fields: []string{"email"}},
	},
})

// Instructor__Cols lists every column of Instructor, for Select.
var Instructor__Cols = TableInstructor.Columns()

// QueryInstructorByID reads one Instructor by primary key; bind Instructor_ID.
var QueryInstructorByID = tsq.
	Select(Instructor__Cols...).
	From(TableInstructor).
	Where(
		Instructor_ID.EQ(Instructor_ID.Param()),
	).
	MustBuild()

// QueryInstructorByIDIn reads Instructor rows by a list of primary keys; bind Instructor_ID with BindList.
var QueryInstructorByIDIn = tsq.
	Select(Instructor__Cols...).
	From(TableInstructor).
	Where(
		Instructor_ID.In(Instructor_ID.ListParam()),
	).
	MustBuild()

// FetchInstructorByID returns the Instructor rows with the given primary keys,
// in the order given. It fails with an error wrapping sql.ErrNoRows when any of
// them is missing.
func FetchInstructorByID(
	ctx context.Context,
	db tsq.Executor,
	iDs ...int64,
) ([]*Instructor, error) {
	list, err := QueryInstructorByIDIn.List(ctx, db, Instructor_ID.BindList(iDs...))
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrder(iDs, list, func(row *Instructor) int64 {
		return row.ID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Instructor by ID %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryInstructorByEmail reads one Instructor by unique index ux_instructor_email.
var QueryInstructorByEmail = tsq.
	Select(Instructor__Cols...).
	From(TableInstructor).
	Where(
		Instructor_Email.EQ(Instructor_Email.Param()),
	).
	MustBuild()

// FetchInstructorByEmail returns the Instructor rows matching unique index ux_instructor_email,
// one per Email value, in the order given. It fails with an error wrapping
// sql.ErrNoRows when any of them is missing.
func FetchInstructorByEmail(
	ctx context.Context,
	db tsq.Executor,
	emails ...string,
) ([]*Instructor, error) {
	list, err := QueryInstructorByEmailIn.List(ctx, db,
		Instructor_Email.BindList(emails...),
	)
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrderKey(emails, list,
		func(row *Instructor) string { return lookupKey(row.Email) },
		func(input string) string { return lookupKey(input) },
	)
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Instructor by Email %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryInstructorByEmailIn reads Instructor rows by index ux_instructor_email.
var QueryInstructorByEmailIn = tsq.
	Select(Instructor__Cols...).
	From(TableInstructor).
	Where(
		Instructor_Email.In(Instructor_Email.ListParam()),
	).
	MustBuild()

// QueryInstructor reads every Instructor row; Page matches its search columns.
var QueryInstructor = tsq.
	Select(Instructor__Cols...).
	From(TableInstructor).
	Search(TableInstructor.SearchColumns()...).
	MustBuild()

// Insert inserts the row; see tsq.TableOf.Insert.
func (i *Instructor) Insert(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.Insert(ctx, db, i)
}

// Update updates the row; see tsq.TableOf.Update.
func (i *Instructor) Update(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.Update(ctx, db, i)
}

// Delete removes the row. Instructor has no deleted_at column, so Delete and
// HardDelete are the same.
func (i *Instructor) Delete(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.Delete(ctx, db, i)
}

// HardDelete removes the row from the table.
func (i *Instructor) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.HardDelete(ctx, db, i)
}
