// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// InstructorTable is the instructor table: the descriptor of Instructor rows, with one field
// per column.
type InstructorTable struct {
	*tsq.TableOf[Instructor, int64]

	Bio       tsq.Column[Instructor, string]
	CreatedAt tsq.NullColumn[Instructor, tsqtime.Time]
	Email     tsq.Column[Instructor, string]
	ID        tsq.Column[Instructor, int64]
	Name      tsq.Column[Instructor, string]
	Specialty tsq.Column[Instructor, string]
}

// TableInstructor is the instructor table.
var TableInstructor = newInstructorTable()

// newInstructorTable declares the table, its columns, then its definition, so that
// anything naming TableInstructor is initialized after the table is complete.
func newInstructorTable() InstructorTable {
	t := tsq.NewTable[Instructor, int64]("instructor")
	c := InstructorTable{
		TableOf:   t,
		Bio:       tsq.NewColumn(t, "bio", "bio", func(r *Instructor) *string { return &r.Bio }),
		CreatedAt: tsq.NewNullColumn[tsqtime.Time](t, "created_at", "created_at", func(r *Instructor) *null.Time { return &r.CreatedAt }),
		Email:     tsq.NewColumn(t, "email", "email", func(r *Instructor) *string { return &r.Email }),
		ID:        tsq.NewColumn(t, "id", "id", func(r *Instructor) *int64 { return &r.ID }),
		Name:      tsq.NewColumn(t, "name", "name", func(r *Instructor) *string { return &r.Name }),
		Specialty: tsq.NewColumn(t, "specialty", "specialty", func(r *Instructor) *string { return &r.Specialty }),
	}

	t.Define(tsq.TableSpec[Instructor, int64]{
		Columns: []tsq.BoundColumn[Instructor]{
			c.Bio,
			c.CreatedAt,
			c.Email,
			c.ID,
			c.Name,
			c.Specialty,
		},
		PrimaryKey:    c.ID,
		AutoIncrement: true,
		CreatedAt:     c.CreatedAt,
		Search: []tsq.SearchColumn{
			tsq.Searchable(c.Name),
			tsq.Searchable(c.Specialty),
			tsq.Searchable(c.Bio),
		},
		ColumnSpecs: []tsqdialect.ColumnSpec{
			{
				Name: "id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				PrimaryKey:    true,
				AutoIncrement: true,
			},
			{
				Name: "created_at",
				Type: tsqdialect.ColumnType{
					Kind:     tsqdialect.KindTime,
					Nullable: true,
				},
			},
			{
				Name: "bio",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 2048,
				},
			},
			{
				Name: "email",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 160,
				},
			},
			{
				Name: "name",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 120,
				},
			},
			{
				Name: "specialty",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 160,
				},
			},
		},
		Indexes: []tsq.TableIndex{
			{Name: "ux_instructor_email", Unique: true, Columns: []string{"email"}},
		},
	})

	return c
}

// As returns the table under alias, with every column bound to the alias, for
// joining the table more than once.
func (t InstructorTable) As(alias string) InstructorTable {
	a := t.TableOf.As(alias)

	return InstructorTable{
		TableOf:   a,
		Bio:       t.Bio.WithTable(a),
		CreatedAt: t.CreatedAt.WithTable(a).(tsq.NullColumn[Instructor, tsqtime.Time]),
		Email:     t.Email.WithTable(a),
		ID:        t.ID.WithTable(a),
		Name:      t.Name.WithTable(a),
		Specialty: t.Specialty.WithTable(a),
	}
}

// WithDeleted returns the table without its soft-delete scope; see
// tsq.TableOf.WithDeleted.
func (t InstructorTable) WithDeleted() InstructorTable {
	t.TableOf = t.TableOf.WithDeleted()

	return t
}

// GetByEmail reads the Instructor matching unique index ux_instructor_email, and fails with an
// error wrapping sql.ErrNoRows when there is none.
func (t InstructorTable) GetByEmail(
	ctx context.Context,
	db tsq.Executor,
	email string,
) (*Instructor, error) {
	return tsq.Select(t.Columns()...).From(t).Where(
		t.Email.EQ(tsq.Val(email)),
	).Get(ctx, db)
}

// FetchByEmail reads the Instructor rows matching unique index ux_instructor_email, one per
// Email value, in the order given; see tsq.TableOf.FetchBy.
func (t InstructorTable) FetchByEmail(
	ctx context.Context,
	db tsq.Executor,
	emails ...string,
) ([]*Instructor, error) {
	return t.FetchBy(ctx, db, t.Email, emails)
}

// Insert inserts the row; see tsq.TableOf.Insert.
func (i *Instructor) Insert(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.Insert(ctx, db, i)
}

// Update writes the row, or only cols when given; see tsq.TableOf.Update.
func (i *Instructor) Update(ctx context.Context, db tsq.Executor, cols ...tsq.BoundColumn[Instructor]) error {
	return TableInstructor.Update(ctx, db, i, cols...)
}

// Delete removes the row. Instructor has no deleted_at column, so Delete and
// HardDelete are the same.
func (i *Instructor) Delete(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.Delete(ctx, db, i)
}

// HardDelete removes the row from the table.
func (i *Instructor) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableInstructor.HardDelete(ctx, db, i)
}
