// Code generated by tsq-v4.1.1. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"errors"
	"fmt"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/tmoeish/tsq/v4"
)

// LearnerGeneratedQuery wraps a generated query and preserves any init-time build error.
type LearnerGeneratedQuery struct {
	query *tsq.Query[Learner]
	err   error
}

func (g LearnerGeneratedQuery) resolved() (*tsq.Query[Learner], error) {
	if g.err != nil {
		return nil, g.err
	}

	if g.query == nil {
		return nil, errors.New("generated query is not initialized")
	}

	return g.query, nil
}

// Load executes the generated query and scans one Learner row into holder.
func (g LearnerGeneratedQuery) Load(ctx context.Context, db tsq.SQLExecutor, holder *Learner, args ...any) error {
	query, err := g.resolved()
	if err != nil {
		return err
	}

	return query.Load(ctx, db, holder, args...)
}

// Exists reports whether the generated query matches at least one Learner row.
func (g LearnerGeneratedQuery) Exists(ctx context.Context, db tsq.SQLExecutor, args ...any) (bool, error) {
	query, err := g.resolved()
	if err != nil {
		return false, err
	}

	return query.Exists(ctx, db, args...)
}

// Count returns the number of Learner rows matched by the generated query.
func (g LearnerGeneratedQuery) Count(ctx context.Context, db tsq.SQLExecutor, args ...any) (int, error) {
	query, err := g.resolved()
	if err != nil {
		return 0, err
	}

	return query.Count(ctx, db, args...)
}

// List executes the generated query and returns all matching Learner rows.
func (g LearnerGeneratedQuery) List(ctx context.Context, db tsq.SQLExecutor, args ...any) ([]*Learner, error) {
	query, err := g.resolved()
	if err != nil {
		return nil, err
	}

	return tsq.List(ctx, db, query, args...)
}

// Page executes the generated query with paging and returns a paged Learner result.
func (g LearnerGeneratedQuery) Page(ctx context.Context, db tsq.SQLExecutor, page *tsq.PageRequest, args ...any) (*tsq.PageResponse[Learner], error) {
	query, err := g.resolved()
	if err != nil {
		return nil, err
	}

	return tsq.Page(ctx, db, page, query, args...)
}

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableLearner implements the tsq.Table interface for Learner.
var TableLearner tsq.Table = Learner{}

// TSQOwner marks Learner as a TSQ owner.
func (l Learner) TSQOwner() {}

// Table returns the database table name for Learner.
func (l Learner) Table() string { return "learner" }

// Cols returns all generated columns for Learner.
func (l Learner) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(Learner__Cols...)
}

// SearchColumns returns columns that support keyword search for Learner.
func (l Learner) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{
		Learner_Name,
		Learner_Email,
		Learner_Company,
	}
}

// PrimaryKeys returns the primary key columns for Learner.
func (l Learner) PrimaryKeys() []string {
	return []string{"id"}
}

// AutoIncrement reports whether Learner uses an auto-increment primary key.
func (l Learner) AutoIncrement() bool { return true }

// VersionColumn returns the optimistic-lock version column for Learner, if any.
func (l Learner) VersionColumn() string {
	return ""
}

// Column definitions for Learner table.
var (
	Learner_Company   = tsq.NewCol("company", "company", func(t *Learner) *string { return &t.Company })
	Learner_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *Learner) *null.Time { return &t.CreatedAt })
	Learner_Email     = tsq.NewCol("email", "email", func(t *Learner) *string { return &t.Email })
	Learner_ID        = tsq.NewCol("id", "id", func(t *Learner) *int64 { return &t.ID })
	Learner_Name      = tsq.NewCol("name", "name", func(t *Learner) *string { return &t.Name })
)

// Learner__Cols is the list of all selectable columns for Learner table.
var Learner__Cols = []tsq.BoundColumn[Learner]{
	Learner_Company,
	Learner_CreatedAt,
	Learner_Email,
	Learner_ID,
	Learner_Name,
}

// =============================================================================
// Table Registration and Index Initialization
// =============================================================================

func init() {
	tsq.RegisterTable(
		TableLearner,
		func(db *tsq.Engine) error {
			// Upsert unique indexes.
			if err := tsq.UpsertIndex(db, "learner", true, "ux_learner_email", []string{"email"}); err != nil {
				return fmt.Errorf("%s: %w", "upsert ux_learner_email@learner", err)
			}
			// Upsert non-unique indexes.
			if err := tsq.UpsertIndex(db, "learner", false, "idx_learner_company", []string{"company"}); err != nil {
				return fmt.Errorf("%s: %w", "upsert idx_learner_company@learner", err)
			}
			return nil
		},
	)
}

// =============================================================================
// Query by Primary Key
// =============================================================================
// getLearnerByIDQuery stores the generated primary-key lookup query for Learner.
var getLearnerByIDQuery LearnerGeneratedQuery

func init() {
	var err error
	getLearnerByIDQuery.query, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(Learner_ID.EQVar()).
		Build()
	if err != nil {
		getLearnerByIDQuery.err = fmt.Errorf("%s: %w", "initialize getLearnerByIDQuery", err)
	}
}

// GetLearnerByID retrieves a Learner record by its primary key.
// Returns (nil, nil) if the record is not found.
func GetLearnerByID(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return row, nil
}

// GetLearnerByIDOrErr retrieves a Learner record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetLearnerByIDOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		return nil, err
	}
	return row, nil
}

// ListLearnerByIDIn retrieves multiple Learner records by a set of primary key values.
// Records not found are silently ignored.
func ListLearnerByIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*Learner, error) {
	query, err := tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(Learner_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "build query", err)
	}
	return tsq.List(ctx, db, query)
}

// ListLearnerByIDInOrErr retrieves multiple Learner records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListLearnerByIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*Learner, error) {
	query, err := tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(Learner_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "build query", err)
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, err
	}

	ordered, missing := tsq.MatchByInputOrder(iDs, list, func(row *Learner) int64 {
		return row.ID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("records not found: %v", missing)
	}
	return ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
// getLearnerByEmailQuery stores the generated unique-index lookup query for Learner.
var getLearnerByEmailQuery LearnerGeneratedQuery

func init() {
	var err error
	getLearnerByEmailQuery.query, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Search(TableLearner.SearchColumns()...).
		Where(
			Learner_Email.EQVar(),
		).
		Build()
	if err != nil {
		getLearnerByEmailQuery.err = fmt.Errorf("%s: %w", "initialize getLearnerByEmailQuery", err)
	}
}

// GetLearnerByEmail retrieves a Learner record by unique index ux_learner_email.
// Returns (nil, nil) if the record is not found.
func GetLearnerByEmail(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByEmailQuery.Load(
		ctx, db, row,
		email,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return row, nil
}

// GetLearnerByEmailOrErr retrieves a Learner record by unique index ux_learner_email.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetLearnerByEmailOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByEmailQuery.Load(
		ctx, db, row,
		email,
	)
	if err != nil {
		return nil, err
	}
	return row, nil
}

// ExistsLearnerByEmail checks if a Learner record exists by unique index ux_learner_email.
func ExistsLearnerByEmail(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (bool, error) {
	rs, err := getLearnerByEmailQuery.Exists(
		ctx, db,
		email,
	)
	return rs, err
}

// =============================================================================
// Query by Indexes
// =============================================================================
// ListLearnerByCompanyQuery stores the generated index query for Learner.
var ListLearnerByCompanyQuery LearnerGeneratedQuery

func init() {
	var err error
	ListLearnerByCompanyQuery.query, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Search(TableLearner.SearchColumns()...).
		Where(
			Learner_Company.EQVar(),
		).
		Build()
	if err != nil {
		ListLearnerByCompanyQuery.err = fmt.Errorf("%s: %w", "initialize ListLearnerByCompanyQuery", err)
	}
}

// CountLearnerByCompany returns the count of Learner records matching index idx_learner_company.
func CountLearnerByCompany(
	ctx context.Context,
	db tsq.SQLExecutor,
	company string,
) (int, error) {
	rs, err := ListLearnerByCompanyQuery.Count(
		ctx, db,
		company,
	)
	if err != nil {
		return 0, fmt.Errorf("%s: %w", "query by index idx_learner_company", err)
	}
	return rs, nil
}

// ListLearnerByCompany retrieves Learner records by index idx_learner_company.
func ListLearnerByCompany(
	ctx context.Context,
	db tsq.SQLExecutor,
	company string,
) ([]*Learner, error) {
	data, err := ListLearnerByCompanyQuery.List(
		ctx, db,
		company,
	)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "query by index idx_learner_company", err)
	}
	return data, nil
}

// PageLearnerByCompany retrieves Learner records by index idx_learner_company with pagination.
func PageLearnerByCompany(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageRequest,
	company string,
) (*tsq.PageResponse[Learner], error) {
	rs, err := ListLearnerByCompanyQuery.Page(
		ctx, db, page,
		company,
	)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "query by index idx_learner_company", err)
	}
	return rs, nil
}

// ListLearnerByCompanyInQuery stores the generated index query for Learner.
var ListLearnerByCompanyInQuery LearnerGeneratedQuery

func init() {
	var err error
	ListLearnerByCompanyInQuery.query, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(
			Learner_Company.InVar(),
		).
		Build()
	if err != nil {
		ListLearnerByCompanyInQuery.err = fmt.Errorf("%s: %w", "initialize ListLearnerByCompanyInQuery", err)
	}
}

// ListLearnerByCompanyIn retrieves multiple Learner records by index idx_learner_company using an IN clause.
func ListLearnerByCompanyIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	companys ...string,
) ([]*Learner, error) {
	list, err := ListLearnerByCompanyInQuery.List(
		ctx, db,
		companys,
	)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", "query by index idx_learner_company", err)
	}
	return list, nil
}

// =============================================================================
// List All Records
// =============================================================================
// listLearnerQuery stores the generated list-all query for Learner.
var listLearnerQuery LearnerGeneratedQuery

func init() {
	var err error
	listLearnerQuery.query, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Search(TableLearner.SearchColumns()...).
		Build()
	if err != nil {
		listLearnerQuery.err = fmt.Errorf("%s: %w", "initialize listLearnerQuery", err)
	}
}

// CountLearner returns the total count of Learner records.
func CountLearner(
	ctx context.Context,
	tx tsq.SQLExecutor,
) (int, error) {
	return listLearnerQuery.Count(ctx, tx)
}

// ListLearner retrieves all Learner records.
func ListLearner(
	ctx context.Context,
	tx tsq.SQLExecutor,
) ([]*Learner, error) {
	return listLearnerQuery.List(ctx, tx)
}

// PageLearner retrieves Learner records with pagination.
func PageLearner(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageRequest,
) (*tsq.PageResponse[Learner], error) {
	return listLearnerQuery.Page(ctx, tx, page)
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Learner record.
func (l *Learner) Insert(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	l.CreatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, l)
	if err != nil {
		return fmt.Errorf("insert Learner: %s: %w", tsq.CompactJSON(l), err)
	}
	return nil
}

// Update updates an existing Learner record.
func (l *Learner) Update(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Update(ctx, db, l)
	if err != nil {
		return fmt.Errorf("update Learner: %s: %w", tsq.CompactJSON(l), err)
	}
	return nil
}

// Delete permanently removes a Learner record.
func (l *Learner) Delete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Delete(ctx, db, l)
	if err != nil {
		return fmt.Errorf("delete Learner: %s: %w", tsq.CompactJSON(l), err)
	}
	return nil
}

// =============================================================================
// Custom Query Helpers
// =============================================================================
// ListLearnerByQuery executes a custom query to retrieve a list of Learner records.
func ListLearnerByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	qb *tsq.Query[Learner],
	args ...any,
) ([]*Learner, error) {
	return tsq.List(ctx, tx, qb, args...)
}

// PageLearnerByQuery executes a custom query to retrieve a page of Learner records.
func PageLearnerByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageRequest,
	qb *tsq.Query[Learner],
	args ...any,
) (*tsq.PageResponse[Learner], error) {
	return tsq.Page(ctx, tx, page, qb, args...)
}
