// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	"fmt"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
	null "gopkg.in/nullbio/null.v6"
)

// tsqLearnerTable is TableLearner before its definition; columns are declared on it.
var tsqLearnerTable = tsq.NewTable[Learner]("learner")

// Columns of Learner.
var (
	Learner_Company   = tsq.NewColumn(tsqLearnerTable, "company", "company", func(r *Learner) *string { return &r.Company })
	Learner_CreatedAt = tsq.NewColumn(tsqLearnerTable, "created_at", "created_at", func(r *Learner) *null.Time { return &r.CreatedAt })
	Learner_Email     = tsq.NewColumn(tsqLearnerTable, "email", "email", func(r *Learner) *string { return &r.Email })
	Learner_ID        = tsq.NewColumn(tsqLearnerTable, "id", "id", func(r *Learner) *int64 { return &r.ID })
	Learner_Name      = tsq.NewColumn(tsqLearnerTable, "name", "name", func(r *Learner) *string { return &r.Name })
)

// TableLearner is the table descriptor of Learner. It depends on every column, so
// package initialization completes the table before any query uses it.
var TableLearner = tsqLearnerTable.Define(tsq.TableSpec[Learner]{
	Columns: []tsq.BoundColumn[Learner]{
		Learner_Company,
		Learner_CreatedAt,
		Learner_Email,
		Learner_ID,
		Learner_Name,
	},
	PrimaryKey:    Learner_ID,
	AutoIncrement: true,
	CreatedAt:     Learner_CreatedAt,
	Search: []tsq.SearchColumn{
		Learner_Name,
		Learner_Email,
		Learner_Company,
	},
	Schema: []tsqdialect.ColumnSpec{
		{
			Name: "id",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindInt,
				Bits: 64,
			},
			PrimaryKey:    true,
			AutoIncrement: true,
		},
		{
			Name: "created_at",
			Type: tsqdialect.ColumnType{
				Kind:     tsqdialect.KindTime,
				Nullable: true,
			},
		},
		{
			Name: "company",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 160,
			},
		},
		{
			Name: "email",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 160,
			},
		},
		{
			Name: "name",
			Type: tsqdialect.ColumnType{
				Kind: tsqdialect.KindString,
				Size: 120,
			},
		},
	},
	Indexes: []tsq.TableIndex{
		{Name: "ux_learner_email", Unique: true, Fields: []string{"email"}},
		{Name: "idx_learner_company", Fields: []string{"company"}},
	},
})

// Learner__Cols lists every column of Learner, for Select.
var Learner__Cols = TableLearner.Columns()

// QueryLearnerByID reads one Learner by primary key; bind Learner_ID.
var QueryLearnerByID = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Where(
		Learner_ID.EQ(Learner_ID.Param()),
	).
	MustBuild()

// QueryLearnerByIDIn reads Learner rows by a list of primary keys; bind Learner_ID with BindList.
var QueryLearnerByIDIn = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Where(
		Learner_ID.In(Learner_ID.ListParam()),
	).
	MustBuild()

// FetchLearnerByID returns the Learner rows with the given primary keys,
// in the order given. It fails with an error wrapping sql.ErrNoRows when any of
// them is missing.
func FetchLearnerByID(
	ctx context.Context,
	db tsq.Executor,
	iDs ...int64,
) ([]*Learner, error) {
	list, err := QueryLearnerByIDIn.List(ctx, db, Learner_ID.BindList(iDs...))
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrder(iDs, list, func(row *Learner) int64 {
		return row.ID
	})
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Learner by ID %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryLearnerByEmail reads one Learner by unique index ux_learner_email.
var QueryLearnerByEmail = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Where(
		Learner_Email.EQ(Learner_Email.Param()),
	).
	MustBuild()

// FetchLearnerByEmail returns the Learner rows matching unique index ux_learner_email,
// one per Email value, in the order given. It fails with an error wrapping
// sql.ErrNoRows when any of them is missing.
func FetchLearnerByEmail(
	ctx context.Context,
	db tsq.Executor,
	emails ...string,
) ([]*Learner, error) {
	list, err := QueryLearnerByEmailIn.List(ctx, db,
		Learner_Email.BindList(emails...),
	)
	if err != nil {
		return nil, err
	}

	ordered, missing := matchByInputOrderKey(emails, list,
		func(row *Learner) string { return lookupKey(row.Email) },
		func(input string) string { return lookupKey(input) },
	)
	if len(missing) > 0 {
		return nil, fmt.Errorf("fetch Learner by Email %v: %w", missing, tsqsql.ErrNoRows)
	}

	return ordered, nil
}

// QueryLearnerByCompany reads Learner rows by index idx_learner_company.
var QueryLearnerByCompany = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Where(
		Learner_Company.EQ(Learner_Company.Param()),
	).
	MustBuild()

// QueryLearnerByCompanyIn reads Learner rows by index idx_learner_company.
var QueryLearnerByCompanyIn = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Where(
		Learner_Company.In(Learner_Company.ListParam()),
	).
	MustBuild()

// QueryLearnerByEmailIn reads Learner rows by index ux_learner_email.
var QueryLearnerByEmailIn = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Where(
		Learner_Email.In(Learner_Email.ListParam()),
	).
	MustBuild()

// QueryLearner reads every Learner row; Page matches its search columns.
var QueryLearner = tsq.
	Select(Learner__Cols...).
	From(TableLearner).
	Search(TableLearner.SearchColumns()...).
	MustBuild()

// Insert inserts the row; see tsq.TableOf.Insert.
func (l *Learner) Insert(ctx context.Context, db tsq.Executor) error {
	return TableLearner.Insert(ctx, db, l)
}

// Update updates the row; see tsq.TableOf.Update.
func (l *Learner) Update(ctx context.Context, db tsq.Executor) error {
	return TableLearner.Update(ctx, db, l)
}

// Delete removes the row. Learner has no deleted_at column, so Delete and
// HardDelete are the same.
func (l *Learner) Delete(ctx context.Context, db tsq.Executor) error {
	return TableLearner.Delete(ctx, db, l)
}

// HardDelete removes the row from the table.
func (l *Learner) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableLearner.HardDelete(ctx, db, l)
}
