// Code generated by tsq-v3.7.1. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableLearner implements the tsq.Table interface for Learner.
var TableLearner tsq.Table = Learner{}

// TSQOwner marks Learner as a TSQ owner.
func (l Learner) TSQOwner() {}

// Table returns the database table name for Learner.
func (l Learner) Table() string { return "learner" }

// Cols returns all generated columns for Learner.
func (l Learner) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(Learner__Cols...)
}

// SearchColumns returns columns that support keyword search for Learner.
func (l Learner) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{
		Learner_Name,
		Learner_Email,
		Learner_Company,
	}
}

// PrimaryKeys returns the primary key columns for Learner.
func (l Learner) PrimaryKeys() []string {
	return []string{"id"}
}

// AutoIncrement reports whether Learner uses an auto-increment primary key.
func (l Learner) AutoIncrement() bool { return true }

// VersionColumn returns the optimistic-lock version column for Learner, if any.
func (l Learner) VersionColumn() string {
	return ""
}

// Column definitions for Learner table.
var (
	Learner_Company   = tsq.NewCol("company", "company", func(t *Learner) *string { return &t.Company })
	Learner_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *Learner) *null.Time { return &t.CreatedAt })
	Learner_Email     = tsq.NewCol("email", "email", func(t *Learner) *string { return &t.Email })
	Learner_ID        = tsq.NewCol("id", "id", func(t *Learner) *int64 { return &t.ID })
	Learner_Name      = tsq.NewCol("name", "name", func(t *Learner) *string { return &t.Name })
)

// Learner__Cols is the list of all selectable columns for Learner table.
var Learner__Cols = []tsq.BoundColumn[Learner]{
	Learner_Company,
	Learner_CreatedAt,
	Learner_Email,
	Learner_ID,
	Learner_Name,
}

// =============================================================================
// Table Registration and Index Initialization
// =============================================================================

func init() {
	tsq.RegisterTable(
		TableLearner,
		func(db *tsq.Engine) error {
			// Upsert unique indexes.
			if err := tsq.UpsertIndex(db, "learner", true, "ux_learner_email", []string{"email"}); err != nil {
				return errors.Annotate(err, "upsert ux_learner_email@learner")
			}
			// Upsert non-unique indexes.
			if err := tsq.UpsertIndex(db, "learner", false, "idx_learner_company", []string{"company"}); err != nil {
				return errors.Annotate(err, "upsert idx_learner_company@learner")
			}
			return nil
		},
	)
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getLearnerByIDQuery *tsq.Query[Learner]

func init() {
	var err error
	getLearnerByIDQuery, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(Learner_ID.EQVar()).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getLearnerByIDQuery"))
	}
}

// GetLearnerByID retrieves a Learner record by its primary key.
// Returns (nil, nil) if the record is not found.
func GetLearnerByID(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetLearnerByIDOrErr retrieves a Learner record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetLearnerByIDOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ListLearnerByIDIn retrieves multiple Learner records by a set of primary key values.
// Records not found are silently ignored.
func ListLearnerByIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*Learner, error) {
	query, err := tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(Learner_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}
	return tsq.List(ctx, db, query)
}

// ListLearnerByIDInOrErr retrieves multiple Learner records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListLearnerByIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*Learner, error) {
	query, err := tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(Learner_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(iDs, list, func(row *Learner) int64 {
		return row.ID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Learner(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
var getLearnerByEmailQuery *tsq.Query[Learner]

func init() {
	var err error
	getLearnerByEmailQuery, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Search(TableLearner.SearchColumns()...).
		Where(
			Learner_Email.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getLearnerByEmailQuery"))
	}
}

// GetLearnerByEmail retrieves a Learner record by unique index ux_learner_email.
// Returns (nil, nil) if the record is not found.
func GetLearnerByEmail(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByEmailQuery.Load(
		ctx, db, row,
		email,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetLearnerByEmailOrErr retrieves a Learner record by unique index ux_learner_email.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetLearnerByEmailOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (*Learner, error) {
	row := &Learner{}
	err := getLearnerByEmailQuery.Load(
		ctx, db, row,
		email,
	)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ExistsLearnerByEmail checks if a Learner record exists by unique index ux_learner_email.
func ExistsLearnerByEmail(
	ctx context.Context,
	db tsq.SQLExecutor,
	email string,
) (bool, error) {
	rs, err := getLearnerByEmailQuery.Exists(
		ctx, db,
		email,
	)
	return rs, errors.Trace(err)
}

// =============================================================================
// Query by Indexes
// =============================================================================
var ListLearnerByCompanyQuery *tsq.Query[Learner]

func init() {
	var err error
	ListLearnerByCompanyQuery, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Search(TableLearner.SearchColumns()...).
		Where(
			Learner_Company.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListLearnerByCompanyQuery"))
	}
}

// CountLearnerByCompany returns the count of Learner records matching index idx_learner_company.
func CountLearnerByCompany(
	ctx context.Context,
	db tsq.SQLExecutor,
	company string,
) (int, error) {
	rs, err := ListLearnerByCompanyQuery.Count(
		ctx, db,
		company,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_learner_company")
	}
	return rs, nil
}

// ListLearnerByCompany retrieves Learner records by index idx_learner_company.
func ListLearnerByCompany(
	ctx context.Context,
	db tsq.SQLExecutor,
	company string,
) ([]*Learner, error) {
	data, err := tsq.List(
		ctx, db, ListLearnerByCompanyQuery,
		company,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_learner_company")
	}
	return data, nil
}

// PageLearnerByCompany retrieves Learner records by index idx_learner_company with pagination.
func PageLearnerByCompany(
	ctx context.Context,
	db tsq.SQLExecutor,
	page *tsq.PageReq,
	company string,
) (*tsq.PageResp[Learner], error) {
	rs, err := tsq.Page(
		ctx, db, page, ListLearnerByCompanyQuery,
		company,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_learner_company")
	}
	return rs, nil
}

var ListLearnerByCompanyInQuery *tsq.Query[Learner]

func init() {
	var err error
	ListLearnerByCompanyInQuery, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Where(
			Learner_Company.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListLearnerByCompanyInQuery"))
	}
}

// ListLearnerByCompanyIn retrieves multiple Learner records by index idx_learner_company using an IN clause.
func ListLearnerByCompanyIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	companys ...string,
) ([]*Learner, error) {
	list, err := tsq.List(
		ctx, db, ListLearnerByCompanyInQuery,
		companys,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_learner_company")
	}
	return list, nil
}

// =============================================================================
// List All Records
// =============================================================================
var listLearnerQuery *tsq.Query[Learner]

func init() {
	var err error
	listLearnerQuery, err = tsq.
		Select(Learner__Cols...).
		From(TableLearner).
		Search(TableLearner.SearchColumns()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listLearnerQuery"))
	}
}

// CountLearner returns the total count of Learner records.
func CountLearner(
	ctx context.Context,
	tx tsq.SQLExecutor,
) (int, error) {
	return listLearnerQuery.Count(ctx, tx)
}

// ListLearner retrieves all Learner records.
func ListLearner(
	ctx context.Context,
	tx tsq.SQLExecutor,
) ([]*Learner, error) {
	return tsq.List(ctx, tx, listLearnerQuery)
}

// PageLearner retrieves Learner records with pagination.
func PageLearner(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Learner], error) {
	return tsq.Page(ctx, tx, page, listLearnerQuery)
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Learner record.
func (l *Learner) Insert(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	l.CreatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, l)
	if err != nil {
		return errors.Annotatef(err, "insert Learner: %s", tsq.CompactJSON(l))
	}
	return nil
}

// Update updates an existing Learner record.
func (l *Learner) Update(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Update(ctx, db, l)
	if err != nil {
		return errors.Annotatef(err, "update Learner: %s", tsq.CompactJSON(l))
	}
	return nil
}

// Delete permanently removes a Learner record.
func (l *Learner) Delete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Delete(ctx, db, l)
	if err != nil {
		return errors.Annotatef(err, "delete Learner: %s", tsq.CompactJSON(l))
	}
	return nil
}

// =============================================================================
// Custom Query Helpers
// =============================================================================
// ListLearnerByQuery executes a custom query to retrieve a list of Learner records.
func ListLearnerByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	qb *tsq.Query[Learner],
	args ...any,
) ([]*Learner, error) {
	return tsq.List(ctx, tx, qb, args...)
}

// PageLearnerByQuery executes a custom query to retrieve a page of Learner records.
func PageLearnerByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
	qb *tsq.Query[Learner],
	args ...any,
) (*tsq.PageResp[Learner], error) {
	return tsq.Page(ctx, tx, page, qb, args...)
}
