// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// LearnerTable is the learner table: the descriptor of Learner rows, with one field
// per column.
type LearnerTable struct {
	*tsq.TableOf[Learner, int64]

	Company   tsq.Column[Learner, string]
	CreatedAt tsq.NullColumn[Learner, tsqtime.Time]
	Email     tsq.Column[Learner, string]
	ID        tsq.Column[Learner, int64]
	Name      tsq.Column[Learner, string]
}

// TableLearner is the learner table.
var TableLearner = newLearnerTable()

// newLearnerTable declares the table, its columns, then its definition, so that
// anything naming TableLearner is initialized after the table is complete.
func newLearnerTable() LearnerTable {
	t := tsq.NewTable[Learner, int64]("learner")
	c := LearnerTable{
		TableOf:   t,
		Company:   tsq.NewColumn(t, "company", "company", func(r *Learner) *string { return &r.Company }),
		CreatedAt: tsq.NewNullColumn[tsqtime.Time](t, "created_at", "created_at", func(r *Learner) *tsqsql.Null[tsqtime.Time] { return &r.CreatedAt }),
		Email:     tsq.NewColumn(t, "email", "email", func(r *Learner) *string { return &r.Email }),
		ID:        tsq.NewColumn(t, "id", "id", func(r *Learner) *int64 { return &r.ID }),
		Name:      tsq.NewColumn(t, "name", "name", func(r *Learner) *string { return &r.Name }),
	}

	t.Define(tsq.TableSpec[Learner, int64]{
		Columns: []tsq.BoundColumn[Learner]{
			c.Company,
			c.CreatedAt,
			c.Email,
			c.ID,
			c.Name,
		},
		PrimaryKey:    c.ID,
		AutoIncrement: true,
		CreatedAt:     c.CreatedAt,
		Search: []tsq.SearchColumn{
			tsq.Searchable(c.Name),
			tsq.Searchable(c.Email),
			tsq.Searchable(c.Company),
		},
		ColumnSpecs: []tsqdialect.ColumnSpec{
			{
				Name: "id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				PrimaryKey:    true,
				AutoIncrement: true,
			},
			{
				Name: "created_at",
				Type: tsqdialect.ColumnType{
					Kind:     tsqdialect.KindTime,
					Nullable: true,
				},
			},
			{
				Name: "company",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 160,
				},
			},
			{
				Name: "email",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 160,
				},
			},
			{
				Name: "name",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 120,
				},
			},
		},
		Indexes: []tsq.TableIndex{
			{Name: "ux_learner_email", Unique: true, Columns: []string{"email"}},
			{Name: "idx_learner_company", Columns: []string{"company"}},
		},
	})

	return c
}

// As returns the table under alias, with every column bound to the alias, for
// joining the table more than once.
func (t LearnerTable) As(alias string) LearnerTable {
	a := t.TableOf.As(alias)

	return LearnerTable{
		TableOf:   a,
		Company:   t.Company.WithTable(a),
		CreatedAt: t.CreatedAt.WithTable(a).(tsq.NullColumn[Learner, tsqtime.Time]),
		Email:     t.Email.WithTable(a),
		ID:        t.ID.WithTable(a),
		Name:      t.Name.WithTable(a),
	}
}

// WithDeleted returns the table without its soft-delete scope; see
// tsq.TableOf.WithDeleted.
func (t LearnerTable) WithDeleted() LearnerTable {
	t.TableOf = t.TableOf.WithDeleted()

	return t
}

// GetByEmail reads the Learner matching unique index ux_learner_email, and fails with an
// error wrapping sql.ErrNoRows when there is none.
func (t LearnerTable) GetByEmail(
	ctx context.Context,
	db tsq.Executor,
	email string,
) (*Learner, error) {
	return t.GetBy(ctx, db, t.Email, email)
}

// FetchByEmail reads the Learner rows matching unique index ux_learner_email, one per
// Email value, in the order given; see tsq.TableOf.FetchBy.
func (t LearnerTable) FetchByEmail(
	ctx context.Context,
	db tsq.Executor,
	emails ...string,
) ([]*Learner, error) {
	return t.FetchBy(ctx, db, t.Email, emails)
}

// Insert inserts the row; see tsq.TableOf.Insert.
func (l *Learner) Insert(ctx context.Context, db tsq.Executor) error {
	return TableLearner.Insert(ctx, db, l)
}

// Update writes the row, or only cols when given; see tsq.TableOf.Update.
func (l *Learner) Update(ctx context.Context, db tsq.Executor, cols ...tsq.BoundColumn[Learner]) error {
	return TableLearner.Update(ctx, db, l, cols...)
}

// Delete removes the row. Learner has no deleted_at column, so Delete and
// HardDelete are the same.
func (l *Learner) Delete(ctx context.Context, db tsq.Executor) error {
	return TableLearner.Delete(ctx, db, l)
}

// HardDelete removes the row from the table.
func (l *Learner) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableLearner.HardDelete(ctx, db, l)
}
