-- Code generated by tsq-v4.1.17. DO NOT EDIT.

-- Dialect: mysql

-- Table: course

CREATE TABLE IF NOT EXISTS `course` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME,
    `instructor_id` BIGINT NOT NULL,
    `level` BIGINT NOT NULL,
    `list_price_cents` BIGINT NOT NULL,
    `prerequisite_id` BIGINT NOT NULL,
    `published` BOOLEAN NOT NULL,
    `summary` VARCHAR(4096) NOT NULL,
    `title` VARCHAR(160) NOT NULL,
    `track_id` BIGINT NOT NULL
);

ALTER TABLE `course` ADD INDEX `idx_course_instructor_id`(`instructor_id`);

ALTER TABLE `course` ADD INDEX `idx_course_prerequisite_id`(`prerequisite_id`);

ALTER TABLE `course` ADD INDEX `idx_course_track_id`(`track_id`);

ALTER TABLE `course` ADD UNIQUE INDEX `ux_course_title`(`title`);


-- Table: enrollment

CREATE TABLE IF NOT EXISTS `enrollment` (
    `uid` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `version` BIGINT NOT NULL DEFAULT 1,
    `course_id` BIGINT NOT NULL,
    `fee_cents` BIGINT NOT NULL,
    `learner_id` BIGINT NOT NULL,
    `score` BIGINT NOT NULL,
    `status` BIGINT NOT NULL
);

ALTER TABLE `enrollment` ADD INDEX `idx_enrollment_course_id`(`course_id`);

ALTER TABLE `enrollment` ADD INDEX `idx_enrollment_learner_id_course_id`(`learner_id`, `course_id`);

ALTER TABLE `enrollment` ADD INDEX `idx_enrollment_status`(`status`);


-- Table: instructor

CREATE TABLE IF NOT EXISTS `instructor` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME,
    `bio` VARCHAR(2048) NOT NULL,
    `email` VARCHAR(160) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `specialty` VARCHAR(160) NOT NULL
);

ALTER TABLE `instructor` ADD UNIQUE INDEX `ux_instructor_email`(`email`);


-- Table: learner

CREATE TABLE IF NOT EXISTS `learner` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME,
    `company` VARCHAR(160) NOT NULL,
    `email` VARCHAR(160) NOT NULL,
    `name` VARCHAR(120) NOT NULL
);

ALTER TABLE `learner` ADD INDEX `idx_learner_company`(`company`);

ALTER TABLE `learner` ADD UNIQUE INDEX `ux_learner_email`(`email`);


-- Table: track

CREATE TABLE IF NOT EXISTS `track` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME,
    `description` VARCHAR(1024) NOT NULL,
    `name` VARCHAR(120) NOT NULL
);

ALTER TABLE `track` ADD UNIQUE INDEX `ux_track_name`(`name`);
