-- Code generated by tsq-v4.1.2. DO NOT EDIT.

-- Dialect: postgres

-- Table: course

CREATE TABLE IF NOT EXISTS "course" (
    "id" BIGSERIAL PRIMARY KEY,
    "created_at" TIMESTAMP,
    "instructor_id" BIGINT NOT NULL,
    "level" BIGINT NOT NULL,
    "list_price_cents" BIGINT NOT NULL,
    "prerequisite_id" BIGINT NOT NULL,
    "published" BOOLEAN NOT NULL,
    "summary" VARCHAR(4096) NOT NULL,
    "title" VARCHAR(160) NOT NULL,
    "track_id" BIGINT NOT NULL
);

CREATE INDEX "idx_course_instructor_id" ON "course"("instructor_id")

CREATE INDEX "idx_course_prerequisite_id" ON "course"("prerequisite_id")

CREATE INDEX "idx_course_track_id" ON "course"("track_id")

CREATE UNIQUE INDEX "ux_course_title" ON "course"("title")


-- Table: enrollment

CREATE TABLE IF NOT EXISTS "enrollment" (
    "uid" BIGSERIAL PRIMARY KEY,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" BIGINT NOT NULL DEFAULT 0,
    "version" BIGINT NOT NULL DEFAULT 1,
    "course_id" BIGINT NOT NULL,
    "fee_cents" BIGINT NOT NULL,
    "learner_id" BIGINT NOT NULL,
    "score" BIGINT NOT NULL,
    "status" BIGINT NOT NULL
);

CREATE INDEX "idx_enrollment_course_id" ON "enrollment"("course_id")

CREATE INDEX "idx_enrollment_learner_id_course_id" ON "enrollment"("learner_id", "course_id")

CREATE INDEX "idx_enrollment_status" ON "enrollment"("status")


-- Table: instructor

CREATE TABLE IF NOT EXISTS "instructor" (
    "id" BIGSERIAL PRIMARY KEY,
    "created_at" TIMESTAMP,
    "bio" VARCHAR(2048) NOT NULL,
    "email" VARCHAR(160) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "specialty" VARCHAR(160) NOT NULL
);

CREATE UNIQUE INDEX "ux_instructor_email" ON "instructor"("email")


-- Table: learner

CREATE TABLE IF NOT EXISTS "learner" (
    "id" BIGSERIAL PRIMARY KEY,
    "created_at" TIMESTAMP,
    "company" VARCHAR(160) NOT NULL,
    "email" VARCHAR(160) NOT NULL,
    "name" VARCHAR(120) NOT NULL
);

CREATE INDEX "idx_learner_company" ON "learner"("company")

CREATE UNIQUE INDEX "ux_learner_email" ON "learner"("email")


-- Table: track

CREATE TABLE IF NOT EXISTS "track" (
    "id" BIGSERIAL PRIMARY KEY,
    "created_at" TIMESTAMP,
    "description" VARCHAR(1024) NOT NULL,
    "name" VARCHAR(120) NOT NULL
);

CREATE UNIQUE INDEX "ux_track_name" ON "track"("name")
