// Code generated by tsq-v4.1.14. DO NOT EDIT.

package academy

import (
	"encoding/json"

	"github.com/tmoeish/tsq/v4"
)

// TSQTables returns all generated table registrations for this package.
func TSQTables() []tsq.TableRegistration {
	return []tsq.TableRegistration{
		{
			Table: TableCourse,
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_course_title", Unique: true, Fields: []string{"title"}},
				// Declared non-unique indexes.
				{Name: "idx_course_instructor_id", Fields: []string{"instructor_id"}},
				{Name: "idx_course_prerequisite_id", Fields: []string{"prerequisite_id"}},
				{Name: "idx_course_track_id", Fields: []string{"track_id"}},
			},
		},
		{
			Table: TableEnrollment,
			Indexes: []tsq.TableIndex{
				// Declared non-unique indexes.
				{Name: "idx_enrollment_course_id", Fields: []string{"deleted_at", "course_id"}},
				{Name: "idx_enrollment_learner_id_course_id", Fields: []string{"deleted_at", "learner_id", "course_id"}},
				{Name: "idx_enrollment_status", Fields: []string{"deleted_at", "status"}},
			},
		},
		{
			Table: TableInstructor,
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_instructor_email", Unique: true, Fields: []string{"email"}},
			},
		},
		{
			Table: TableLearner,
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_learner_email", Unique: true, Fields: []string{"email"}},
				// Declared non-unique indexes.
				{Name: "idx_learner_company", Fields: []string{"company"}},
			},
		},
		{
			Table: TableTrack,
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_track_name", Unique: true, Fields: []string{"name"}},
			},
		},
	}
}

//// Helper functions

// compactJSON marshals a value to JSON and returns it as a string, or an empty string if marshaling fails.
func compactJSON(v any) string {
	bs, err := json.Marshal(v)
	if err != nil {
		return ""
	}

	return string(bs)
}

// matchByInputOrder reorders rows to match inputs and reports which keys were missing.
func matchByInputOrder[T any, K comparable](inputs []K, rows []*T, key func(*T) K) ([]*T, []K) {
	index := make(map[K]*T, len(rows))

	for _, row := range rows {
		if row == nil {
			continue
		}

		index[key(row)] = row
	}

	ordered := make([]*T, 0, len(inputs))
	missing := make([]K, 0)
	seenMissing := make(map[K]struct{})

	for _, input := range inputs {
		row, ok := index[input]
		if ok {
			ordered = append(ordered, row)
			continue
		}

		if _, exists := seenMissing[input]; exists {
			continue
		}

		seenMissing[input] = struct{}{}

		missing = append(missing, input)
	}

	return ordered, missing
}
