// Code generated by tsq-v4.1.22. DO NOT EDIT.

package academy

import (
	"encoding/json"

	"github.com/tmoeish/tsq/v4"
	tsqdialect "github.com/tmoeish/tsq/v4/dialect"
)

// TSQTables returns all generated table registrations for this package.
func TSQTables() []tsq.TableRegistration {
	return []tsq.TableRegistration{
		{
			Table: TableCourse,
			Columns: []tsqdialect.DDLColumnSpec{
				{
					Name: "id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					PrimaryKey:    true,
					AutoIncrement: true,
				},
				{
					Name: "created_at",
					Type: tsqdialect.DDLColumnType{
						Kind:     tsqdialect.DDLColumnKindTime,
						Nullable: true,
					},
				},
				{
					Name: "instructor_id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "level",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 32,
					},
				},
				{
					Name: "list_price_cents",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "prerequisite_id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "published",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindBool,
					},
				},
				{
					Name: "summary",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 4096,
					},
				},
				{
					Name: "title",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 160,
					},
				},
				{
					Name: "track_id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
			},
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_course_title", Unique: true, Fields: []string{"title"}},
				// Declared non-unique indexes.
				{Name: "idx_course_instructor_id", Fields: []string{"instructor_id"}},
				{Name: "idx_course_prerequisite_id", Fields: []string{"prerequisite_id"}},
				{Name: "idx_course_track_id", Fields: []string{"track_id"}},
			},
		},
		{
			Table: TableEnrollment,
			Columns: []tsqdialect.DDLColumnSpec{
				{
					Name: "uid",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					PrimaryKey:    true,
					AutoIncrement: true,
				},
				{
					Name: "created_at",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindTime,
					},
					Default: "CURRENT_TIMESTAMP",
				},
				{
					Name: "updated_at",
					Type: tsqdialect.DDLColumnType{
						Kind:     tsqdialect.DDLColumnKindTime,
						Nullable: true,
					},
				},
				{
					Name: "deleted_at",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					Default: "0",
				},
				{
					Name: "version",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					Default: "1",
				},
				{
					Name: "course_id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "fee_cents",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "learner_id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "score",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
				},
				{
					Name: "status",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 32,
					},
				},
			},
			Indexes: []tsq.TableIndex{
				// Declared non-unique indexes.
				{Name: "idx_enrollment_course_id", Fields: []string{"deleted_at", "course_id"}},
				{Name: "idx_enrollment_learner_id_course_id", Fields: []string{"deleted_at", "learner_id", "course_id"}},
				{Name: "idx_enrollment_status", Fields: []string{"deleted_at", "status"}},
			},
		},
		{
			Table: TableInstructor,
			Columns: []tsqdialect.DDLColumnSpec{
				{
					Name: "id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					PrimaryKey:    true,
					AutoIncrement: true,
				},
				{
					Name: "created_at",
					Type: tsqdialect.DDLColumnType{
						Kind:     tsqdialect.DDLColumnKindTime,
						Nullable: true,
					},
				},
				{
					Name: "bio",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 2048,
					},
				},
				{
					Name: "email",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 160,
					},
				},
				{
					Name: "name",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 120,
					},
				},
				{
					Name: "specialty",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 160,
					},
				},
			},
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_instructor_email", Unique: true, Fields: []string{"email"}},
			},
		},
		{
			Table: TableLearner,
			Columns: []tsqdialect.DDLColumnSpec{
				{
					Name: "id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					PrimaryKey:    true,
					AutoIncrement: true,
				},
				{
					Name: "created_at",
					Type: tsqdialect.DDLColumnType{
						Kind:     tsqdialect.DDLColumnKindTime,
						Nullable: true,
					},
				},
				{
					Name: "company",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 160,
					},
				},
				{
					Name: "email",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 160,
					},
				},
				{
					Name: "name",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 120,
					},
				},
			},
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_learner_email", Unique: true, Fields: []string{"email"}},
				// Declared non-unique indexes.
				{Name: "idx_learner_company", Fields: []string{"company"}},
			},
		},
		{
			Table: TableTrack,
			Columns: []tsqdialect.DDLColumnSpec{
				{
					Name: "id",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindInt,
						Bits: 64,
					},
					PrimaryKey:    true,
					AutoIncrement: true,
				},
				{
					Name: "created_at",
					Type: tsqdialect.DDLColumnType{
						Kind:     tsqdialect.DDLColumnKindTime,
						Nullable: true,
					},
				},
				{
					Name: "description",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 1024,
					},
				},
				{
					Name: "name",
					Type: tsqdialect.DDLColumnType{
						Kind: tsqdialect.DDLColumnKindString,
						Size: 120,
					},
				},
				{
					Name: "skill_items",
					Type: tsqdialect.DDLColumnType{
						RawType: "JSON",
						Kind:    tsqdialect.DDLColumnKindBytes,
					},
				},
			},
			Indexes: []tsq.TableIndex{
				// Declared unique indexes.
				{Name: "ux_track_name", Unique: true, Fields: []string{"name"}},
			},
		},
	}
}

//// Helper functions

// compactJSON marshals a value to JSON and returns it as a string, or an empty string if marshaling fails.
func compactJSON(v any) string {
	bs, err := json.Marshal(v)
	if err != nil {
		return ""
	}

	return string(bs)
}

// matchByInputOrder reorders rows to match inputs and reports which keys were missing.
func matchByInputOrder[T any, K comparable](inputs []K, rows []*T, key func(*T) K) ([]*T, []K) {
	index := make(map[K]*T, len(rows))

	for _, row := range rows {
		if row == nil {
			continue
		}

		index[key(row)] = row
	}

	ordered := make([]*T, 0, len(inputs))
	missing := make([]K, 0)
	seenMissing := make(map[K]struct{})

	for _, input := range inputs {
		row, ok := index[input]
		if ok {
			ordered = append(ordered, row)
			continue
		}

		if _, exists := seenMissing[input]; exists {
			continue
		}

		seenMissing[input] = struct{}{}

		missing = append(missing, input)
	}

	return ordered, missing
}

// matchByInputOrderKey reorders rows to match inputs using derived string keys and reports which keys were missing.
func matchByInputOrderKey[T any, K any](inputs []K, rows []*T, rowKey func(*T) string, inputKey func(K) string) ([]*T, []K) {
	index := make(map[string]*T, len(rows))

	for _, row := range rows {
		if row == nil {
			continue
		}

		index[rowKey(row)] = row
	}

	ordered := make([]*T, 0, len(inputs))
	missing := make([]K, 0)
	seenMissing := make(map[string]struct{})

	for _, input := range inputs {
		k := inputKey(input)
		row, ok := index[k]
		if ok {
			ordered = append(ordered, row)
			continue
		}

		if _, exists := seenMissing[k]; exists {
			continue
		}

		seenMissing[k] = struct{}{}
		missing = append(missing, input)
	}

	return ordered, missing
}
