-- Code generated by tsq-v4.1.14. DO NOT EDIT.

-- Dialect: sqlite

-- Table: course

CREATE TABLE IF NOT EXISTS "course" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "instructor_id" INTEGER NOT NULL,
    "level" INTEGER NOT NULL,
    "list_price_cents" INTEGER NOT NULL,
    "prerequisite_id" INTEGER NOT NULL,
    "published" BOOLEAN NOT NULL,
    "summary" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "track_id" INTEGER NOT NULL
);

CREATE INDEX "idx_course_instructor_id" ON "course"("instructor_id")

CREATE INDEX "idx_course_prerequisite_id" ON "course"("prerequisite_id")

CREATE INDEX "idx_course_track_id" ON "course"("track_id")

CREATE UNIQUE INDEX "ux_course_title" ON "course"("title")


-- Table: enrollment

CREATE TABLE IF NOT EXISTS "enrollment" (
    "uid" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 1,
    "course_id" INTEGER NOT NULL,
    "fee_cents" INTEGER NOT NULL,
    "learner_id" INTEGER NOT NULL,
    "score" INTEGER NOT NULL,
    "status" INTEGER NOT NULL
);

CREATE INDEX "idx_enrollment_course_id" ON "enrollment"("course_id")

CREATE INDEX "idx_enrollment_learner_id_course_id" ON "enrollment"("learner_id", "course_id")

CREATE INDEX "idx_enrollment_status" ON "enrollment"("status")


-- Table: instructor

CREATE TABLE IF NOT EXISTS "instructor" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "bio" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "specialty" TEXT NOT NULL
);

CREATE UNIQUE INDEX "ux_instructor_email" ON "instructor"("email")


-- Table: learner

CREATE TABLE IF NOT EXISTS "learner" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "company" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL
);

CREATE INDEX "idx_learner_company" ON "learner"("company")

CREATE UNIQUE INDEX "ux_learner_email" ON "learner"("email")


-- Table: track

CREATE TABLE IF NOT EXISTS "track" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "description" TEXT NOT NULL,
    "name" TEXT NOT NULL
);

CREATE UNIQUE INDEX "ux_track_name" ON "track"("name")
