// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// CourseTable is the course table: the descriptor of Course rows, with one field
// per column.
type CourseTable struct {
	*tsq.TableOf[Course, int64]

	ID             tsq.Column[Course, int64]
	CreatedAt      tsq.NullColumn[Course, tsqtime.Time]
	TrackID        tsq.Column[Course, int64]
	InstructorID   tsq.Column[Course, int64]
	PrerequisiteID tsq.Column[Course, int64]
	Title          tsq.Column[Course, string]
	Summary        tsq.Column[Course, string]
	Level          tsq.Column[Course, CourseLevel]
	ListPriceCents tsq.Column[Course, int64]
	Published      tsq.Column[Course, bool]
	Currency       tsq.NullColumn[Course, string]
	Blurb          tsq.NullColumn[Course, string]
	Slug           tsq.Column[Course, string]
}

// TableCourse is the course table.
var TableCourse = newCourseTable()

// newCourseTable declares the table, its columns, then its definition, so that
// anything naming TableCourse is initialized after the table is complete.
func newCourseTable() CourseTable {
	t := tsq.NewTable[Course, int64]("course")
	c := CourseTable{
		TableOf:        t,
		ID:             tsq.NewColumn(t, "id", "id", func(r *Course) *int64 { return &r.ID }),
		CreatedAt:      tsq.NewNullColumn[tsqtime.Time](t, "created_at", "created_at", func(r *Course) *tsqsql.Null[tsqtime.Time] { return &r.CreatedAt }),
		TrackID:        tsq.NewColumn(t, "track_id", "track_id", func(r *Course) *int64 { return &r.TrackID }),
		InstructorID:   tsq.NewColumn(t, "instructor_id", "instructor_id", func(r *Course) *int64 { return &r.InstructorID }),
		PrerequisiteID: tsq.NewColumn(t, "prerequisite_id", "prerequisite_id", func(r *Course) *int64 { return &r.PrerequisiteID }),
		Title:          tsq.NewColumn(t, "title", "title", func(r *Course) *string { return &r.Title }),
		Summary:        tsq.NewColumn(t, "summary", "summary", func(r *Course) *string { return &r.Summary }),
		Level:          tsq.NewColumn(t, "level", "level", func(r *Course) *CourseLevel { return &r.Level }),
		ListPriceCents: tsq.NewColumn(t, "list_price_cents", "list_price_cents", func(r *Course) *int64 { return &r.ListPriceCents }),
		Published:      tsq.NewColumn(t, "published", "published", func(r *Course) *bool { return &r.Published }),
		Currency:       tsq.NewNullColumn[string](t, "currency", "currency", func(r *Course) **string { return &r.Currency }),
		Blurb:          tsq.NewNullColumn[string](t, "blurb", "blurb", func(r *Course) **string { return &r.Blurb }),
		Slug:           tsq.NewColumn(t, "slug", "slug", func(r *Course) *string { return &r.Slug }),
	}

	t.Define(tsq.TableSpec[Course, int64]{
		Columns: []tsq.BoundColumn[Course]{
			c.ID,
			c.CreatedAt,
			c.TrackID,
			c.InstructorID,
			c.PrerequisiteID,
			c.Title,
			c.Summary,
			c.Level,
			c.ListPriceCents,
			c.Published,
			c.Currency,
			c.Blurb,
			c.Slug,
		},
		PrimaryKey:    c.ID,
		AutoIncrement: true,
		CreatedAt:     c.CreatedAt,
		Search: []tsq.SearchColumn{
			tsq.Searchable(c.Title),
			tsq.Searchable(c.Summary),
		},
		ColumnSpecs: []tsqdialect.ColumnSpec{
			{
				Name: "id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				PrimaryKey:    true,
				AutoIncrement: true,
			},
			{
				Name: "created_at",
				Type: tsqdialect.ColumnType{
					Kind:     tsqdialect.KindTime,
					Nullable: true,
				},
			},
			{
				Name: "blurb",
				Type: tsqdialect.ColumnType{
					RawType:  "TEXT",
					Kind:     tsqdialect.KindString,
					Nullable: true,
					Size:     255,
				},
				Default: "'none'",
				Fill:    tsqdialect.FillDefault,
			},
			{
				Name: "currency",
				Type: tsqdialect.ColumnType{
					Kind:     tsqdialect.KindString,
					Nullable: true,
					Size:     3,
				},
				Default: "'USD'",
				Fill:    tsqdialect.FillDefault,
			},
			{
				Name: "instructor_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "level",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 32,
				},
			},
			{
				Name: "list_price_cents",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "prerequisite_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "published",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindBool,
				},
			},
			{
				Name: "slug",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 160,
				},
				Fill:      tsqdialect.FillGenerated,
				Generated: "LOWER(title)",
			},
			{
				Name: "summary",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 4096,
				},
			},
			{
				Name: "title",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 160,
				},
			},
			{
				Name: "track_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
		},
		Indexes: []tsq.IndexSpec{
			{Name: "ux_course_title", Unique: true, Columns: []string{"title"}},
			{Name: "idx_course_instructor_id", Columns: []string{"instructor_id"}},
			{Name: "idx_course_prerequisite_id", Columns: []string{"prerequisite_id"}},
			{Name: "idx_course_track_id", Columns: []string{"track_id"}},
			{Name: "ft_course_title_summary", FullText: true, Columns: []string{"title", "summary"}},
		},
	})

	return c
}

// As returns the table under alias, with every column bound to the alias, for
// joining the table more than once.
func (t CourseTable) As(alias string) CourseTable {
	a := t.TableOf.As(alias)

	return CourseTable{
		TableOf:        a,
		ID:             t.ID.WithTable(a),
		CreatedAt:      tsq.RebindNull(t.CreatedAt, a),
		TrackID:        t.TrackID.WithTable(a),
		InstructorID:   t.InstructorID.WithTable(a),
		PrerequisiteID: t.PrerequisiteID.WithTable(a),
		Title:          t.Title.WithTable(a),
		Summary:        t.Summary.WithTable(a),
		Level:          t.Level.WithTable(a),
		ListPriceCents: t.ListPriceCents.WithTable(a),
		Published:      t.Published.WithTable(a),
		Currency:       tsq.RebindNull(t.Currency, a),
		Blurb:          tsq.RebindNull(t.Blurb, a),
		Slug:           t.Slug.WithTable(a),
	}
}

// FullTextTitleAndSummary is the full-text index ft_course_title_summary; search it with
// tsq.Matches.
func (t CourseTable) FullTextTitleAndSummary() tsq.FullTextIndex {
	return t.FullText("ft_course_title_summary")
}

// GetByTitle reads the Course matching unique index ux_course_title, and fails with an
// error wrapping sql.ErrNoRows when there is none.
func (t CourseTable) GetByTitle(
	ctx context.Context,
	db tsq.Executor,
	title string,
) (*Course, error) {
	return t.GetBy(ctx, db, t.Title, title)
}

// FindByTitle is GetByTitle that returns nil, nil when there is no such row.
func (t CourseTable) FindByTitle(
	ctx context.Context,
	db tsq.Executor,
	title string,
) (*Course, error) {
	return t.FindBy(ctx, db, t.Title, title)
}

// FetchByTitle reads the Course rows matching unique index ux_course_title, one per
// Title value, in the order given; see tsq.TableOf.FetchBy.
func (t CourseTable) FetchByTitle(
	ctx context.Context,
	db tsq.Executor,
	titles ...string,
) ([]*Course, error) {
	return t.FetchBy(ctx, db, t.Title, titles)
}

// Insert inserts the row; see tsq.TableOf.Insert.
func (c *Course) Insert(ctx context.Context, db tsq.Executor) error {
	return TableCourse.Insert(ctx, db, c)
}

// Update writes the row, or only cols when given; see tsq.TableOf.Update.
func (c *Course) Update(ctx context.Context, db tsq.Executor, cols ...tsq.BoundColumn[Course]) error {
	return TableCourse.Update(ctx, db, c, cols...)
}

// HardDelete removes the row from the table.
func (c *Course) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableCourse.HardDelete(ctx, db, c)
}
