// Code generated by tsq-v4.10.0. DO NOT EDIT.

package academy

import (
	"github.com/tmoeish/tsq/v5"
)

// TSQTables returns every table declared in this package, for tsq.Open and
// tsq.NewRuntime.
func TSQTables() []tsq.Table {
	return []tsq.Table{
		TableCourse,
		TableEnrollment,
		TableInstructor,
		TableLearner,
		TableTrack,
	}
}
