-- Code generated by tsq-v4.10.0. DO NOT EDIT.

-- Dialect: sqlite

-- Table: course

CREATE TABLE IF NOT EXISTS "course" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "currency" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "instructor_id" INTEGER NOT NULL,
    "level" INTEGER NOT NULL,
    "list_price_cents" INTEGER NOT NULL,
    "prerequisite_id" INTEGER NOT NULL,
    "published" BOOLEAN NOT NULL,
    "slug" VARCHAR(160) GENERATED ALWAYS AS (LOWER(title)) STORED,
    "summary" VARCHAR(4096) NOT NULL,
    "title" VARCHAR(160) NOT NULL,
    "track_id" INTEGER NOT NULL
);

CREATE INDEX "idx_course_instructor_id" ON "course"("instructor_id");

CREATE INDEX "idx_course_prerequisite_id" ON "course"("prerequisite_id");

CREATE INDEX "idx_course_track_id" ON "course"("track_id");

CREATE UNIQUE INDEX "ux_course_title" ON "course"("title");


-- Table: enrollment

CREATE TABLE IF NOT EXISTS "enrollment" (
    "uid" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 1,
    "course_id" INTEGER NOT NULL,
    "fee_cents" INTEGER NOT NULL,
    "learner_id" INTEGER NOT NULL,
    "score" INTEGER NOT NULL,
    "status" INTEGER NOT NULL
);

CREATE INDEX "idx_enrollment_course_id" ON "enrollment"("deleted_at", "course_id");

CREATE INDEX "idx_enrollment_learner_id_course_id" ON "enrollment"("deleted_at", "learner_id", "course_id");

CREATE INDEX "idx_enrollment_status" ON "enrollment"("deleted_at", "status");


-- Table: instructor

CREATE TABLE IF NOT EXISTS "instructor" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "bio" VARCHAR(2048) NOT NULL,
    "email" VARCHAR(160) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "specialty" VARCHAR(160) NOT NULL
);

CREATE UNIQUE INDEX "ux_instructor_email" ON "instructor"("email");


-- Table: learner

CREATE TABLE IF NOT EXISTS "learner" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "company" VARCHAR(160) NOT NULL,
    "email" VARCHAR(160) NOT NULL,
    "name" VARCHAR(120) NOT NULL
);

CREATE INDEX "idx_learner_company" ON "learner"("company");

CREATE UNIQUE INDEX "ux_learner_email" ON "learner"("email");


-- Table: track

CREATE TABLE IF NOT EXISTS "track" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "description" VARCHAR(1024) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "skill_items" JSON NOT NULL
);

CREATE UNIQUE INDEX "ux_track_name" ON "track"("name");

-- Migration: 2026-09-29 11:19:35

-- Table: course

-- course: rebuilt by copying its rows; triggers on it are dropped and must be created again

PRAGMA foreign_keys = OFF;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "__tsq_new_course" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "currency" VARCHAR(3) DEFAULT 'USD',
    "instructor_id" INTEGER NOT NULL,
    "level" INTEGER NOT NULL,
    "list_price_cents" INTEGER NOT NULL,
    "prerequisite_id" INTEGER NOT NULL,
    "published" BOOLEAN NOT NULL,
    "slug" VARCHAR(160) GENERATED ALWAYS AS (LOWER(title)) STORED,
    "summary" VARCHAR(4096) NOT NULL,
    "title" VARCHAR(160) NOT NULL,
    "track_id" INTEGER NOT NULL
);

INSERT INTO "__tsq_new_course" ("id", "created_at", "currency", "instructor_id", "level", "list_price_cents", "prerequisite_id", "published", "summary", "title", "track_id") SELECT "id", "created_at", "currency", "instructor_id", "level", "list_price_cents", "prerequisite_id", "published", "summary", "title", "track_id" FROM "course";

DELETE FROM sqlite_sequence WHERE name = '__tsq_new_course';

INSERT INTO sqlite_sequence (name, seq) SELECT '__tsq_new_course', seq FROM sqlite_sequence WHERE name = 'course';

DROP TABLE "course";

ALTER TABLE "__tsq_new_course" RENAME TO "course";

CREATE INDEX "idx_course_instructor_id" ON "course"("instructor_id");

CREATE INDEX "idx_course_prerequisite_id" ON "course"("prerequisite_id");

CREATE INDEX "idx_course_track_id" ON "course"("track_id");

CREATE UNIQUE INDEX "ux_course_title" ON "course"("title");

PRAGMA foreign_key_check;

COMMIT;

PRAGMA foreign_keys = ON;

-- Migration: 2026-09-29 15:39:59

-- Table: course

ALTER TABLE "course" ADD COLUMN "blurb" TEXT DEFAULT 'none';

-- Migration: 2026-09-29 16:19:27

-- Table: course

-- course: rebuilt by copying its rows; triggers on it are dropped and must be created again

PRAGMA foreign_keys = OFF;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS "__tsq_new_course" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "blurb" TEXT DEFAULT 'not_set',
    "currency" VARCHAR(3) DEFAULT 'USD',
    "instructor_id" INTEGER NOT NULL,
    "level" INTEGER NOT NULL,
    "list_price_cents" INTEGER NOT NULL,
    "prerequisite_id" INTEGER NOT NULL,
    "published" BOOLEAN NOT NULL,
    "slug" VARCHAR(160) GENERATED ALWAYS AS (LOWER(title)) STORED,
    "summary" VARCHAR(4096) NOT NULL,
    "title" VARCHAR(160) NOT NULL,
    "track_id" INTEGER NOT NULL
);

INSERT INTO "__tsq_new_course" ("id", "created_at", "blurb", "currency", "instructor_id", "level", "list_price_cents", "prerequisite_id", "published", "summary", "title", "track_id") SELECT "id", "created_at", "blurb", "currency", "instructor_id", "level", "list_price_cents", "prerequisite_id", "published", "summary", "title", "track_id" FROM "course";

DELETE FROM sqlite_sequence WHERE name = '__tsq_new_course';

INSERT INTO sqlite_sequence (name, seq) SELECT '__tsq_new_course', seq FROM sqlite_sequence WHERE name = 'course';

DROP TABLE "course";

ALTER TABLE "__tsq_new_course" RENAME TO "course";

CREATE INDEX "idx_course_instructor_id" ON "course"("instructor_id");

CREATE INDEX "idx_course_prerequisite_id" ON "course"("prerequisite_id");

CREATE INDEX "idx_course_track_id" ON "course"("track_id");

CREATE UNIQUE INDEX "ux_course_title" ON "course"("title");

PRAGMA foreign_key_check;

COMMIT;

PRAGMA foreign_keys = ON;
