package cmd

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	goparser "go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"golang.org/x/tools/go/packages"

	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
	"github.com/tmoeish/tsq/v5/internal/buildinfo"
	"github.com/tmoeish/tsq/v5/internal/genmodel"
	sqld "github.com/tmoeish/tsq/v5/internal/sqldialect"
)

const ddlGeneratedFileHeaderPrefix = "-- Code generated by tsq-"

const ddlDefaultStringSize = 255

type ddlFileModel struct {
	Filename string
	Source   []byte
}

type ddlArtifacts struct {
	models       []ddlFileModel
	firstRun     bool
	hasChange    bool
	recordTables []ddlStateRecordTable
}

type ddlDialectSpec struct {
	dialect sqld.Dialect
}

type ddlTypeResolver struct {
	packages map[string]*packages.Package
}

type ddlColumnKind string

const (
	ddlColumnBool   ddlColumnKind = "bool"
	ddlColumnBytes  ddlColumnKind = "bytes"
	ddlColumnFloat  ddlColumnKind = "float"
	ddlColumnInt    ddlColumnKind = "int"
	ddlColumnString ddlColumnKind = "string"
	ddlColumnTime   ddlColumnKind = "time"
)

// fill translates the tag options into who provides the column's value.
func (o ddlTagOptions) fill() string {
	switch {
	case o.generated:
		return "generated"
	case o.defaultExpr != "":
		return "default"
	default:
		return ""
	}
}

type ddlColumnDescriptor struct {
	kind     ddlColumnKind
	bits     int
	unsigned bool
	nullable bool
	size     int
	rawType  string
	// fill and generated come from the db tag: who provides the value.
	fill         string
	defaultExpr  string
	generatedSQL string
}

var ddlDialects = []ddlDialectSpec{
	{dialect: sqld.SQLiteDialect{}},
	{dialect: sqld.MySQLDialect{}},
	{dialect: sqld.PostgresDialect{}},
}

func buildDDLArtifacts(packagePath string, list []*genmodel.StructInfo, outDir string) (ddlArtifacts, error) {
	if err := validateIndexNameCollisions(list); err != nil {
		return ddlArtifacts{}, err
	}

	tables := make([]*genmodel.StructInfo, 0, len(list))
	for _, item := range list {
		if item == nil || item.TableMeta == nil || item.IsResult || len(item.Fields) == 0 {
			continue
		}

		tables = append(tables, item)
	}

	sort.Slice(tables, func(i, j int) bool {
		if tables[i].Table == tables[j].Table {
			return tables[i].TypeInfo.TypeName < tables[j].TypeInfo.TypeName
		}

		return tables[i].Table < tables[j].Table
	})

	resolver, err := newDDLTypeResolver(packagePath, outDir)
	if err != nil {
		return ddlArtifacts{}, err
	}

	version := stableVersion(buildinfo.Version())

	currentSnapshot, err := buildCurrentDDLSnapshot(tables, resolver)
	if err != nil {
		return ddlArtifacts{}, err
	}

	previousState, err := loadDDLStateFile(outDir)
	if err != nil {
		return ddlArtifacts{}, err
	}

	var previousSnapshot *ddlSnapshot
	if previousState != nil {
		previousSnapshot = &previousState.Snapshot
	}

	changes := diffDDLSnapshots(previousSnapshot, currentSnapshot)
	recordTables := buildDDLRecordTables(changes)
	hasChange := len(recordTables) > 0
	models := make([]ddlFileModel, 0, len(ddlDialects)+1)
	dialectHistory := make(map[string]ddlStateDialectDiff, len(ddlDialects))
	firstRun := previousState == nil
	currentDialects := make(map[string][]byte, len(ddlDialects))

	for _, dialect := range ddlDialects {
		name := ddlDialectName(dialect)
		currentDialects[name] = renderDDLSnapshotAggregateFile(version, currentSnapshot, dialect)
	}

	initialDialects, renderedRecords, err := buildDDLInitialDialects(previousState, outDir, currentDialects)
	if err != nil {
		return ddlArtifacts{}, err
	}

	sequence := ""
	if previousState != nil && hasChange {
		sequence = time.Now().Format(time.DateTime)
	}

	for _, dialect := range ddlDialects {
		name := ddlDialectName(dialect)

		diffRecord, err := renderDDLIncrementalArtifact(dialect, changes)
		if err != nil {
			return ddlArtifacts{}, err
		}
		dialectHistory[name] = diffRecord
	}

	stateSource, err := marshalDDLStateFile(
		version,
		previousState,
		currentSnapshot,
		initialDialects,
		renderedRecords,
		recordTables,
		dialectHistory,
		sequence,
	)
	if err != nil {
		return ddlArtifacts{}, err
	}

	var state ddlStateFile
	if err := json.Unmarshal(stateSource, &state); err != nil {
		return ddlArtifacts{}, fmt.Errorf("failed to parse rendered DDL state: %w", err)
	}

	for _, dialect := range ddlDialects {
		name := ddlDialectName(dialect)

		source, err := renderDDLAggregateFileFromState(state, name)
		if err != nil {
			return ddlArtifacts{}, err
		}

		models = append(models, ddlFileModel{
			Filename: filepath.Join(outDir, name+".sql"),
			Source:   source,
		})
	}

	models = append(models, ddlFileModel{
		Filename: filepath.Join(outDir, ddlStateFilename),
		Source:   stateSource,
	})

	sort.Slice(models, func(i, j int) bool {
		return models[i].Filename < models[j].Filename
	})

	return ddlArtifacts{
		models:       models,
		firstRun:     firstRun,
		hasChange:    hasChange,
		recordTables: append([]ddlStateRecordTable(nil), recordTables...),
	}, nil
}

func buildDDLInitialDialects(
	previous *ddlStateFile,
	outDir string,
	current map[string][]byte,
) (map[string]ddlStateDialectSQL, int, error) {
	if previous != nil && len(previous.InitialDialects) > 0 {
		renderedRecords := min(previous.RenderedRecords, len(previous.Records))

		return cloneDDLStateDialects(previous.InitialDialects), renderedRecords, nil
	}

	initial := make(map[string]ddlStateDialectSQL, len(ddlDialects))
	for _, dialect := range ddlDialects {
		name := ddlDialectName(dialect)
		filename := filepath.Join(outDir, name+".sql")

		content, err := os.ReadFile(filename)
		switch {
		case os.IsNotExist(err):
			content = current[name]
		case err != nil:
			return nil, 0, err
		default:
			if !isGeneratedDDLArtifact(content) {
				return nil, 0, fmt.Errorf("refusing to read non-generated DDL file: %s", filename)
			}

			// The history lives in tsq.json; without it the file's schema would be
			// taken as the start of history, and every change since the last run
			// would reach no migration.
			if previous == nil {
				return nil, 0, fmt.Errorf("%s exists but %s does not: restore %s (from version control), or delete the generated .sql files to start the history again",
					filename, ddlStateFilename, filepath.Join(outDir, ddlStateFilename))
			}
		}

		initial[name] = ddlStateDialectSQL{SQL: string(content)}
	}

	renderedRecords := 0
	if previous != nil {
		renderedRecords = len(previous.Records)
	}

	return initial, renderedRecords, nil
}

func renderDDLHeader(version string) string {
	return fmt.Sprintf("%s%s. DO NOT EDIT.\n\n", ddlGeneratedFileHeaderPrefix, version)
}

func orderedDDLFields(table *genmodel.StructInfo) []genmodel.FieldInfo {
	fields := make([]genmodel.FieldInfo, 0, len(table.Fields))
	fields = append(fields, table.Fields...)

	rank := func(name string) int {
		switch name {
		case table.PrimaryKey:
			return 0
		case table.CreatedAtField:
			return 1
		case table.UpdatedAtField:
			return 2
		case table.DeletedAtField:
			return 3
		case table.VersionField:
			return 4
		default:
			return 10
		}
	}

	sort.Slice(fields, func(i, j int) bool {
		leftRank := rank(fields[i].Name)

		rightRank := rank(fields[j].Name)
		if leftRank != rightRank {
			return leftRank < rightRank
		}

		if fields[i].Column != fields[j].Column {
			return fields[i].Column < fields[j].Column
		}

		return fields[i].Name < fields[j].Name
	})

	return fields
}

// ddlColumnDefault is the DEFAULT clause of the column: the one the db tag asks
// for, or the one a managed column gets.
func ddlColumnDefault(table *genmodel.StructInfo, field genmodel.FieldInfo, desc ddlColumnDescriptor) string {
	if desc.defaultExpr != "" {
		return desc.defaultExpr
	}

	return ddlManagedDefaultClause(table, field, desc)
}

func ddlManagedDefaultClause(table *genmodel.StructInfo, field genmodel.FieldInfo, desc ddlColumnDescriptor) string {
	switch field.Name {
	case table.CreatedAtField:
		if desc.kind == ddlColumnTime && !desc.nullable {
			return "CURRENT_TIMESTAMP"
		}
	case table.DeletedAtField:
		if desc.kind == ddlColumnInt && !desc.nullable {
			return "0"
		}
	case table.VersionField:
		if desc.kind == ddlColumnInt && !desc.nullable {
			return "1"
		}
	}

	return ""
}

func ddlDialectName(dialect ddlDialectSpec) string {
	return string(dialect.dialect.Name())
}

func ddlColumnSpecFromSnapshot(column ddlSnapshotColumn) tsqdialect.ColumnSpec {
	return tsqdialect.ColumnSpec{
		Name: column.Name,
		Type: tsqdialect.ColumnType{
			Kind:     tsqdialect.ColumnKind(column.Kind),
			Bits:     column.Bits,
			Unsigned: column.Unsigned,
			Nullable: column.Nullable,
			Size:     column.Size,
			RawType:  column.RawType,
		},
		PrimaryKey:    column.PrimaryKey,
		AutoIncrement: column.AutoIncrement,
		Default:       column.Default,
		Fill:          ddlFillOf(column.Fill),
		Generated:     column.Generated,
	}
}

// ddlFillOf maps the generated model's fill name onto the dialect value.
func ddlFillOf(fill string) tsqdialect.Fill {
	switch fill {
	case "default":
		return tsqdialect.FillDefault
	case "generated":
		return tsqdialect.FillGenerated
	default:
		return tsqdialect.FillCaller
	}
}

func renderDDLColumnSpec(dialect sqld.Dialect, column tsqdialect.ColumnSpec) (string, error) {
	return sqld.ColumnDefinitionSQL(dialect, column)
}

func newDDLTypeResolver(packagePath, dir string) (*ddlTypeResolver, error) {
	cfg, pattern, err := resolveDDLLoadRequest(packagePath, dir)
	if err != nil {
		return nil, err
	}

	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		return nil, err
	}

	all := flattenLoadedPackages(pkgs)

	byPath := make(map[string]*packages.Package, len(all))
	for _, pkg := range all {
		if pkg.PkgPath == "" {
			continue
		}

		byPath[pkg.PkgPath] = pkg
	}

	if len(byPath) == 0 {
		return nil, fmt.Errorf("failed to load package %s", packagePath)
	}

	return &ddlTypeResolver{packages: byPath}, nil
}

func resolveDDLLoadRequest(packagePath, dir string) (*packages.Config, string, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedImports |
			packages.NeedDeps |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedSyntax |
			packages.NeedModule,
	}

	pattern := packagePath

	switch {
	case dir != "":
		absDir, err := filepath.Abs(dir)
		if err != nil {
			return nil, "", err
		}

		cfg.Dir = absDir
		pattern = "."
	case filepath.IsAbs(packagePath):
		cfg.Dir = packagePath
		pattern = "."
	case strings.HasPrefix(packagePath, "."):
		absPath, err := filepath.Abs(packagePath)
		if err != nil {
			return nil, "", err
		}

		cfg.Dir = absPath
		pattern = "."
	}

	if cfg.Dir != "" {
		overlay, err := buildDDLGeneratedFileOverlay(cfg.Dir)
		if err != nil {
			return nil, "", err
		}

		if len(overlay) > 0 {
			cfg.Overlay = overlay
		}
	}

	return cfg, pattern, nil
}

func buildDDLGeneratedFileOverlay(dir string) (map[string][]byte, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}

	if err != nil {
		return nil, err
	}

	packageName, err := detectDDLPackageName(dir, entries)
	if err != nil {
		return nil, err
	}

	if packageName == "" {
		return nil, nil
	}

	overlay := make(map[string][]byte)

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".tsq.go") {
			continue
		}

		overlay[filepath.Join(dir, entry.Name())] = []byte("package " + packageName + "\n")
	}

	return overlay, nil
}

func detectDDLPackageName(dir string, entries []os.DirEntry) (string, error) {
	fileSet := token.NewFileSet()

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || strings.HasSuffix(name, ".tsq.go") {
			continue
		}

		file, err := goparser.ParseFile(fileSet, filepath.Join(dir, name), nil, goparser.PackageClauseOnly)
		if err != nil {
			return "", err
		}

		return file.Name.Name, nil
	}

	return "", nil
}

func flattenLoadedPackages(roots []*packages.Package) []*packages.Package {
	seen := make(map[string]struct{})
	ordered := make([]*packages.Package, 0)

	var visit func(*packages.Package)
	visit = func(pkg *packages.Package) {
		if pkg == nil {
			return
		}

		key := pkg.PkgPath
		if key == "" {
			key = pkg.ID
		}

		if _, ok := seen[key]; ok {
			return
		}

		seen[key] = struct{}{}

		ordered = append(ordered, pkg)

		importPaths := make([]string, 0, len(pkg.Imports))
		for path := range pkg.Imports {
			importPaths = append(importPaths, path)
		}

		sort.Strings(importPaths)

		for _, path := range importPaths {
			visit(pkg.Imports[path])
		}
	}

	for _, root := range roots {
		visit(root)
	}

	return ordered
}

func (r *ddlTypeResolver) describeField(
	table *genmodel.StructInfo,
	field genmodel.FieldInfo,
) (ddlColumnDescriptor, error) {
	namedType, pkg, err := r.lookupNamedStruct(table.TypeInfo)
	if err != nil {
		return ddlColumnDescriptor{}, err
	}

	varObj, tag, err := lookupDDLField(namedType, pkg, field.Name)
	if err != nil {
		return ddlColumnDescriptor{}, err
	}

	return classifyDDLColumnType(varObj.Type(), tag)
}

// isText reports whether field holds text: its type is string, or a named type
// whose underlying type is, which tsq.Searchable and the pattern functions take.
func (r *ddlTypeResolver) isText(table *genmodel.StructInfo, field genmodel.FieldInfo) (bool, error) {
	namedType, pkg, err := r.lookupNamedStruct(table.TypeInfo)
	if err != nil {
		return false, err
	}

	varObj, _, err := lookupDDLField(namedType, pkg, field.Name)
	if err != nil {
		return false, err
	}

	basic, ok := varObj.Type().Underlying().(*types.Basic)

	return ok && basic.Kind() == types.String, nil
}

func (r *ddlTypeResolver) lookupNamedStruct(typeInfo genmodel.TypeInfo) (*types.Named, *types.Package, error) {
	pkg, ok := r.packages[typeInfo.Package.Path]
	if !ok || pkg.Types == nil {
		return nil, nil, fmt.Errorf("loaded type package %s not found", typeInfo.Package.Path)
	}

	obj := pkg.Types.Scope().Lookup(typeInfo.TypeName)
	if obj == nil {
		return nil, nil, fmt.Errorf("type %s not found in package %s", typeInfo.TypeName, typeInfo.Package.Path)
	}

	typeName, ok := obj.(*types.TypeName)
	if !ok {
		return nil, nil, fmt.Errorf("%s in package %s is not a named type", typeInfo.TypeName, typeInfo.Package.Path)
	}

	named, ok := typeName.Type().(*types.Named)
	if !ok || underlyingStructType(named) == nil {
		return nil, nil, fmt.Errorf("%s is not a struct type", typeInfo.TypeName)
	}

	return named, pkg.Types, nil
}

func lookupDDLField(named *types.Named, pkg *types.Package, fieldName string) (*types.Var, string, error) {
	obj, index, _ := types.LookupFieldOrMethod(named, false, pkg, fieldName)
	if obj == nil {
		obj, index, _ = types.LookupFieldOrMethod(types.NewPointer(named), false, pkg, fieldName)
		if obj == nil {
			if first, _ := utf8.DecodeRuneInString(fieldName); unicode.IsLower(first) {
				return nil, "", fmt.Errorf("field %s is unexported in a type from another package, which the generated code cannot reach; export it", fieldName)
			}

			return nil, "", fmt.Errorf("field %s not found", fieldName)
		}
	}

	fieldObj, ok := obj.(*types.Var)
	if !ok || !fieldObj.IsField() {
		return nil, "", fmt.Errorf("%s is not a field", fieldName)
	}

	tag, err := lookupDDLFieldTag(named, index)
	if err != nil {
		return nil, "", err
	}

	return fieldObj, tag, nil
}

func lookupDDLFieldTag(root types.Type, index []int) (string, error) {
	current := root
	tag := ""

	for _, item := range index {
		structType := underlyingStructType(current)
		if structType == nil {
			return "", errors.New("field index does not resolve to a struct")
		}

		tag = structType.Tag(item)
		current = structType.Field(item).Type()
	}

	return tag, nil
}

func underlyingStructType(t types.Type) *types.Struct {
	switch value := t.(type) {
	case *types.Named:
		return underlyingStructType(value.Underlying())
	case *types.Pointer:
		return underlyingStructType(value.Elem())
	case *types.Struct:
		return value
	default:
		return nil
	}
}

func classifyDDLColumnType(t types.Type, rawTag string) (ddlColumnDescriptor, error) {
	opts, err := parseDDLTagOptions(reflect.StructTag(rawTag).Get("db"))
	if err != nil {
		return ddlColumnDescriptor{}, err
	}

	desc, err := classifyDDLColumnTypeRecursive(t, opts.size, false)
	if err != nil {
		if opts.rawType == "" {
			return ddlColumnDescriptor{}, fmt.Errorf(
				"%w; use db tag option type:<SQL_TYPE> to override the DDL column type",
				err,
			)
		}

		// The same rule the generated Go uses: a nullable form here is a NullColumn
		// there, so the column must accept NULL.
		_, nullableValue := nullableValueType(t)
		desc = ddlColumnDescriptor{
			nullable: ddlTypeNullable(t) || nullableValue,
		}
	}

	switch desc.kind {
	case ddlColumnString:
		desc.size = normalizeDDLStringSize(opts.size)
	case ddlColumnBytes:
		// Bytes have no default size; one declared picks MySQL's BLOB type.
		desc.size = opts.size
	}

	desc.rawType = opts.rawType
	desc.fill = opts.fill()
	desc.defaultExpr = opts.defaultExpr
	desc.generatedSQL = opts.generatedSQL

	return desc, nil
}

func classifyDDLColumnTypeRecursive(
	t types.Type,
	size int,
	nullable bool,
) (ddlColumnDescriptor, error) {
	switch value := t.(type) {
	case *types.Pointer:
		return classifyDDLColumnTypeRecursive(value.Elem(), size, true)
	case *types.Alias:
		return classifyDDLColumnTypeRecursive(types.Unalias(value), size, nullable)
	case *types.Named:
		if pkg := value.Obj().Pkg(); pkg != nil {
			switch pkg.Path() {
			case importPathTime:
				if value.Obj().Name() == "Time" {
					return ddlColumnDescriptor{kind: ddlColumnTime, nullable: nullable}, nil
				}
			case importPathDatabaseSQL:
				switch value.Obj().Name() {
				case "NullBool":
					return ddlColumnDescriptor{kind: ddlColumnBool, nullable: true}, nil
				case "NullFloat64":
					return ddlColumnDescriptor{kind: ddlColumnFloat, bits: 64, nullable: true}, nil
				case "NullInt64":
					return ddlColumnDescriptor{kind: ddlColumnInt, bits: 64, nullable: true}, nil
				case "NullString":
					return ddlColumnDescriptor{kind: ddlColumnString, nullable: true, size: size}, nil
				case "NullTime":
					return ddlColumnDescriptor{kind: ddlColumnTime, nullable: true}, nil
				case "Null":
					// sql.Null[T] is T that can be NULL.
					if args := value.TypeArgs(); args.Len() == 1 {
						return classifyDDLColumnTypeRecursive(args.At(0), size, true)
					}
				}
			default:
				if strings.HasPrefix(pkg.Path(), nullbioImportPrefix) {
					switch value.Obj().Name() {
					case "Time":
						return ddlColumnDescriptor{kind: ddlColumnTime, nullable: true}, nil
					case "String":
						return ddlColumnDescriptor{kind: ddlColumnString, nullable: true, size: size}, nil
					case "Bool":
						return ddlColumnDescriptor{kind: ddlColumnBool, nullable: true}, nil
					case "Float32":
						return ddlColumnDescriptor{kind: ddlColumnFloat, bits: 32, nullable: true}, nil
					case "Float64":
						return ddlColumnDescriptor{kind: ddlColumnFloat, bits: 64, nullable: true}, nil
					case "Int":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 32, nullable: true}, nil
					case "Int8":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 8, nullable: true}, nil
					case "Int16":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 16, nullable: true}, nil
					case "Int32":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 32, nullable: true}, nil
					case "Int64":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 64, nullable: true}, nil
					case "Uint":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 32, unsigned: true, nullable: true}, nil
					case "Uint8":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 8, unsigned: true, nullable: true}, nil
					case "Uint16":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 16, unsigned: true, nullable: true}, nil
					case "Uint32":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 32, unsigned: true, nullable: true}, nil
					case "Uint64":
						return ddlColumnDescriptor{kind: ddlColumnInt, bits: 64, unsigned: true, nullable: true}, nil
					}
				}
			}
		}

		// A codec type decides its own representation, which the underlying type
		// does not tell: a string type may store an integer. Guessing would create
		// the column without an error and fail on the first write, so it is declared.
		if method := codecMethod(value); method != "" {
			err := fmt.Errorf("%s implements %s, so its column type cannot be derived", types.TypeString(value, nil), method)
			if basic, ok := value.Underlying().(*types.Basic); ok {
				err = fmt.Errorf("%w (database/sql already stores a named %s as itself, which needs neither method)", err, basic.Name())
			}

			return ddlColumnDescriptor{}, err
		}

		return classifyDDLColumnTypeRecursive(value.Underlying(), size, nullable)

	case *types.Basic:
		info := value.Info()
		switch {
		case info&types.IsBoolean != 0:
			return ddlColumnDescriptor{kind: ddlColumnBool, nullable: nullable}, nil
		case info&types.IsString != 0:
			return ddlColumnDescriptor{kind: ddlColumnString, nullable: nullable, size: size}, nil
		case info&types.IsFloat != 0:
			bits := 64
			if value.Kind() == types.Float32 {
				bits = 32
			}

			return ddlColumnDescriptor{kind: ddlColumnFloat, bits: bits, nullable: nullable}, nil
		case info&types.IsInteger != 0:
			return ddlBasicIntegerDescriptor(value, nullable), nil
		}
	case *types.Slice:
		if elem, ok := value.Elem().(*types.Basic); ok && elem.Kind() == types.Byte {
			return ddlColumnDescriptor{kind: ddlColumnBytes, nullable: nullable}, nil
		}
	}

	return ddlColumnDescriptor{}, fmt.Errorf("unsupported DDL field type %s", types.TypeString(t, nil))
}

// codecMethod names the database/sql interface t implements, driver.Valuer or
// sql.Scanner, or "" when it implements neither. The pointer's method set counts:
// Scan has a pointer receiver.
func codecMethod(t *types.Named) string {
	for _, m := range []struct {
		name, iface  string
		params, outs int
	}{{"Value", "driver.Valuer", 0, 2}, {"Scan", "sql.Scanner", 1, 1}} {
		obj, _, _ := types.LookupFieldOrMethod(types.NewPointer(t), true, t.Obj().Pkg(), m.name)

		fn, ok := obj.(*types.Func)
		if !ok {
			continue
		}

		if sig, ok := fn.Type().(*types.Signature); ok && sig.Params().Len() == m.params && sig.Results().Len() == m.outs {
			return m.iface
		}
	}

	return ""
}

func normalizeDDLStringSize(size int) int {
	if size > 0 {
		return size
	}

	return ddlDefaultStringSize
}

func ddlBasicIntegerDescriptor(basic *types.Basic, nullable bool) ddlColumnDescriptor {
	desc := ddlColumnDescriptor{kind: ddlColumnInt, bits: 64, nullable: nullable}

	switch basic.Kind() {
	case types.Int8:
		desc.bits = 8
	case types.Int16:
		desc.bits = 16
	case types.Int32:
		desc.bits = 32
	case types.Int:
		desc.bits = 32
	case types.Int64:
		desc.bits = 64
	case types.Uint8:
		desc.bits = 8
		desc.unsigned = true
	case types.Uint16:
		desc.bits = 16
		desc.unsigned = true
	case types.Uint32:
		desc.bits = 32
		desc.unsigned = true
	case types.Uint:
		desc.bits = 32
		desc.unsigned = true
	case types.Uint64, types.Uintptr:
		desc.bits = 64
		desc.unsigned = true
	}

	return desc
}

type ddlTagOptions struct {
	size         int
	rawType      string
	defaultExpr  string
	generated    bool
	generatedSQL string
}

// parseDDLTagOptions reads the options of a db tag after the column name. An
// option it does not know, or one without a usable value, is an error: size:ten
// or a misspelled defualt: used to be ignored, and the column quietly got the
// type or default nobody asked for.
func parseDDLTagOptions(dbTag string) (ddlTagOptions, error) {
	opts := ddlTagOptions{}
	if dbTag == "" {
		return opts, nil
	}

	parts := splitDDLTagParts(dbTag)
	for _, part := range parts[1:] {
		key, value, ok := strings.Cut(strings.TrimSpace(part), ":")

		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)

		switch {
		case key == "generated" && !ok:
			// generated without an expression: the database computes the column,
			// and the schema it lives in is not TSQ's to write.
			opts.generated = true
		case key == "size":
			n, err := strconv.Atoi(value)
			if err != nil || n <= 0 {
				return opts, fmt.Errorf("db tag option size:%s is not a positive number", value)
			}

			opts.size = n
		case key == "type" && value != "":
			opts.rawType = value
		case key == "default" && value != "":
			opts.defaultExpr = value
		case key == "generated" && value != "":
			opts.generated = true
			opts.generatedSQL = value
		case key == "type" || key == "default" || key == "generated":
			return opts, fmt.Errorf("db tag option %s: needs a value", key)
		case key == "":
			return opts, fmt.Errorf("db tag %q has an empty option", dbTag)
		default:
			return opts, fmt.Errorf("db tag option %q is not one TSQ knows; it takes size:N, type:SQL, default:SQL and generated[:SQL]", key)
		}
	}

	return opts, nil
}

func splitDDLTagParts(dbTag string) []string {
	if dbTag == "" {
		return nil
	}

	parts := make([]string, 0, 4)
	var current strings.Builder
	depth := 0
	// A comma inside a SQL string literal (default:'a, b') is part of it; a
	// doubled quote inside one toggles twice and changes nothing.
	quoted := false

	for _, r := range dbTag {
		switch r {
		case '\'':
			quoted = !quoted
		case '(':
			if !quoted {
				depth++
			}
		case ')':
			if depth > 0 && !quoted {
				depth--
			}
		case ',':
			if depth == 0 && !quoted {
				parts = append(parts, current.String())
				current.Reset()

				continue
			}
		}

		current.WriteRune(r)
	}

	parts = append(parts, current.String())

	return parts
}

func ddlTypeNullable(t types.Type) bool {
	switch value := t.(type) {
	case *types.Pointer:
		return true
	case *types.Alias:
		return ddlTypeNullable(types.Unalias(value))
	case *types.Named:
		return ddlTypeNullable(value.Underlying())
	default:
		return false
	}
}

func buildDDLPlan(models []ddlFileModel, dir string) ([]generationPlanEntry, error) {
	plan := make([]generationPlanEntry, 0, len(models))
	plannedFiles := make(map[string]struct{}, len(models))

	for _, model := range models {
		status, err := ddlPlanStatusFor(model.Filename, model.Source)
		if err != nil {
			return nil, fmt.Errorf("failed to plan DDL file: %s"+": %w", model.Filename, err)
		}

		plan = append(plan, generationPlanEntry{
			Filename: model.Filename,
			Source:   model.Source,
			Status:   status,
		})
		plannedFiles[model.Filename] = struct{}{}
	}

	staleFiles, err := findStaleDDLFiles(dir, plannedFiles)
	if err != nil {
		return nil, err
	}

	for _, stale := range staleFiles {
		plan = append(plan, generationPlanEntry{
			Filename: stale,
			Status:   generationPlanStale,
		})
	}

	sort.Slice(plan, func(i, j int) bool {
		return plan[i].Filename < plan[j].Filename
	})

	return plan, nil
}

func ddlPlanStatusFor(filename string, src []byte) (generationPlanStatus, error) {
	existing, err := os.ReadFile(filename)
	if os.IsNotExist(err) {
		return generationPlanCreate, nil
	}

	if err != nil {
		return "", err
	}

	if bytes.Equal(existing, src) {
		return generationPlanUnchanged, nil
	}

	if err := ensureWritableDDLFile(filename); err != nil {
		return "", err
	}

	return generationPlanUpdate, nil
}

func findStaleDDLFiles(dir string, plannedFiles map[string]struct{}) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}

	if err != nil {
		return nil, err
	}

	stale := make([]string, 0)

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		if !strings.HasSuffix(name, ".sql") && name != ddlStateFilename {
			continue
		}

		filename := filepath.Join(dir, name)
		if _, ok := plannedFiles[filename]; ok {
			continue
		}

		content, err := os.ReadFile(filename)
		if err != nil {
			return nil, err
		}

		if !isGeneratedDDLArtifact(content) {
			continue
		}

		stale = append(stale, filename)
	}

	sort.Strings(stale)

	return stale, nil
}

func writeDDLFile(filename string, src []byte) error {
	if err := ensureWritableDDLFile(filename); err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(filename), 0o750); err != nil {
		return err
	}

	perm := os.FileMode(0o644)
	if info, err := os.Stat(filename); err == nil {
		perm = info.Mode().Perm()
	} else if !os.IsNotExist(err) {
		return err
	}

	dir := filepath.Dir(filename)
	pattern := "." + filepath.Base(filename) + ".tmp-*"

	tmpFile, err := os.CreateTemp(dir, pattern)
	if err != nil {
		return err
	}

	tmpName := tmpFile.Name()

	defer func() {
		_ = os.Remove(tmpName)
	}()

	if err := tmpFile.Chmod(perm); err != nil {
		_ = tmpFile.Close()
		return err
	}

	if _, err := tmpFile.Write(src); err != nil {
		_ = tmpFile.Close()
		return err
	}

	if err := tmpFile.Close(); err != nil {
		return err
	}

	return os.Rename(tmpName, filename)
}

func ensureWritableDDLFile(filename string) error {
	existing, err := os.ReadFile(filename)
	if os.IsNotExist(err) {
		return nil
	}

	if err != nil {
		return err
	}

	if len(existing) == 0 || isGeneratedDDLArtifact(existing) {
		return nil
	}

	return fmt.Errorf("refusing to overwrite non-generated file: %s", filename)
}

func isGeneratedDDLArtifact(content []byte) bool {
	if bytes.HasPrefix(content, []byte(ddlGeneratedFileHeaderPrefix)) {
		return true
	}

	var meta struct {
		GeneratedBy string `json:"generated_by"`
	}

	if err := json.Unmarshal(content, &meta); err != nil {
		return false
	}

	return strings.HasPrefix(meta.GeneratedBy, "tsq-")
}

// mysqlMaxKeyBytes is InnoDB's limit on an index key, and mysqlCharBytes the most
// a utf8mb4 character takes.
const (
	mysqlMaxKeyBytes = 3072
	mysqlCharBytes   = 4
)

// mysqlIndexProblem says why MySQL rejects an index over columns when the DDL
// runs, or "" when it does not: a TEXT or BLOB column cannot be indexed (error
// 1170), and a key can take at most 3072 bytes (error 1071; a VARCHAR(n) is up to
// 4n). A column of an unknown or explicit type: is not counted.
//
// It is a warning, not a refusal: a schema that only ever runs on PostgreSQL or
// SQLite may declare such an index, and tsq gen writes the DDL of every dialect.
func mysqlIndexProblem(index string, columns []string, typeOf func(column string) (tsqdialect.ColumnType, bool)) string {
	total := 0

	for _, name := range columns {
		columnType, ok := typeOf(name)
		if !ok || columnType.RawType != "" {
			continue
		}

		spelled := sqld.MySQLDialect{}.ColumnTypeSQL(columnType)

		var chars int

		switch {
		case strings.HasPrefix(spelled, "VARCHAR("):
			_, _ = fmt.Sscanf(spelled, "VARCHAR(%d)", &chars)
			total += chars * mysqlCharBytes
		case strings.HasSuffix(spelled, "TEXT"), strings.HasSuffix(spelled, "BLOB"):
			return fmt.Sprintf("index %s covers %s, a %s on MySQL, which cannot be indexed; give it a size: of at most %d or leave it out of the index",
				index, name, spelled, mysqlMaxKeyBytes/mysqlCharBytes)
		default:
			total += 8
		}
	}

	if total > mysqlMaxKeyBytes {
		return fmt.Sprintf("index %s can take %d bytes on MySQL, which limits a key to %d (%d bytes a character); lower the size: of its string columns or leave some out",
			index, total, mysqlMaxKeyBytes, mysqlCharBytes)
	}

	return ""
}

// mysqlIndexWarnings lists the indexes of s that MySQL would reject.
func mysqlIndexWarnings(s *genmodel.StructInfo) []string {
	columns := make(map[string]genmodel.SchemaColumn, len(s.Schema))
	for _, column := range s.Schema {
		columns[column.Name] = column
	}

	typeOf := func(name string) (tsqdialect.ColumnType, bool) {
		column, ok := columns[name]

		return tsqdialect.ColumnType{
			Kind: tsqdialect.ColumnKind(column.Kind), Bits: column.Bits, Unsigned: column.Unsigned, Size: column.Size, RawType: column.RawType,
		}, ok
	}

	var warnings []string

	for _, index := range slices.Concat(s.Uniques, s.Indexes) {
		cols := make([]string, 0, len(index.Fields)+1)
		for _, field := range indexFieldNames(s, index.Fields) {
			cols = append(cols, s.FieldsByName[field].Column)
		}

		if problem := mysqlIndexProblem(index.Name, cols, typeOf); problem != "" {
			warnings = append(warnings, s.TypeInfo.TypeName+": "+problem)
		}
	}

	return warnings
}
