#!/usr/bin/env python3
"""版本号的四个副本必须一致，且不能倒退。

失败的都是真实会发生的事故：改了 buildinfo 忘了写 CHANGELOG（使用者升级时读不到
迁移说明）；写了 CHANGELOG 忘了重新生成示例（生成文件头印着旧版本，别人 diff 时
以为自己环境坏了）；主版本跨到 v5 却没改 go.mod 的模块路径（Go Proxy 直接判非法
版本，`go get` 报 invalid version，而且 tag 一旦被抓取就再也改不回来）。
"""

from __future__ import annotations

import re
import sys
from typing import Final

from changeset import ChangesetError, PROJECT_ROOT
from version import (
    CHANGELOG_PATH,
    BUILDINFO_PATH,
    Version,
    VersionError,
    buildinfo_version,
    changelog_version,
    head_tag,
    latest_tag,
    module_major,
)

GENERATED_HEADER: Final = re.compile(r"^// Code generated by tsq-(?P<version>v\S+)\.")
EXAMPLE_GENERATED: Final = "examples/academy/runtime.tsq.go"

# `-X` 的目标包路径打错是**静默**失败的：链接器找不到符号时不报错，直接忽略，产出的二进制
# 把 build time / commit / branch 全报成 "unknown"。这个错在 `.goreleaser.yaml` 和
# `Dockerfile` 里各发生过一次（v4.4.3 修了前者，后者又活了三个月）。这里把三份构建配置里
# 每一个 `-X pkg.var=` 都对着 `internal/buildinfo` 真实声明的变量核一遍。
BUILDINFO_PACKAGE: Final = "github.com/tmoeish/tsq/v4/internal/buildinfo"
BUILDINFO_SOURCE: Final = "internal/buildinfo/buildinfo.go"
LDFLAGS_FILES: Final = ("Makefile", ".goreleaser.yaml", "Dockerfile")
# 包路径允许 Makefile 的 `$(MODULE)` 变量引用；`-X` 后面跟着 `something=` 的都算一个目标。
LDFLAG_X: Final = re.compile(r"-X\s+'?(?P<pkg>[A-Za-z0-9_./$()-]+)\.(?P<var>[A-Za-z_][A-Za-z0-9_]*)=")
LDFLAG_ANY: Final = re.compile(r"-X\s+'?[^\s'=]+=")
PACKAGE_VAR: Final = re.compile(r"^var\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=", re.MULTILINE)

WORKFLOW: Final = ".github/workflows/go.yml"
GORELEASER_REF: Final = "${{ env.GORELEASER_VERSION }}"
GORELEASER_PIN: Final = re.compile(
    r"^\s*GORELEASER_VERSION:\s*'(?P<version>v\d+\.\d+\.\d+)'\s*$", re.MULTILINE
)
GORELEASER_INSTALL: Final = re.compile(
    r"go install github\.com/goreleaser/goreleaser/v2@(?P<ref>.+?)\s*$", re.MULTILINE
)


class ReleaseError(RuntimeError):
    """版本号不一致时抛出。"""


def generated_version() -> Version:
    path = PROJECT_ROOT / EXAMPLE_GENERATED
    first = path.read_text(encoding="utf-8").splitlines()[0]
    match = GENERATED_HEADER.match(first)
    if match is None:
        raise ReleaseError(f"{EXAMPLE_GENERATED} 首行不是生成文件头：{first!r}")

    return Version.parse(match.group("version"))


def buildinfo_variables() -> set[str]:
    text = (PROJECT_ROOT / BUILDINFO_SOURCE).read_text(encoding="utf-8")

    return set(PACKAGE_VAR.findall(text))


def check_ldflags_targets() -> int:
    """三份构建配置里的每个 `-X` 都必须指向 internal/buildinfo 里真实存在的变量。"""
    variables = buildinfo_variables()
    problems: list[str] = []
    total = 0

    for name in LDFLAGS_FILES:
        text = (PROJECT_ROOT / name).read_text(encoding="utf-8")
        matches = list(LDFLAG_X.finditer(text))
        # 每个 `-X ` 都必须被上面的正则认出来：认不出来的形态（比如少了包路径里的点）
        # 同样是链接器会静默忽略的，不能因为长得不像就放过。
        if len(matches) != len(LDFLAG_ANY.findall(text)):
            problems.append(f"{name}: 有 -X 参数不符合 `-X <pkg>.<var>=` 形态")

        for match in matches:
            total += 1
            pkg, var = match.group("pkg"), match.group("var")
            # Makefile 用 $(MODULE)/internal/buildinfo 拼路径，只核后缀。
            if pkg != BUILDINFO_PACKAGE and not pkg.endswith("/internal/buildinfo"):
                problems.append(f"{name}: -X {pkg}.{var} 指向的不是 {BUILDINFO_PACKAGE}")
            elif var not in variables:
                problems.append(f"{name}: -X {pkg}.{var} 里的变量 {var} 在 {BUILDINFO_SOURCE} 中不存在")

    if problems:
        raise ReleaseError(
            "ldflags 的 -X 目标打错了包路径或变量名，链接器会静默忽略它：\n  - "
            + "\n  - ".join(problems)
        )

    return total


def check_release_tooling_pinned() -> str:
    """CI 安装的 goreleaser 必须钉死版本，且 check 与 release 用同一个。

    两次都真实发生过。`@latest` 在 goreleaser v2.18.1 发布那天开始要求 Go >= 1.27.1，
    而 CI 用 GOTOOLCHAIN=local 钉着 1.27.0，于是每个 PR 的 GoReleaser Check 都装不上
    工具而变红——改动本身完全无关。更贵的是 release job 的 `version: latest`：它只在
    **tag 推送之后**才跑，而 tag 一旦推出去就不能删了重打。

    check 与 release 用不同版本时，check job 证明不了 release 会成功，那它就没有存在
    的意义。
    """
    text = (PROJECT_ROOT / WORKFLOW).read_text(encoding="utf-8")

    pin = GORELEASER_PIN.search(text)
    if pin is None:
        raise ReleaseError(
            f"{WORKFLOW} 里没有 `GORELEASER_VERSION: 'vX.Y.Z'`。"
            "发版工具链要和 gosec、govulncheck 一样钉死版本。"
        )

    problems: list[str] = []

    installs = GORELEASER_INSTALL.findall(text)
    if not installs:
        problems.append("找不到安装 goreleaser 的步骤")

    for ref in installs:
        if ref != GORELEASER_REF:
            problems.append(f"安装用的是 `@{ref}`，应该是 `@{GORELEASER_REF}`")

    uses = text.count(GORELEASER_REF)
    if uses < 2:
        problems.append(
            f"`{GORELEASER_REF}` 只被引用了 {uses} 次；check job 和 release job 都要用它"
        )

    for number, line in enumerate(text.splitlines(), start=1):
        if "goreleaser" in line.lower() and "latest" in line:
            problems.append(f"第 {number} 行仍然是 latest：{line.strip()}")

    if problems:
        raise ReleaseError(
            "发版工具链没有钉死版本：\n  - " + "\n  - ".join(problems)
        )

    return pin.group("version")


def main() -> int:
    ldflags = check_ldflags_targets()
    goreleaser = check_release_tooling_pinned()
    code = buildinfo_version()
    changelog, date = changelog_version()
    generated = generated_version()

    if code != changelog:
        raise ReleaseError(
            f"{BUILDINFO_PATH} 是 {code}，{CHANGELOG_PATH} 置顶条目是 {changelog}。"
            "两者要一起改：使用者升级时读的是 CHANGELOG，`tsq version` 打印的是前者。"
        )

    if code != generated:
        raise ReleaseError(
            f"{BUILDINFO_PATH} 是 {code}，但 {EXAMPLE_GENERATED} 的文件头印着 "
            f"{generated}。跑 `make examples` 让生成物带上新版本号。"
        )

    if code.major != module_major():
        raise ReleaseError(
            f"版本号是 {code}，但 go.mod 的模块路径声明的是主版本 v{module_major()}。"
            "Go 的语义化导入版本要求 v2+ 把 `/vN` 写进模块路径，否则 Go Proxy 会判"
            "这个 tag 非法。改 go.mod、改所有内部 import，再发版。"
        )

    previous = latest_tag()
    pinned = head_tag()
    if pinned is not None and pinned != code:
        raise ReleaseError(
            f"HEAD 上打着 tag {pinned}，但代码里的版本是 {code}。"
            "tag 一旦推送就被 Go Proxy 永久缓存，不能删了重打——"
            "修好代码里的版本号，用一个新的补丁版本重新发。"
        )

    # 只查"倒退"，不查"没前进"。两个合法状态都必须放行：发版之间 buildinfo 等于最新
    # tag（这是常态，绝大多数提交都处在这里），而 `release.py` 跑 harness 的那一刻
    # buildinfo 已经领先于最新 tag（tag 要等 harness 全绿才打）。要求严格大于会同时
    # 拦下这两种情况，那是把门装反了。
    if previous is not None and code < previous:
        raise ReleaseError(
            f"代码里的版本 {code} 低于已发布的 {previous}。版本号只能前进："
            "重发一个已经用过的号会让全球用户的 checksum 校验失败。"
        )

    print(
        f"版本一致性通过：{code}（CHANGELOG {date}，生成物 {generated}，"
        f"模块主版本 v{module_major()}，已发布最新 {previous or '无'}，"
        f"{ldflags} 个 -X 目标全部指向 {BUILDINFO_SOURCE}，"
        f"goreleaser 钉在 {goreleaser}）。"
    )

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ReleaseError, VersionError, ChangesetError) as error:
        print(f"版本一致性检查失败：{error}", file=sys.stderr)
        raise SystemExit(1) from error
