#!/usr/bin/env python3
"""确认每个生成包（有 tsq.json 的包：示例模型和集成测试夹具）的生成物就是当前源码此刻会产出的东西。

`git diff --exit-code` 不能用来判断这件事：一波变更本来就可能
合法地改动生成物，而它们在提交之前一直是未提交状态——那道门会对每一波正当改动都失败。

判据只能是"拿当前源码重新渲染一遍，看结果一不一样"。`tsq gen --check` 正是为此存在：
它在内存里渲染并与磁盘比对，不落盘。它失败意味着两件事之一——有人手改了 `*.tsq.go`，
或者改完模板/解析器/示例结构体忘了跑 `make examples`。两种情况的修法都是 `make examples`
然后把结果一起提交。

注意生成文件头带着 TSQ 版本号（`// Code generated by tsq-vX.Y.Z.`），所以**改了
internal/buildinfo 的版本号也必须重新生成示例**，否则这道门会失败。发版流程依赖这
一点来保证 tag 和生成物是一致的。
"""

from __future__ import annotations

import subprocess
import sys
from typing import Final

from changeset import PROJECT_ROOT, ChangesetError, git_output

def generated_packages() -> list[str]:
    """有 tsq.json 的目录就是生成包；Makefile 的 GENERATED_PACKAGES 用同一个判据。"""
    skip = {"bin", "dist", ".git"}
    found = [
        path.parent.relative_to(PROJECT_ROOT).as_posix()
        for path in PROJECT_ROOT.rglob("tsq.json")
        if not skip.intersection(path.relative_to(PROJECT_ROOT).parts)
    ]

    return sorted(found)


# 必须和 `make examples` 用同一个二进制：`bin/tsq` 带着 git describe 注入的版本号，
# 用它比对会把"工作区脏"读成"生成物过期"。见 Makefile 的 build-gen。
GENERATOR_BINARY: Final = "tsq-gen"


class GeneratedError(RuntimeError):
    """生成物与源码脱节时抛出。"""


def module_path() -> str:
    for line in (PROJECT_ROOT / "go.mod").read_text(encoding="utf-8").splitlines():
        fields = line.strip().split()
        if len(fields) == 2 and fields[0] == "module":
            return fields[1]

    raise GeneratedError("go.mod 里没有 module 指令")


def run(command: list[str]) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        command, cwd=PROJECT_ROOT, check=False, capture_output=True
    )


def main() -> int:
    built = run(["make", "--no-print-directory", "build-gen"])
    if built.returncode != 0:
        detail = built.stderr.decode("utf-8", errors="replace").strip()
        raise GeneratedError(f"构建 tsq 生成器失败：\n{detail}")

    failed = False
    for relative in generated_packages():
        package = f"{module_path()}/{relative}"
        checked = run([f"./bin/{GENERATOR_BINARY}", "gen", "--check", package])
        output = (checked.stdout + checked.stderr).decode("utf-8", errors="replace").strip()
        if checked.returncode == 0:
            print(f"生成物检查通过：{relative} 就是当前源码的输出。")
            continue

        failed = True
        print(f"{relative} 的生成物与源码脱节：\n{output}")

    if failed:
        print(
            "\n跑 `make examples` 重新生成，然后 `make examples-run` 确认示例仍可运行，"
            "把生成结果一起提交。如果你是手改了 *.tsq.go，把改动挪回结构体、模板或解析器里"
            "——生成文件不是源码。"
        )

        return 1

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (GeneratedError, ChangesetError) as error:
        print(f"生成物检查失败：{error}", file=sys.stderr)
        raise SystemExit(1) from error
