-- Code generated by tsq-v4.10.0. DO NOT EDIT.

-- Dialect: mysql

-- Table: categories

CREATE TABLE IF NOT EXISTS `categories` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(64) NOT NULL,
    `parent_id` BIGINT
);

ALTER TABLE `categories` ADD UNIQUE INDEX `ux_categories_name`(`name`);


-- Table: customers

CREATE TABLE IF NOT EXISTS `customers` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    `email` VARCHAR(128) NOT NULL,
    `level` VARCHAR(16) DEFAULT 'regular',
    `name` VARCHAR(64) NOT NULL,
    `phone` VARCHAR(32)
);

ALTER TABLE `customers` ADD UNIQUE INDEX `ux_customers_email`(`email`);


-- Table: order_items

CREATE TABLE IF NOT EXISTS `order_items` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `line_total_cents` BIGINT GENERATED ALWAYS AS (quantity * unit_price_cents) STORED,
    `order_id` BIGINT NOT NULL,
    `product_id` BIGINT NOT NULL,
    `quantity` BIGINT NOT NULL,
    `unit_price_cents` BIGINT NOT NULL
);

ALTER TABLE `order_items` ADD INDEX `idx_order_items_product_id`(`product_id`);

ALTER TABLE `order_items` ADD UNIQUE INDEX `ux_order_items_order_id_product_id`(`order_id`, `product_id`);


-- Table: orders

CREATE TABLE IF NOT EXISTS `orders` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    `updated_at` DATETIME(6) NOT NULL,
    `version` BIGINT NOT NULL DEFAULT 1,
    `customer_id` BIGINT NOT NULL,
    `note` VARCHAR(255),
    `status` VARCHAR(16) NOT NULL,
    `total_cents` BIGINT NOT NULL
);

ALTER TABLE `orders` ADD INDEX `idx_orders_customer_id_status`(`customer_id`, `status`);


-- Table: products

CREATE TABLE IF NOT EXISTS `products` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    `updated_at` DATETIME(6) NOT NULL,
    `deleted_at` BIGINT NOT NULL DEFAULT 0,
    `version` BIGINT NOT NULL DEFAULT 1,
    `category_id` BIGINT NOT NULL,
    `description` VARCHAR(512) NOT NULL,
    `name` VARCHAR(128) NOT NULL,
    `price_cents` BIGINT NOT NULL,
    `sku` VARCHAR(32) NOT NULL,
    `status` VARCHAR(16) NOT NULL,
    `stock` BIGINT NOT NULL
);

ALTER TABLE `products` ADD FULLTEXT INDEX `ft_products_name_description`(`name`, `description`);

ALTER TABLE `products` ADD INDEX `idx_products_category_id`(`deleted_at`, `category_id`);

ALTER TABLE `products` ADD UNIQUE INDEX `ux_products_sku`(`deleted_at`, `sku`);
