// Code generated by tsq-v5.0.0. DO NOT EDIT.

package shop

import (
	"context"
	tsqtime "time"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// OrderTable is the orders table: the descriptor of Order rows, with one field
// per column.
type OrderTable struct {
	*tsq.TableOf[Order, int64]

	ID         tsq.Column[Order, int64]
	CustomerID tsq.Column[Order, int64]
	Status     tsq.Column[Order, OrderStatus]
	TotalCents tsq.Column[Order, int64]
	Note       tsq.NullColumn[Order, string]
	CreatedAt  tsq.Column[Order, tsqtime.Time]
	UpdatedAt  tsq.Column[Order, tsqtime.Time]
	Version    tsq.Column[Order, int64]
}

// TableOrder is the orders table.
var TableOrder = newOrderTable()

// newOrderTable declares the table, its columns, then its definition, so that
// anything naming TableOrder is initialized after the table is complete.
func newOrderTable() OrderTable {
	t := tsq.NewTable[Order, int64]("orders")
	c := OrderTable{
		TableOf:    t,
		ID:         tsq.NewColumn(t, "id", "id", func(r *Order) *int64 { return &r.ID }),
		CustomerID: tsq.NewColumn(t, "customer_id", "customer_id", func(r *Order) *int64 { return &r.CustomerID }),
		Status:     tsq.NewColumn(t, "status", "status", func(r *Order) *OrderStatus { return &r.Status }),
		TotalCents: tsq.NewColumn(t, "total_cents", "total_cents", func(r *Order) *int64 { return &r.TotalCents }),
		Note:       tsq.NewNullColumn[string](t, "note", "note", func(r *Order) **string { return &r.Note }),
		CreatedAt:  tsq.NewColumn(t, "created_at", "created_at", func(r *Order) *tsqtime.Time { return &r.CreatedAt }),
		UpdatedAt:  tsq.NewColumn(t, "updated_at", "updated_at", func(r *Order) *tsqtime.Time { return &r.UpdatedAt }),
		Version:    tsq.NewColumn(t, "version", "version", func(r *Order) *int64 { return &r.Version }),
	}

	t.Define(tsq.TableSpec[Order, int64]{
		Columns: []tsq.BoundColumn[Order]{
			c.ID,
			c.CustomerID,
			c.Status,
			c.TotalCents,
			c.Note,
			c.CreatedAt,
			c.UpdatedAt,
			c.Version,
		},
		PrimaryKey:    c.ID,
		AutoIncrement: true,
		Version:       c.Version,
		CreatedAt:     c.CreatedAt,
		UpdatedAt:     c.UpdatedAt,
		ColumnSpecs: []tsqdialect.ColumnSpec{
			{
				Name: "id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindInt,
					Bits: 64,
				},
				PrimaryKey:    true,
				AutoIncrement: true,
			},
			{
				Name: "created_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindTime,
				},
				Default: "CURRENT_TIMESTAMP",
			},
			{
				Name: "updated_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindTime,
				},
			},
			{
				Name: "version",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindInt,
					Bits: 64,
				},
				Default: "1",
			},
			{
				Name: "customer_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindInt,
					Bits: 64,
				},
			},
			{
				Name: "note",
				Type: tsqdialect.ColumnType{
					Kind:     tsqdialect.ColumnKindString,
					Nullable: true,
					Size:     255,
				},
			},
			{
				Name: "status",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindString,
					Size: 16,
				},
			},
			{
				Name: "total_cents",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.ColumnKindInt,
					Bits: 64,
				},
			},
		},
		Indexes: []tsq.IndexSpec{
			{Name: "idx_orders_customer_id_status", Columns: []string{"customer_id", "status"}},
		},
	})

	return c
}

// As returns the table under alias, with every column bound to the alias, for
// joining the table more than once.
func (t OrderTable) As(alias string) OrderTable {
	a := t.TableOf.As(alias)

	return OrderTable{
		TableOf:    a,
		ID:         t.ID.Rebind(a),
		CustomerID: t.CustomerID.Rebind(a),
		Status:     t.Status.Rebind(a),
		TotalCents: t.TotalCents.Rebind(a),
		Note:       tsq.RebindNull(t.Note, a),
		CreatedAt:  t.CreatedAt.Rebind(a),
		UpdatedAt:  t.UpdatedAt.Rebind(a),
		Version:    t.Version.Rebind(a),
	}
}

// Insert inserts the row; see tsq.TableOf.Insert.
func (o *Order) Insert(ctx context.Context, db tsq.Executor) error {
	return TableOrder.Insert(ctx, db, o)
}

// Update writes the row, or only cols when given; see tsq.TableOf.Update.
func (o *Order) Update(ctx context.Context, db tsq.Executor, cols ...tsq.BoundColumn[Order]) error {
	return TableOrder.Update(ctx, db, o, cols...)
}

// HardDelete removes the row from the table.
func (o *Order) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableOrder.HardDelete(ctx, db, o)
}
