// Code generated by tsq-v4.10.0. DO NOT EDIT.

package shop

import (
	"context"
	tsqtime "time"

	"github.com/tmoeish/tsq/v5"
	tsqdialect "github.com/tmoeish/tsq/v5/dialect"
)

// ProductTable is the products table: the descriptor of Product rows, with one field
// per column.
type ProductTable struct {
	*tsq.SoftDeleteTableOf[Product, int64]

	ID          tsq.Column[Product, int64]
	CategoryID  tsq.Column[Product, int64]
	SKU         tsq.Column[Product, string]
	Name        tsq.Column[Product, string]
	Description tsq.Column[Product, string]
	PriceCents  tsq.Column[Product, int64]
	Stock       tsq.Column[Product, int64]
	Status      tsq.Column[Product, ProductStatus]
	CreatedAt   tsq.Column[Product, tsqtime.Time]
	UpdatedAt   tsq.Column[Product, tsqtime.Time]
	DeletedAt   tsq.Column[Product, int64]
	Version     tsq.Column[Product, int64]
}

// TableProduct is the products table.
var TableProduct = newProductTable()

// newProductTable declares the table, its columns, then its definition, so that
// anything naming TableProduct is initialized after the table is complete.
func newProductTable() ProductTable {
	t := tsq.NewSoftDeleteTable[Product, int64]("products")
	c := ProductTable{
		SoftDeleteTableOf: t,
		ID:                tsq.NewColumn(t.TableOf, "id", "id", func(r *Product) *int64 { return &r.ID }),
		CategoryID:        tsq.NewColumn(t.TableOf, "category_id", "category_id", func(r *Product) *int64 { return &r.CategoryID }),
		SKU:               tsq.NewColumn(t.TableOf, "sku", "sku", func(r *Product) *string { return &r.SKU }),
		Name:              tsq.NewColumn(t.TableOf, "name", "name", func(r *Product) *string { return &r.Name }),
		Description:       tsq.NewColumn(t.TableOf, "description", "description", func(r *Product) *string { return &r.Description }),
		PriceCents:        tsq.NewColumn(t.TableOf, "price_cents", "price_cents", func(r *Product) *int64 { return &r.PriceCents }),
		Stock:             tsq.NewColumn(t.TableOf, "stock", "stock", func(r *Product) *int64 { return &r.Stock }),
		Status:            tsq.NewColumn(t.TableOf, "status", "status", func(r *Product) *ProductStatus { return &r.Status }),
		CreatedAt:         tsq.NewColumn(t.TableOf, "created_at", "created_at", func(r *Product) *tsqtime.Time { return &r.CreatedAt }),
		UpdatedAt:         tsq.NewColumn(t.TableOf, "updated_at", "updated_at", func(r *Product) *tsqtime.Time { return &r.UpdatedAt }),
		DeletedAt:         tsq.NewColumn(t.TableOf, "deleted_at", "deleted_at", func(r *Product) *int64 { return &r.DeletedAt }),
		Version:           tsq.NewColumn(t.TableOf, "version", "version", func(r *Product) *int64 { return &r.Version }),
	}

	t.Define(tsq.TableSpec[Product, int64]{
		Columns: []tsq.BoundColumn[Product]{
			c.ID,
			c.CategoryID,
			c.SKU,
			c.Name,
			c.Description,
			c.PriceCents,
			c.Stock,
			c.Status,
			c.CreatedAt,
			c.UpdatedAt,
			c.DeletedAt,
			c.Version,
		},
		PrimaryKey:    c.ID,
		AutoIncrement: true,
		Version:       c.Version,
		CreatedAt:     c.CreatedAt,
		UpdatedAt:     c.UpdatedAt,
		Search: []tsq.SearchColumn{
			tsq.Searchable(c.Name),
			tsq.Searchable(c.Description),
		},
		ColumnSpecs: []tsqdialect.ColumnSpec{
			{
				Name: "id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				PrimaryKey:    true,
				AutoIncrement: true,
			},
			{
				Name: "created_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindTime,
				},
				Default: "CURRENT_TIMESTAMP",
			},
			{
				Name: "updated_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindTime,
				},
			},
			{
				Name: "deleted_at",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				Default: "0",
			},
			{
				Name: "version",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
				Default: "1",
			},
			{
				Name: "category_id",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "description",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 512,
				},
			},
			{
				Name: "name",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 128,
				},
			},
			{
				Name: "price_cents",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
			{
				Name: "sku",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 32,
				},
			},
			{
				Name: "status",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindString,
					Size: 16,
				},
			},
			{
				Name: "stock",
				Type: tsqdialect.ColumnType{
					Kind: tsqdialect.KindInt,
					Bits: 64,
				},
			},
		},
		Indexes: []tsq.IndexSpec{
			{Name: "ux_products_sku", Unique: true, Columns: []string{"deleted_at", "sku"}},
			{Name: "idx_products_category_id", Columns: []string{"deleted_at", "category_id"}},
			{Name: "ft_products_name_description", FullText: true, Columns: []string{"name", "description"}},
		},
	}, c.DeletedAt)

	return c
}

// As returns the table under alias, with every column bound to the alias, for
// joining the table more than once.
func (t ProductTable) As(alias string) ProductTable {
	a := t.SoftDeleteTableOf.As(alias)

	return ProductTable{
		SoftDeleteTableOf: a,
		ID:                t.ID.WithTable(a),
		CategoryID:        t.CategoryID.WithTable(a),
		SKU:               t.SKU.WithTable(a),
		Name:              t.Name.WithTable(a),
		Description:       t.Description.WithTable(a),
		PriceCents:        t.PriceCents.WithTable(a),
		Stock:             t.Stock.WithTable(a),
		Status:            t.Status.WithTable(a),
		CreatedAt:         t.CreatedAt.WithTable(a),
		UpdatedAt:         t.UpdatedAt.WithTable(a),
		DeletedAt:         t.DeletedAt.WithTable(a),
		Version:           t.Version.WithTable(a),
	}
}

// ProductTableWithDeleted is ProductTable without its live-row filter: the same columns,
// and no lookups by unique index. The unique indexes of a soft-delete table include
// deleted_at, so a value is unique only among live rows; read deleted rows
// by primary key.
type ProductTableWithDeleted ProductTable

// WithDeleted returns the table without its live-row filter; see
// tsq.SoftDeleteTableOf.WithDeleted.
func (t ProductTable) WithDeleted() ProductTableWithDeleted {
	t.SoftDeleteTableOf = t.SoftDeleteTableOf.WithDeleted()

	return ProductTableWithDeleted(t)
}

// As returns the table under alias, with every column bound to the alias.
func (t ProductTableWithDeleted) As(alias string) ProductTableWithDeleted {
	return ProductTableWithDeleted(ProductTable(t).As(alias))
}

// FullTextNameAndDescription is the full-text index ft_products_name_description; search it with
// tsq.Matches.
func (t ProductTableWithDeleted) FullTextNameAndDescription() tsq.FullTextIndex {
	return t.FullText("ft_products_name_description")
}

// FullTextNameAndDescription is the full-text index ft_products_name_description; search it with
// tsq.Matches.
func (t ProductTable) FullTextNameAndDescription() tsq.FullTextIndex {
	return t.FullText("ft_products_name_description")
}

// GetBySKU reads the Product matching unique index ux_products_sku, and fails with an
// error wrapping sql.ErrNoRows when there is none.
func (t ProductTable) GetBySKU(
	ctx context.Context,
	db tsq.Executor,
	sku string,
) (*Product, error) {
	return t.GetBy(ctx, db, t.SKU, sku)
}

// FindBySKU is GetBySKU that returns nil, nil when there is no such row.
func (t ProductTable) FindBySKU(
	ctx context.Context,
	db tsq.Executor,
	sku string,
) (*Product, error) {
	return t.FindBy(ctx, db, t.SKU, sku)
}

// FetchBySKU reads the Product rows matching unique index ux_products_sku, one per
// SKU value, in the order given; see tsq.TableOf.FetchBy.
func (t ProductTable) FetchBySKU(
	ctx context.Context,
	db tsq.Executor,
	skus ...string,
) ([]*Product, error) {
	return t.FetchBy(ctx, db, t.SKU, skus)
}

// Insert inserts the row; see tsq.TableOf.Insert.
func (p *Product) Insert(ctx context.Context, db tsq.Executor) error {
	return TableProduct.Insert(ctx, db, p)
}

// Update writes the row, or only cols when given; see tsq.TableOf.Update.
func (p *Product) Update(ctx context.Context, db tsq.Executor, cols ...tsq.BoundColumn[Product]) error {
	return TableProduct.Update(ctx, db, p, cols...)
}

// Delete soft-deletes the row by stamping DeletedAt; queries naming the
// table leave it out from then on. See tsq.SoftDeleteTableOf.Delete.
func (p *Product) Delete(ctx context.Context, db tsq.Executor) error {
	return TableProduct.Delete(ctx, db, p)
}

// HardDelete removes the row from the table. Unlike a soft delete, it cannot be undone.
func (p *Product) HardDelete(ctx context.Context, db tsq.Executor) error {
	return TableProduct.HardDelete(ctx, db, p)
}

// Restore clears the row's tombstone; see tsq.SoftDeleteTableOf.Restore.
func (p *Product) Restore(ctx context.Context, db tsq.Executor) error {
	return TableProduct.Restore(ctx, db, p)
}

// IsDeleted reports whether the row, as loaded, is soft-deleted.
func (p *Product) IsDeleted() bool {
	return p.DeletedAt != 0
}
