-- Code generated by tsq-v4.10.0. DO NOT EDIT.

-- Dialect: sqlite

-- Table: categories

CREATE TABLE IF NOT EXISTS "categories" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" VARCHAR(64) NOT NULL,
    "parent_id" INTEGER
);

CREATE UNIQUE INDEX "ux_categories_name" ON "categories"("name");


-- Table: customers

CREATE TABLE IF NOT EXISTS "customers" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "email" VARCHAR(128) NOT NULL,
    "level" VARCHAR(16) DEFAULT 'regular',
    "name" VARCHAR(64) NOT NULL,
    "phone" VARCHAR(32)
);

CREATE UNIQUE INDEX "ux_customers_email" ON "customers"("email");


-- Table: order_items

CREATE TABLE IF NOT EXISTS "order_items" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "line_total_cents" INTEGER GENERATED ALWAYS AS (quantity * unit_price_cents) STORED,
    "order_id" INTEGER NOT NULL,
    "product_id" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price_cents" INTEGER NOT NULL
);

CREATE INDEX "idx_order_items_product_id" ON "order_items"("product_id");

CREATE UNIQUE INDEX "ux_order_items_order_id_product_id" ON "order_items"("order_id", "product_id");


-- Table: orders

CREATE TABLE IF NOT EXISTS "orders" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "customer_id" INTEGER NOT NULL,
    "note" VARCHAR(255),
    "status" VARCHAR(16) NOT NULL,
    "total_cents" INTEGER NOT NULL
);

CREATE INDEX "idx_orders_customer_id_status" ON "orders"("customer_id", "status");


-- Table: products

CREATE TABLE IF NOT EXISTS "products" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,
    "deleted_at" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 1,
    "category_id" INTEGER NOT NULL,
    "description" VARCHAR(512) NOT NULL,
    "name" VARCHAR(128) NOT NULL,
    "price_cents" INTEGER NOT NULL,
    "sku" VARCHAR(32) NOT NULL,
    "status" VARCHAR(16) NOT NULL,
    "stock" INTEGER NOT NULL
);

CREATE INDEX "idx_products_category_id" ON "products"("deleted_at", "category_id");

CREATE UNIQUE INDEX "ux_products_sku" ON "products"("deleted_at", "sku");
