// Code generated by tsq-v3.7.1. DO NOT EDIT.

package database

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableOrder implements the tsq.Table interface for Order.
var TableOrder tsq.Table = Order{}

// Column definitions for Order table.
var (
	Order_Amount    = tsq.NewCol[int64](TableOrder, "amount", "Amount", func(t any) any { return &t.(*Order).Amount })
	Order_CreatedAt = tsq.NewCol[tsqtime.Time](TableOrder, "created_at", "created_at", func(t any) any { return &t.(*Order).CreatedAt })
	Order_DeletedAt = tsq.NewCol[int64](TableOrder, "deleted_at", "deleted_at", func(t any) any { return &t.(*Order).DeletedAt })
	Order_ItemID    = tsq.NewCol[int64](TableOrder, "item_id", "ItemID", func(t any) any { return &t.(*Order).ItemID })
	Order_Price     = tsq.NewCol[int64](TableOrder, "price", "Price", func(t any) any { return &t.(*Order).Price })
	Order_Status    = tsq.NewCol[OrderStatus](TableOrder, "status", "Status", func(t any) any { return &t.(*Order).Status })
	Order_UID       = tsq.NewCol[int64](TableOrder, "uid", "uid", func(t any) any { return &t.(*Order).UID })
	Order_UpdatedAt = tsq.NewCol[null.Time](TableOrder, "updated_at", "updated_at", func(t any) any { return &t.(*Order).UpdatedAt })
	Order_UserID    = tsq.NewCol[int64](TableOrder, "user_id", "UserID", func(t any) any { return &t.(*Order).UserID })
	Order_Version   = tsq.NewCol[int64](TableOrder, "version", "version", func(t any) any { return &t.(*Order).Version })
)

// TableOrderCols is the list of columns for Order table.
var TableOrderCols = []tsq.Column{
	Order_Amount,
	Order_CreatedAt,
	Order_DeletedAt,
	Order_ItemID,
	Order_Price,
	Order_Status,
	Order_UID,
	Order_UpdatedAt,
	Order_UserID,
	Order_Version,
}

// Table returns the database table name for Order.
func (o Order) Table() string { return "order" }

// KwList returns columns that support keyword search for Order.
func (o Order) KwList() []tsq.Column {
	return []tsq.Column{}
}

// Cols returns all generated columns for Order.
func (o Order) Cols() []tsq.Column {
	return TableOrderCols
}

func init() {
	tsq.RegisterTable(
		TableOrder,
		func(db *tsq.DbMap) {
			db.AddTableWithName(TableOrder, "order").SetKeys(true, "UID").SetVersionCol("Version")
		},
		func(db *tsq.DbMap) error {
			// Upsert non-unique indexes.
			if err := tsq.UpsertIndex(db, "order", false, "idx_item", []string{"deleted_at", "item_id"}); err != nil {
				return errors.Annotate(err, "upsert idx_item@order")
			}
			if err := tsq.UpsertIndex(db, "order", false, "idx_order_user_id_item_id", []string{"deleted_at", "user_id", "item_id"}); err != nil {
				return errors.Annotate(err, "upsert idx_order_user_id_item_id@order")
			}

			return nil
		},
	)
}

// Active returns true if the Order record is not soft-deleted.
func (o *Order) Active() bool {
	return o.DeletedAt == 0
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getOrderByUIDQuery *tsq.Query

func init() {
	var err error
	getOrderByUIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(Order_UID.EQVar()).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getOrderByUIDQuery"))
	}
}

// GetOrderByUID retrieves a Order record by its UID.
// Returns (nil, nil) if the record is not found.
func GetOrderByUID(
	ctx context.Context,
	db tsq.SqlExecutor,
	uID int64,
) (*Order, error) {
	row := &Order{}
	err := getOrderByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// GetOrderByUIDOrErr retrieves a Order record by its UID.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetOrderByUIDOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	uID int64,
) (*Order, error) {
	row := &Order{}
	err := getOrderByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, errors.Trace(err)
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// ListOrderByUIDIn retrieves multiple Order records by a set of UID values.
// Records not found are silently ignored.
func ListOrderByUIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	uIDs ...int64,
) ([]*Order, error) {
	query, err := tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(Order_UID.In(uIDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	return tsq.List[Order](ctx, db, query)
}

// ListOrderByUIDInOrErr retrieves multiple Order records by a set of UID values.
// Returns an error if any of the specified records are not found.
func ListOrderByUIDInOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	uIDs ...int64,
) ([]*Order, error) {
	query, err := tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(Order_UID.In(uIDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List[Order](ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(uIDs, list, func(row *Order) int64 {
		return row.UID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Order(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// Query Active Records by Primary Key
// =============================================================================
var getActiveOrderByUIDQuery *tsq.Query

func init() {
	var err error
	getActiveOrderByUIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UID.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getActiveOrderByUIDQuery"))
	}
}

// GetActiveOrderByUID retrieves an active (non-deleted) Order record by its UID.
// Returns (nil, nil) if the record is not found or has been soft-deleted.
func GetActiveOrderByUID(
	ctx context.Context,
	db tsq.SqlExecutor,
	uID int64,
) (*Order, error) {
	row := &Order{}
	err := getActiveOrderByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// GetActiveOrderByUIDOrErr retrieves an active (non-deleted) Order record by its UID.
// Returns (nil, database/sql.ErrNoRows) if the record is not found or has been soft-deleted.
func GetActiveOrderByUIDOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	uID int64,
) (*Order, error) {
	row := &Order{}
	err := getActiveOrderByUIDQuery.Load(ctx, db, row, uID)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, errors.Trace(err)
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// ListActiveOrderByUIDIn retrieves multiple active (non-deleted) Order records by a set of UID values.
// Records not found or soft-deleted are silently ignored.
func ListActiveOrderByUIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	uIDs ...int64,
) ([]*Order, error) {
	query, err := tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UID.In(uIDs...),
		).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}
	list, err := tsq.List[Order](ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return list, nil
}

// ListActiveOrderByUIDInOrErr retrieves multiple active (non-deleted) Order records by a set of UID values.
// Returns an error if any of the specified active records are not found.
func ListActiveOrderByUIDInOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	uIDs ...int64,
) ([]*Order, error) {
	query, err := tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UID.In(uIDs...),
		).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	var list []*Order
	list, err = tsq.List[Order](ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}
	match := tsq.MatchByInputOrder(uIDs, list, func(row *Order) int64 {
		return row.UID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Order(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Order record into the database.
// Automatically sets creation and modification timestamps if configured.
func (o *Order) Insert(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	o.CreatedAt = tsqtime.Now()
	o.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "insert Order: %s", tsq.CompactJSON(o))
	}

	return nil
}

// Update updates an existing Order record in the database.
// Automatically updates the modification timestamp if configured.
func (o *Order) Update(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	o.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Update(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "update Order: %s", tsq.CompactJSON(o))
	}

	return nil
}

// Delete permanently removes a Order record from the database.
func (o *Order) Delete(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Delete(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "delete Order: %s", tsq.CompactJSON(o))
	}

	return nil
}

// SoftDelete marks a Order record as deleted without removing it from the database.
// If dt is set, uses the provided tombstone value; otherwise uses the current time.
func (o *Order) SoftDelete(
	ctx context.Context,
	db tsq.SqlExecutor,
	dt int64,
) error {
	if dt != 0 {
		o.DeletedAt = dt
	} else {
		o.DeletedAt = tsqtime.Now().UnixNano()
	}
	o.UpdatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Update(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "soft-delete Order: %s", tsq.CompactJSON(o))
	}

	return nil
}

// ListOrderByQuery executes a custom query to retrieve Order records.
func ListOrderByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	qb *tsq.Query,
	args ...any,
) ([]*Order, error) {
	return tsq.List[Order](ctx, tx, qb, args...)
}

// PageOrderByQuery executes a custom query with pagination to retrieve Order records.
func PageOrderByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
	qb *tsq.Query,
	args ...any,
) (*tsq.PageResp[Order], error) {
	return tsq.Page[Order](ctx, tx, page, qb, args...)
}

// =============================================================================
// List All Records
// =============================================================================
// listOrderQuery is the base query for retrieving all Order records.
var listOrderQuery *tsq.Query

func init() {
	var err error
	listOrderQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listOrderQuery"))
	}
}

// CountOrder returns the total count of Order records.
func CountOrder(
	ctx context.Context,
	tx tsq.SqlExecutor,
) (int64, error) {
	return listOrderQuery.Count64(ctx, tx)
}

// ListOrder retrieves all Order records from the database.
func ListOrder(
	ctx context.Context,
	tx tsq.SqlExecutor,
) ([]*Order, error) {
	return tsq.List[Order](ctx, tx, listOrderQuery)
}

// PageOrder retrieves Order records with pagination support.
func PageOrder(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Order], error) {
	return tsq.Page[Order](ctx, tx, page, listOrderQuery)
}

// =============================================================================
// List Active Records
// =============================================================================
// listActiveOrderQuery is the base query for retrieving active (non-deleted) Order records.
var listActiveOrderQuery *tsq.Query

func init() {
	var err error
	listActiveOrderQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(Order_DeletedAt.EQ(0)).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveOrderQuery"))
	}
}

// CountActiveOrder returns the count of active (non-deleted) Order records.
func CountActiveOrder(
	ctx context.Context,
	tx tsq.SqlExecutor,
) (int64, error) {
	return listActiveOrderQuery.Count64(ctx, tx)
}

// ListActiveOrder retrieves all active (non-deleted) Order records.
func ListActiveOrder(
	ctx context.Context,
	tx tsq.SqlExecutor,
) ([]*Order, error) {
	return tsq.List[Order](ctx, tx, listActiveOrderQuery)
}

// PageActiveOrder retrieves active (non-deleted) Order records with pagination support.
func PageActiveOrder(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Order], error) {
	return tsq.Page[Order](ctx, tx, page, listActiveOrderQuery)
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
// =============================================================================
// Query Active Records by Unique Indexes
// =============================================================================
// =============================================================================
// Query by Indexes
// =============================================================================
// ListOrderByItemIDQuery queries Order records by index idx_item.
var ListOrderByItemIDQuery *tsq.Query

func init() {
	var err error
	ListOrderByItemIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_ItemID.EQVar(),
		).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListOrderByItemIDQuery"))
	}
}

// CountOrderByItemID returns the count of Order records matching index idx_item.
func CountOrderByItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	itemID int64,
) (int64, error) {
	query := ListOrderByItemIDQuery

	rs, err := query.Count64(ctx, db,
		itemID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_item")
	}
	return rs, nil
}

// ListOrderByItemID retrieves Order records by index idx_item.
func ListOrderByItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	itemID int64,
) ([]*Order, error) {
	query := ListOrderByItemIDQuery

	data, err := tsq.List[Order](ctx, db, query,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_item")
	}
	return data, nil
}

// PageOrderByItemID retrieves Order records by index idx_item with pagination support.
func PageOrderByItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	page *tsq.PageReq,
	itemID int64,
) (*tsq.PageResp[Order], error) {
	query := ListOrderByItemIDQuery

	rs, err := tsq.Page[Order](ctx, db, page, query,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_item")
	}
	return rs, nil
}

// ListOrderByItemIDInQuery queries Order records by index idx_item using a cached IN-clause query.
var ListOrderByItemIDInQuery *tsq.Query

func init() {
	var err error
	ListOrderByItemIDInQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_ItemID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListOrderByItemIDInQuery"))
	}
}

// ListOrderByItemIDIn retrieves Order records by index ItemIDIn using IN clause for batch querying.
func ListOrderByItemIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	itemIDs ...int64,
) ([]*Order, error) {
	query := ListOrderByItemIDInQuery

	list, err := tsq.List[Order](ctx, db, query,
		itemIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_item")
	}
	return list, nil
}

// ListOrderByUserIDQuery queries Order records by index idx_order_user_id_item_id.
var ListOrderByUserIDQuery *tsq.Query

func init() {
	var err error
	ListOrderByUserIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_UserID.EQVar(),
		).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListOrderByUserIDQuery"))
	}
}

// CountOrderByUserID returns the count of Order records matching index idx_order_user_id_item_id.
func CountOrderByUserID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
) (int64, error) {
	query := ListOrderByUserIDQuery

	rs, err := query.Count64(ctx, db,
		userID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListOrderByUserID retrieves Order records by index idx_order_user_id_item_id.
func ListOrderByUserID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
) ([]*Order, error) {
	query := ListOrderByUserIDQuery

	data, err := tsq.List[Order](ctx, db, query,
		userID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return data, nil
}

// PageOrderByUserID retrieves Order records by index idx_order_user_id_item_id with pagination support.
func PageOrderByUserID(
	ctx context.Context,
	db tsq.SqlExecutor,
	page *tsq.PageReq,
	userID int64,
) (*tsq.PageResp[Order], error) {
	query := ListOrderByUserIDQuery

	rs, err := tsq.Page[Order](ctx, db, page, query,
		userID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListOrderByUserIDAndItemIDQuery queries Order records by index idx_order_user_id_item_id.
var ListOrderByUserIDAndItemIDQuery *tsq.Query

func init() {
	var err error
	ListOrderByUserIDAndItemIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_UserID.EQVar(),
			Order_ItemID.EQVar(),
		).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListOrderByUserIDAndItemIDQuery"))
	}
}

// CountOrderByUserIDAndItemID returns the count of Order records matching index idx_order_user_id_item_id.
func CountOrderByUserIDAndItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
	itemID int64,
) (int64, error) {
	query := ListOrderByUserIDAndItemIDQuery

	rs, err := query.Count64(ctx, db,
		userID,
		itemID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListOrderByUserIDAndItemID retrieves Order records by index idx_order_user_id_item_id.
func ListOrderByUserIDAndItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
	itemID int64,
) ([]*Order, error) {
	query := ListOrderByUserIDAndItemIDQuery

	data, err := tsq.List[Order](ctx, db, query,
		userID,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return data, nil
}

// PageOrderByUserIDAndItemID retrieves Order records by index idx_order_user_id_item_id with pagination support.
func PageOrderByUserIDAndItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	page *tsq.PageReq,
	userID int64,
	itemID int64,
) (*tsq.PageResp[Order], error) {
	query := ListOrderByUserIDAndItemIDQuery

	rs, err := tsq.Page[Order](ctx, db, page, query,
		userID,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListOrderByUserIDAndItemIDInQuery queries Order records by index idx_order_user_id_item_id using a cached IN-clause query.
var ListOrderByUserIDAndItemIDInQuery *tsq.Query

func init() {
	var err error
	ListOrderByUserIDAndItemIDInQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_UserID.EQVar(),
			Order_ItemID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListOrderByUserIDAndItemIDInQuery"))
	}
}

// ListOrderByUserIDAndItemIDIn retrieves Order records by index UserIDAndItemIDIn using IN clause for batch querying.
func ListOrderByUserIDAndItemIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
	itemIDs ...int64,
) ([]*Order, error) {
	query := ListOrderByUserIDAndItemIDInQuery

	list, err := tsq.List[Order](ctx, db, query,
		userID,
		itemIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return list, nil
}

// ListOrderByUserIDInQuery queries Order records by index idx_order_user_id_item_id using a cached IN-clause query.
var ListOrderByUserIDInQuery *tsq.Query

func init() {
	var err error
	ListOrderByUserIDInQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_UserID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListOrderByUserIDInQuery"))
	}
}

// ListOrderByUserIDIn retrieves Order records by index UserIDIn using IN clause for batch querying.
func ListOrderByUserIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	userIDs ...int64,
) ([]*Order, error) {
	query := ListOrderByUserIDInQuery

	list, err := tsq.List[Order](ctx, db, query,
		userIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return list, nil
}

// =============================================================================
// Query Active Records by Indexes
// =============================================================================
// listActiveOrderByItemIDQuery queries active (non-deleted) Order records by index idx_item.
var listActiveOrderByItemIDQuery *tsq.Query

func init() {
	var err error
	listActiveOrderByItemIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_ItemID.EQVar(),
		).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveOrderByItemIDQuery"))
	}
}

// CountActiveOrderByItemID returns the count of active (non-deleted) Order records matching index idx_item.
func CountActiveOrderByItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	itemID int64,
) (int64, error) {
	query := listActiveOrderByItemIDQuery

	rs, err := query.Count64(ctx, db,
		itemID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_item")
	}
	return rs, nil
}

// ListActiveOrderByItemID retrieves active (non-deleted) Order records by index idx_item.
func ListActiveOrderByItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	itemID int64,
) ([]*Order, error) {
	query := listActiveOrderByItemIDQuery

	data, err := tsq.List[Order](ctx, db, query,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_item")
	}
	return data, nil
}

// PageActiveOrderByItemID retrieves active (non-deleted) Order records by index idx_item with pagination support.
func PageActiveOrderByItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	page *tsq.PageReq,
	itemID int64,
) (*tsq.PageResp[Order], error) {
	query := listActiveOrderByItemIDQuery

	rs, err := tsq.Page[Order](ctx, db, page, query,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_item")
	}
	return rs, nil
}

// ListActiveOrderByItemIDInQuery queries active (non-deleted) Order records by index idx_item using a cached IN-clause query.
var ListActiveOrderByItemIDInQuery *tsq.Query

func init() {
	var err error
	ListActiveOrderByItemIDInQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_ItemID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveOrderByItemIDInQuery"))
	}
}

// ListActiveOrderByItemIDIn retrieves active (non-deleted) Order records by index idx_item using IN clause for batch querying.
func ListActiveOrderByItemIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	itemIDs ...int64,
) ([]*Order, error) {
	query := ListActiveOrderByItemIDInQuery
	list, err := tsq.List[Order](ctx, db, query,
		itemIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_item")
	}
	return list, nil
}

// listActiveOrderByUserIDQuery queries active (non-deleted) Order records by index idx_order_user_id_item_id.
var listActiveOrderByUserIDQuery *tsq.Query

func init() {
	var err error
	listActiveOrderByUserIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UserID.EQVar(),
		).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveOrderByUserIDQuery"))
	}
}

// CountActiveOrderByUserID returns the count of active (non-deleted) Order records matching index idx_order_user_id_item_id.
func CountActiveOrderByUserID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
) (int64, error) {
	query := listActiveOrderByUserIDQuery

	rs, err := query.Count64(ctx, db,
		userID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListActiveOrderByUserID retrieves active (non-deleted) Order records by index idx_order_user_id_item_id.
func ListActiveOrderByUserID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
) ([]*Order, error) {
	query := listActiveOrderByUserIDQuery

	data, err := tsq.List[Order](ctx, db, query,
		userID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return data, nil
}

// PageActiveOrderByUserID retrieves active (non-deleted) Order records by index idx_order_user_id_item_id with pagination support.
func PageActiveOrderByUserID(
	ctx context.Context,
	db tsq.SqlExecutor,
	page *tsq.PageReq,
	userID int64,
) (*tsq.PageResp[Order], error) {
	query := listActiveOrderByUserIDQuery

	rs, err := tsq.Page[Order](ctx, db, page, query,
		userID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// listActiveOrderByUserIDAndItemIDQuery queries active (non-deleted) Order records by index idx_order_user_id_item_id.
var listActiveOrderByUserIDAndItemIDQuery *tsq.Query

func init() {
	var err error
	listActiveOrderByUserIDAndItemIDQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UserID.EQVar(),
			Order_ItemID.EQVar(),
		).
		KwSearch(TableOrder.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listActiveOrderByUserIDAndItemIDQuery"))
	}
}

// CountActiveOrderByUserIDAndItemID returns the count of active (non-deleted) Order records matching index idx_order_user_id_item_id.
func CountActiveOrderByUserIDAndItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
	itemID int64,
) (int64, error) {
	query := listActiveOrderByUserIDAndItemIDQuery

	rs, err := query.Count64(ctx, db,
		userID,
		itemID,
	)
	if err != nil {
		return 0, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListActiveOrderByUserIDAndItemID retrieves active (non-deleted) Order records by index idx_order_user_id_item_id.
func ListActiveOrderByUserIDAndItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
	itemID int64,
) ([]*Order, error) {
	query := listActiveOrderByUserIDAndItemIDQuery

	data, err := tsq.List[Order](ctx, db, query,
		userID,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return data, nil
}

// PageActiveOrderByUserIDAndItemID retrieves active (non-deleted) Order records by index idx_order_user_id_item_id with pagination support.
func PageActiveOrderByUserIDAndItemID(
	ctx context.Context,
	db tsq.SqlExecutor,
	page *tsq.PageReq,
	userID int64,
	itemID int64,
) (*tsq.PageResp[Order], error) {
	query := listActiveOrderByUserIDAndItemIDQuery

	rs, err := tsq.Page[Order](ctx, db, page, query,
		userID,
		itemID,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return rs, nil
}

// ListActiveOrderByUserIDAndItemIDInQuery queries active (non-deleted) Order records by index idx_order_user_id_item_id using a cached IN-clause query.
var ListActiveOrderByUserIDAndItemIDInQuery *tsq.Query

func init() {
	var err error
	ListActiveOrderByUserIDAndItemIDInQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UserID.EQVar(),
			Order_ItemID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveOrderByUserIDAndItemIDInQuery"))
	}
}

// ListActiveOrderByUserIDAndItemIDIn retrieves active (non-deleted) Order records by index idx_order_user_id_item_id using IN clause for batch querying.
func ListActiveOrderByUserIDAndItemIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	userID int64,
	itemIDs ...int64,
) ([]*Order, error) {
	query := ListActiveOrderByUserIDAndItemIDInQuery
	list, err := tsq.List[Order](ctx, db, query,
		userID,
		itemIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return list, nil
}

// ListActiveOrderByUserIDInQuery queries active (non-deleted) Order records by index idx_order_user_id_item_id using a cached IN-clause query.
var ListActiveOrderByUserIDInQuery *tsq.Query

func init() {
	var err error
	ListActiveOrderByUserIDInQuery, err = tsq.
		Select(TableOrderCols...).
		From(TableOrder).
		Where(
			Order_DeletedAt.EQ(0),
			Order_UserID.InVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize ListActiveOrderByUserIDInQuery"))
	}
}

// ListActiveOrderByUserIDIn retrieves active (non-deleted) Order records by index idx_order_user_id_item_id using IN clause for batch querying.
func ListActiveOrderByUserIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	userIDs ...int64,
) ([]*Order, error) {
	query := ListActiveOrderByUserIDInQuery
	list, err := tsq.List[Order](ctx, db, query,
		userIDs,
	)
	if err != nil {
		return nil, errors.Annotate(err, "query by index idx_order_user_id_item_id")
	}
	return list, nil
}
