// Code generated by tsq-v4.0.1. DO NOT EDIT.

package database

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq/v4"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableOrg implements the tsq.Table interface for Org.
var TableOrg tsq.Table = Org{}

// TSQOwner marks Org as a TSQ owner.
func (o Org) TSQOwner() {}

// Table returns the database table name for Org.
func (o Org) Table() string { return "org" }

// Cols returns all generated columns for Org.
func (o Org) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(TableOrgCols...)
}

// KwList returns columns that support keyword search for Org.
func (o Org) KwList() []tsq.SearchColumn {
	return []tsq.SearchColumn{}
}

// PrimaryKeys returns the primary key columns for Org.
func (o Org) PrimaryKeys() []string {
	return []string{"id"}
}

// AutoIncrement reports whether Org uses an auto-increment primary key.
func (o Org) AutoIncrement() bool { return true }

// VersionColumn returns the optimistic-lock version column for Org, if any.
func (o Org) VersionColumn() string {
	return ""
}

// Column definitions for Org table.
var (
	Org_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *Org) *null.Time { return &t.CreatedAt })
	Org_ID        = tsq.NewCol("id", "id", func(t *Org) *int64 { return &t.ID })
	Org_Name      = tsq.NewCol("name", "Name", func(t *Org) *string { return &t.Name })
)

// TableOrgCols is the list of all selectable columns for Org table.
var TableOrgCols = []tsq.BoundColumn[Org]{
	Org_CreatedAt,
	Org_ID,
	Org_Name,
}

// =============================================================================
// Table Registration and Index Initialization
// =============================================================================

func init() {
	tsq.RegisterTable(
		TableOrg,
		func(db *tsq.DbMap) {
			db.AddTableWithName(TableOrg, "org").SetKeys(true, "ID")
		},
		func(db *tsq.DbMap) error {
			// Upsert unique indexes.
			if err := tsq.UpsertIndex(db, "org", true, "ux_org_name", []string{"name"}); err != nil {
				return errors.Annotate(err, "upsert ux_org_name@org")
			}
			return nil
		},
	)
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getOrgByIDQuery *tsq.Query[Org]

func init() {
	var err error
	getOrgByIDQuery, err = tsq.
		Select(TableOrgCols...).
		From(TableOrg).
		Where(Org_ID.EQVar()).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getOrgByIDQuery"))
	}
}

// GetOrgByID retrieves a Org record by its primary key.
// Returns (nil, nil) if the record is not found.
func GetOrgByID(
	ctx context.Context,
	db tsq.SqlExecutor,
	iD int64,
) (*Org, error) {
	row := &Org{}
	err := getOrgByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetOrgByIDOrErr retrieves a Org record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetOrgByIDOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	iD int64,
) (*Org, error) {
	row := &Org{}
	err := getOrgByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ListOrgByIDIn retrieves multiple Org records by a set of primary key values.
// Records not found are silently ignored.
func ListOrgByIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	iDs ...int64,
) ([]*Org, error) {
	query, err := tsq.
		Select(TableOrgCols...).
		From(TableOrg).
		Where(Org_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}
	return tsq.List(ctx, db, query)
}

// ListOrgByIDInOrErr retrieves multiple Org records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListOrgByIDInOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	iDs ...int64,
) ([]*Org, error) {
	query, err := tsq.
		Select(TableOrgCols...).
		From(TableOrg).
		Where(Org_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(iDs, list, func(row *Org) int64 {
		return row.ID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Org(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
var getOrgByNameQuery *tsq.Query[Org]

func init() {
	var err error
	getOrgByNameQuery, err = tsq.
		Select(TableOrgCols...).
		From(TableOrg).
		Where(
			Org_Name.EQVar(),
		).
		KwSearch(TableOrg.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getOrgByNameQuery"))
	}
}

// GetOrgByName retrieves a Org record by unique index ux_org_name.
// Returns (nil, nil) if the record is not found.
func GetOrgByName(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (*Org, error) {
	row := &Org{}
	err := getOrgByNameQuery.Load(
		ctx, db, row,
		name,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetOrgByNameOrErr retrieves a Org record by unique index ux_org_name.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetOrgByNameOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (*Org, error) {
	row := &Org{}
	err := getOrgByNameQuery.Load(
		ctx, db, row,
		name,
	)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ExistsOrgByName checks if a Org record exists by unique index ux_org_name.
func ExistsOrgByName(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (bool, error) {
	rs, err := getOrgByNameQuery.Exists(
		ctx, db,
		name,
	)
	return rs, errors.Trace(err)
}

// =============================================================================
// Query by Indexes
// =============================================================================

// =============================================================================
// List All Records
// =============================================================================
var listOrgQuery *tsq.Query[Org]

func init() {
	var err error
	listOrgQuery, err = tsq.
		Select(TableOrgCols...).
		From(TableOrg).
		KwSearch(TableOrg.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listOrgQuery"))
	}
}

// CountOrg returns the total count of Org records.
func CountOrg(
	ctx context.Context,
	tx tsq.SqlExecutor,
) (int64, error) {
	return listOrgQuery.Count64(ctx, tx)
}

// ListOrg retrieves all Org records.
func ListOrg(
	ctx context.Context,
	tx tsq.SqlExecutor,
) ([]*Org, error) {
	return tsq.List(ctx, tx, listOrgQuery)
}

// PageOrg retrieves Org records with pagination.
func PageOrg(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Org], error) {
	return tsq.Page(ctx, tx, page, listOrgQuery)
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Org record.
func (o *Org) Insert(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	o.CreatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "insert Org: %s", tsq.CompactJSON(o))
	}
	return nil
}

// Update updates an existing Org record.
func (o *Org) Update(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Update(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "update Org: %s", tsq.CompactJSON(o))
	}
	return nil
}

// Delete permanently removes a Org record.
func (o *Org) Delete(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Delete(ctx, db, o)
	if err != nil {
		return errors.Annotatef(err, "delete Org: %s", tsq.CompactJSON(o))
	}
	return nil
}

// =============================================================================
// Custom Query Helpers
// =============================================================================
// ListOrgByQuery executes a custom query to retrieve a list of Org records.
func ListOrgByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	qb *tsq.Query[Org],
	args ...any,
) ([]*Org, error) {
	return tsq.List(ctx, tx, qb, args...)
}

// PageOrgByQuery executes a custom query to retrieve a page of Org records.
func PageOrgByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
	qb *tsq.Query[Org],
	args ...any,
) (*tsq.PageResp[Org], error) {
	return tsq.Page(ctx, tx, page, qb, args...)
}
