// Code generated by tsq-v2.0.0. DO NOT EDIT.
package database

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq"

	null "gopkg.in/nullbio/null.v6"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

func init() {
	tsq.RegisterTable(
		TableOrg,
		func(db *tsq.DbMap) {
			db.AddTableWithName(TableOrg, "org").SetKeys(true, "ID")
		},
		func(db *tsq.DbMap) error {
			// Upsert Ux list
			if err := tsq.UpsertIndex(db, "org", true, "ux_org_name", []string{"name"}); err != nil {
				return errors.Annotate(err, "upsert ux_org_name@org")
			}

			return nil
		},
	)
}

// TableOrg implements the tsq.Table interface for Org.
var TableOrg tsq.Table = Org{}

// TableOrgCols is the list of columns for Org table.
var TableOrgCols = []tsq.Column{
	Org_CT,
	Org_ID,
	Org_Name,
}

// Column definitions for Org table.
var (
	Org_CT   = tsq.NewCol[null.Time](TableOrg, "ct", "ct", func(t any) any { return &t.(*Org).CT })
	Org_ID   = tsq.NewCol[int64](TableOrg, "id", "id", func(t any) any { return &t.(*Org).ID })
	Org_Name = tsq.NewCol[string](TableOrg, "name", "Name", func(t any) any { return &t.(*Org).Name })
)

// Table returns the database table name for Org.
func (o Org) Table() string { return "org" }

// KwList returns columns that support keyword search for Org.
func (o Org) KwList() []tsq.Column {
	return []tsq.Column{}
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getOrgByIDQuery *tsq.Query

// GetOrgByID retrieves a Org record by its ID.
// Returns (nil, nil) if the record is not found.
func GetOrgByID(
	ctx context.Context,
	db tsq.SqlExecutor,
	iD int64,
) (*Org, error) {
	row := &Org{}
	err := getOrgByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// GetOrgByIDOrErr retrieves a Org record by its ID.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetOrgByIDOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	iD int64,
) (*Org, error) {
	row := &Org{}
	err := getOrgByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, err
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// ListOrgByIDIn retrieves multiple Org records by a set of ID values.
// Records not found are silently ignored.
func ListOrgByIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	iDs ...int64,
) ([]*Org, error) {
	query, err := tsq.
		Select(TableOrgCols...).
		Where(Org_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	return tsq.List[Org](ctx, db, query)
}

// ListOrgByIDInOrErr retrieves multiple Org records by a set of ID values.
// Returns an error if any of the specified records are not found.
func ListOrgByIDInOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	iDs ...int64,
) ([]*Org, error) {
	query, err := tsq.
		Select(TableOrgCols...).
		Where(Org_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List[Org](ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(iDs, list, func(row *Org) int64 {
		return row.ID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("Org(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new Org record into the database.
// Automatically sets creation and modification timestamps if configured.
func (o *Org) Insert(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	o.CT = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, o)
	if err != nil {
		return errors.Annotate(err, tsq.PrettyJSON(o))
	}

	return nil
}

// Update updates an existing Org record in the database.
// Automatically updates the modification timestamp if configured.
func (o *Org) Update(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Update(ctx, db, o)
	if err != nil {
		return errors.Annotate(err, tsq.PrettyJSON(o))
	}

	return nil
}

// Delete permanently removes a Org record from the database.
func (o *Org) Delete(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Delete(ctx, db, o)
	if err != nil {
		return errors.Annotate(err, tsq.PrettyJSON(o))
	}

	return nil
}

// ListOrgByQuery executes a custom query to retrieve Org records.
func ListOrgByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	qb *tsq.Query,
	args ...any,
) ([]*Org, error) {
	return tsq.List[Org](ctx, tx, qb, args...)
}

// PageOrgByQuery executes a custom query with pagination to retrieve Org records.
func PageOrgByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
	qb *tsq.Query,
	args ...any,
) (*tsq.PageResp[Org], error) {
	return tsq.Page[Org](ctx, tx, page, qb, args...)
}

// =============================================================================
// List All Records
// =============================================================================
// listOrgQuery is the base query for retrieving all Org records.
var listOrgQuery *tsq.Query

// CountOrg returns the total count of Org records.
func CountOrg(
	ctx context.Context,
	tx tsq.SqlExecutor,
) (int64, error) {
	return listOrgQuery.Count64(ctx, tx)
}

// ListOrg retrieves all Org records from the database.
func ListOrg(
	ctx context.Context,
	tx tsq.SqlExecutor,
) ([]*Org, error) {
	return tsq.List[Org](ctx, tx, listOrgQuery)
}

// PageOrg retrieves Org records with pagination support.
func PageOrg(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[Org], error) {
	return tsq.Page[Org](ctx, tx, page, listOrgQuery)
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
var getOrgByNameQuery *tsq.Query

// GetOrgByName retrieves a Org record by unique index ux_org_name.
// Returns (nil, nil) if the record is not found.
func GetOrgByName(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (*Org, error) {
	query := getOrgByNameQuery

	row := &Org{}
	err := query.Load(ctx, db, row,
		name,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// GetOrgByNameOrErr retrieves a Org record by unique index ux_org_name.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetOrgByNameOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (*Org, error) {
	query := getOrgByNameQuery

	row := &Org{}
	err := query.Load(ctx, db, row,
		name,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, err
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// ExistsOrgByName checks whether a Org record exists by unique index ux_org_name.
func ExistsOrgByName(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (bool, error) {
	query := getOrgByNameQuery

	rs, err := query.Exists(ctx, db,
		name,
	)
	return rs, errors.Trace(err)
}
