-- Code generated by tsq-v3.7.0. DO NOT EDIT.

-- Dialect: sqlite

-- Table: category

CREATE TABLE IF NOT EXISTS "category" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "description" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" INTEGER NOT NULL
);

CREATE UNIQUE INDEX "ux_category_name" ON "category"("name");


-- Table: item

CREATE TABLE IF NOT EXISTS "item" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "category_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "price" INTEGER NOT NULL
);

CREATE INDEX "idx_category" ON "item"("category_id");

CREATE UNIQUE INDEX "ux_item_name" ON "item"("name");


-- Table: order

CREATE TABLE IF NOT EXISTS "order" (
    "uid" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP,
    "deleted_at" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 1,
    "amount" INTEGER NOT NULL,
    "item_id" INTEGER NOT NULL,
    "price" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL
);

CREATE INDEX "idx_item" ON "order"("item_id");

CREATE INDEX "idx_order_user_id_item_id" ON "order"("user_id", "item_id");


-- Table: org

CREATE TABLE IF NOT EXISTS "org" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "name" TEXT NOT NULL
);

CREATE UNIQUE INDEX "ux_org_name" ON "org"("name");


-- Table: user

CREATE TABLE IF NOT EXISTS "user" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" TIMESTAMP,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "org_id" INTEGER NOT NULL
);

CREATE UNIQUE INDEX "ux_user_name" ON "user"("name");
