// Code generated by tsq-v3.7.1. DO NOT EDIT.

package database

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableUser implements the tsq.Table interface for User.
var TableUser tsq.Table = User{}

// TSQOwner marks User as a TSQ owner.
func (u User) TSQOwner() {}

// Table returns the database table name for User.
func (u User) Table() string { return "user" }

// Cols returns all generated columns for User.
func (u User) Cols() []tsq.SQLColumn {
	return tsq.SQLColumns(TableUserCols...)
}

// SearchColumns returns columns that support keyword search for User.
func (u User) SearchColumns() []tsq.SearchColumn {
	return []tsq.SearchColumn{
		User_Name,
		User_Email,
	}
}

// PrimaryKeys returns the primary key columns for User.
func (u User) PrimaryKeys() []string {
	return []string{"id"}
}

// AutoIncrement reports whether User uses an auto-increment primary key.
func (u User) AutoIncrement() bool { return true }

// VersionColumn returns the optimistic-lock version column for User, if any.
func (u User) VersionColumn() string {
	return ""
}

// Column definitions for User table.
var (
	User_CreatedAt = tsq.NewCol("created_at", "created_at", func(t *User) *null.Time { return &t.CreatedAt })
	User_Email     = tsq.NewCol("email", "email", func(t *User) *string { return &t.Email })
	User_ID        = tsq.NewCol("id", "id", func(t *User) *int64 { return &t.ID })
	User_Name      = tsq.NewCol("name", "name", func(t *User) *string { return &t.Name })
	User_OrgID     = tsq.NewCol("org_id", "org_id", func(t *User) *int64 { return &t.OrgID })
)

// TableUserCols is the list of all selectable columns for User table.
var TableUserCols = []tsq.BoundColumn[User]{
	User_CreatedAt,
	User_Email,
	User_ID,
	User_Name,
	User_OrgID,
}

// =============================================================================
// Table Registration and Index Initialization
// =============================================================================

func init() {
	tsq.RegisterTable(
		TableUser,
		func(db *tsq.Engine) error {
			// Upsert unique indexes.
			if err := tsq.UpsertIndex(db, "user", true, "ux_user_name", []string{"name"}); err != nil {
				return errors.Annotate(err, "upsert ux_user_name@user")
			}
			return nil
		},
	)
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getUserByIDQuery *tsq.Query[User]

func init() {
	var err error
	getUserByIDQuery, err = tsq.
		Select(TableUserCols...).
		From(TableUser).
		Where(User_ID.EQVar()).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getUserByIDQuery"))
	}
}

// GetUserByID retrieves a User record by its primary key.
// Returns (nil, nil) if the record is not found.
func GetUserByID(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*User, error) {
	row := &User{}
	err := getUserByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetUserByIDOrErr retrieves a User record by its primary key.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetUserByIDOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iD int64,
) (*User, error) {
	row := &User{}
	err := getUserByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ListUserByIDIn retrieves multiple User records by a set of primary key values.
// Records not found are silently ignored.
func ListUserByIDIn(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*User, error) {
	query, err := tsq.
		Select(TableUserCols...).
		From(TableUser).
		Where(User_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}
	return tsq.List(ctx, db, query)
}

// ListUserByIDInOrErr retrieves multiple User records by a set of primary key values.
// Returns an error if any of the specified records are not found.
func ListUserByIDInOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	iDs ...int64,
) ([]*User, error) {
	query, err := tsq.
		Select(TableUserCols...).
		From(TableUser).
		Where(User_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List(ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(iDs, list, func(row *User) int64 {
		return row.ID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("User(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
var getUserByNameQuery *tsq.Query[User]

func init() {
	var err error
	getUserByNameQuery, err = tsq.
		Select(TableUserCols...).
		From(TableUser).
		Search(TableUser.SearchColumns()...).
		Where(
			User_Name.EQVar(),
		).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getUserByNameQuery"))
	}
}

// GetUserByName retrieves a User record by unique index ux_user_name.
// Returns (nil, nil) if the record is not found.
func GetUserByName(
	ctx context.Context,
	db tsq.SQLExecutor,
	name string,
) (*User, error) {
	row := &User{}
	err := getUserByNameQuery.Load(
		ctx, db, row,
		name,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}
		return nil, errors.Trace(err)
	}
	return row, nil
}

// GetUserByNameOrErr retrieves a User record by unique index ux_user_name.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetUserByNameOrErr(
	ctx context.Context,
	db tsq.SQLExecutor,
	name string,
) (*User, error) {
	row := &User{}
	err := getUserByNameQuery.Load(
		ctx, db, row,
		name,
	)
	if err != nil {
		return nil, errors.Trace(err)
	}
	return row, nil
}

// ExistsUserByName checks if a User record exists by unique index ux_user_name.
func ExistsUserByName(
	ctx context.Context,
	db tsq.SQLExecutor,
	name string,
) (bool, error) {
	rs, err := getUserByNameQuery.Exists(
		ctx, db,
		name,
	)
	return rs, errors.Trace(err)
}

// =============================================================================
// Query by Indexes
// =============================================================================

// =============================================================================
// List All Records
// =============================================================================
var listUserQuery *tsq.Query[User]

func init() {
	var err error
	listUserQuery, err = tsq.
		Select(TableUserCols...).
		From(TableUser).
		Search(TableUser.SearchColumns()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listUserQuery"))
	}
}

// CountUser returns the total count of User records.
func CountUser(
	ctx context.Context,
	tx tsq.SQLExecutor,
) (int, error) {
	return listUserQuery.Count(ctx, tx)
}

// ListUser retrieves all User records.
func ListUser(
	ctx context.Context,
	tx tsq.SQLExecutor,
) ([]*User, error) {
	return tsq.List(ctx, tx, listUserQuery)
}

// PageUser retrieves User records with pagination.
func PageUser(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[User], error) {
	return tsq.Page(ctx, tx, page, listUserQuery)
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new User record.
func (u *User) Insert(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	u.CreatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, u)
	if err != nil {
		return errors.Annotatef(err, "insert User: %s", tsq.CompactJSON(u))
	}
	return nil
}

// Update updates an existing User record.
func (u *User) Update(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Update(ctx, db, u)
	if err != nil {
		return errors.Annotatef(err, "update User: %s", tsq.CompactJSON(u))
	}
	return nil
}

// Delete permanently removes a User record.
func (u *User) Delete(
	ctx context.Context,
	db tsq.SQLExecutor,
) error {
	err := tsq.Delete(ctx, db, u)
	if err != nil {
		return errors.Annotatef(err, "delete User: %s", tsq.CompactJSON(u))
	}
	return nil
}

// =============================================================================
// Custom Query Helpers
// =============================================================================
// ListUserByQuery executes a custom query to retrieve a list of User records.
func ListUserByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	qb *tsq.Query[User],
	args ...any,
) ([]*User, error) {
	return tsq.List(ctx, tx, qb, args...)
}

// PageUserByQuery executes a custom query to retrieve a page of User records.
func PageUserByQuery(
	ctx context.Context,
	tx tsq.SQLExecutor,
	page *tsq.PageReq,
	qb *tsq.Query[User],
	args ...any,
) (*tsq.PageResp[User], error) {
	return tsq.Page(ctx, tx, page, qb, args...)
}
