// Code generated by tsq-v3.3.0. DO NOT EDIT.

package database

import (
	"context"
	tsqsql "database/sql"
	tsqtime "time"

	null "gopkg.in/nullbio/null.v6"

	"github.com/juju/errors"
	"github.com/tmoeish/tsq"
)

// =============================================================================
// Table Interface Implementation
// =============================================================================

// TableUser implements the tsq.Table interface for User.
var TableUser tsq.Table = User{}

// Column definitions for User table.
var (
	User_CreatedAt = tsq.NewCol[null.Time](TableUser, "created_at", "created_at", func(t any) any { return &t.(*User).CreatedAt })
	User_Email     = tsq.NewCol[string](TableUser, "email", "email", func(t any) any { return &t.(*User).Email })
	User_ID        = tsq.NewCol[int64](TableUser, "id", "id", func(t any) any { return &t.(*User).ID })
	User_Name      = tsq.NewCol[string](TableUser, "name", "name", func(t any) any { return &t.(*User).Name })
	User_OrgID     = tsq.NewCol[int64](TableUser, "org_id", "org_id", func(t any) any { return &t.(*User).OrgID })
)

// TableUserCols is the list of columns for User table.
var TableUserCols = []tsq.Column{
	User_CreatedAt,
	User_Email,
	User_ID,
	User_Name,
	User_OrgID,
}

// Table returns the database table name for User.
func (u User) Table() string { return "user" }

// KwList returns columns that support keyword search for User.
func (u User) KwList() []tsq.Column {
	return []tsq.Column{
		User_Name,
		User_Email,
	}
}

func init() {
	tsq.RegisterTable(
		TableUser,
		func(db *tsq.DbMap) {
			db.AddTableWithName(TableUser, "user").SetKeys(true, "ID")
		},
		func(db *tsq.DbMap) error {
			// Upsert unique indexes.
			if err := tsq.UpsertIndex(db, "user", true, "ux_user_name", []string{"name"}); err != nil {
				return errors.Annotate(err, "upsert ux_user_name@user")
			}

			return nil
		},
	)
}

// =============================================================================
// Query by Primary Key
// =============================================================================
var getUserByIDQuery *tsq.Query

func init() {
	var err error
	getUserByIDQuery, err = tsq.
		Select(TableUserCols...).
		Where(User_ID.EQVar()).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getUserByIDQuery"))
	}
}

// GetUserByID retrieves a User record by its ID.
// Returns (nil, nil) if the record is not found.
func GetUserByID(
	ctx context.Context,
	db tsq.SqlExecutor,
	iD int64,
) (*User, error) {
	row := &User{}
	err := getUserByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// GetUserByIDOrErr retrieves a User record by its ID.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetUserByIDOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	iD int64,
) (*User, error) {
	row := &User{}
	err := getUserByIDQuery.Load(ctx, db, row, iD)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, err
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// ListUserByIDIn retrieves multiple User records by a set of ID values.
// Records not found are silently ignored.
func ListUserByIDIn(
	ctx context.Context,
	db tsq.SqlExecutor,
	iDs ...int64,
) ([]*User, error) {
	query, err := tsq.
		Select(TableUserCols...).
		Where(User_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	return tsq.List[User](ctx, db, query)
}

// ListUserByIDInOrErr retrieves multiple User records by a set of ID values.
// Returns an error if any of the specified records are not found.
func ListUserByIDInOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	iDs ...int64,
) ([]*User, error) {
	query, err := tsq.
		Select(TableUserCols...).
		Where(User_ID.In(iDs...)).
		Build()
	if err != nil {
		return nil, errors.Annotate(err, "build query")
	}

	list, err := tsq.List[User](ctx, db, query)
	if err != nil {
		return nil, errors.Trace(err)
	}

	match := tsq.MatchByInputOrder(iDs, list, func(row *User) int64 {
		return row.ID
	})
	if len(match.Missing) > 0 {
		return nil, errors.Errorf("User(s) not found: %v", match.Missing)
	}
	return match.Ordered, nil
}

// =============================================================================
// CRUD Operations
// =============================================================================

// Insert inserts a new User record into the database.
// Automatically sets creation and modification timestamps if configured.
func (u *User) Insert(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	u.CreatedAt = null.TimeFrom(tsqtime.Now())
	err := tsq.Insert(ctx, db, u)
	if err != nil {
		return errors.Annotate(err, tsq.PrettyJSON(u))
	}

	return nil
}

// Update updates an existing User record in the database.
// Automatically updates the modification timestamp if configured.
func (u *User) Update(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Update(ctx, db, u)
	if err != nil {
		return errors.Annotate(err, tsq.PrettyJSON(u))
	}

	return nil
}

// Delete permanently removes a User record from the database.
func (u *User) Delete(
	ctx context.Context,
	db tsq.SqlExecutor,
) error {
	err := tsq.Delete(ctx, db, u)
	if err != nil {
		return errors.Annotate(err, tsq.PrettyJSON(u))
	}

	return nil
}

// ListUserByQuery executes a custom query to retrieve User records.
func ListUserByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	qb *tsq.Query,
	args ...any,
) ([]*User, error) {
	return tsq.List[User](ctx, tx, qb, args...)
}

// PageUserByQuery executes a custom query with pagination to retrieve User records.
func PageUserByQuery(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
	qb *tsq.Query,
	args ...any,
) (*tsq.PageResp[User], error) {
	return tsq.Page[User](ctx, tx, page, qb, args...)
}

// =============================================================================
// List All Records
// =============================================================================
// listUserQuery is the base query for retrieving all User records.
var listUserQuery *tsq.Query

func init() {
	var err error
	listUserQuery, err = tsq.
		Select(TableUserCols...).
		KwSearch(TableUser.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize listUserQuery"))
	}
}

// CountUser returns the total count of User records.
func CountUser(
	ctx context.Context,
	tx tsq.SqlExecutor,
) (int64, error) {
	return listUserQuery.Count64(ctx, tx)
}

// ListUser retrieves all User records from the database.
func ListUser(
	ctx context.Context,
	tx tsq.SqlExecutor,
) ([]*User, error) {
	return tsq.List[User](ctx, tx, listUserQuery)
}

// PageUser retrieves User records with pagination support.
func PageUser(
	ctx context.Context,
	tx tsq.SqlExecutor,
	page *tsq.PageReq,
) (*tsq.PageResp[User], error) {
	return tsq.Page[User](ctx, tx, page, listUserQuery)
}

// =============================================================================
// Query by Unique Indexes
// =============================================================================
var getUserByNameQuery *tsq.Query

func init() {
	var err error
	getUserByNameQuery, err = tsq.
		Select(TableUserCols...).
		Where(
			User_Name.EQVar(),
		).
		KwSearch(TableUser.KwList()...).
		Build()
	if err != nil {
		panic(errors.Annotate(err, "initialize getUserByNameQuery"))
	}
}

// GetUserByName retrieves a User record by unique index ux_user_name.
// Returns (nil, nil) if the record is not found.
func GetUserByName(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (*User, error) {
	query := getUserByNameQuery

	row := &User{}
	err := query.Load(ctx, db, row,
		name,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, nil
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// GetUserByNameOrErr retrieves a User record by unique index ux_user_name.
// Returns (nil, database/sql.ErrNoRows) if the record is not found.
func GetUserByNameOrErr(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (*User, error) {
	query := getUserByNameQuery

	row := &User{}
	err := query.Load(ctx, db, row,
		name,
	)
	if err != nil {
		if errors.Is(err, tsqsql.ErrNoRows) {
			return nil, err
		}

		return nil, errors.Trace(err)
	}

	return row, nil
}

// ExistsUserByName checks whether a User record exists by unique index ux_user_name.
func ExistsUserByName(
	ctx context.Context,
	db tsq.SqlExecutor,
	name string,
) (bool, error) {
	query := getUserByNameQuery

	rs, err := query.Exists(ctx, db,
		name,
	)
	return rs, errors.Trace(err)
}
