// Code generated by tsq-dev. DO NOT EDIT.

package database

import (
	"github.com/tmoeish/tsq"
)

var DtoUserOrder = UserOrder{}

// table UserOrder Col list
var (
	UserOrder_ItemCategory = Category_Name.Into(func(holder any) any {
		return &holder.(*UserOrder).ItemCategory
	}, "item_category")
	UserOrder_ItemID = Item_ID.Into(func(holder any) any {
		return &holder.(*UserOrder).ItemID
	}, "item_id")
	UserOrder_ItemName = Item_Name.Into(func(holder any) any {
		return &holder.(*UserOrder).ItemName
	}, "item_name")
	UserOrder_ItemPrice = Item_Price.Into(func(holder any) any {
		return &holder.(*UserOrder).ItemPrice
	}, "item_price")
	UserOrder_OrderAmount = Order_Amount.Into(func(holder any) any {
		return &holder.(*UserOrder).OrderAmount
	}, "order_amount")
	UserOrder_OrderID = Order_ID.Into(func(holder any) any {
		return &holder.(*UserOrder).OrderID
	}, "order_id")
	UserOrder_OrderPrice = Order_Price.Into(func(holder any) any {
		return &holder.(*UserOrder).OrderPrice
	}, "order_price")
	UserOrder_OrderStatus = Order_Status.Into(func(holder any) any {
		return &holder.(*UserOrder).OrderStatus
	}, "order_status")
	UserOrder_OrderTime = Order_CT.Into(func(holder any) any {
		return &holder.(*UserOrder).OrderTime
	}, "order_time")
	UserOrder_OrgName = Org_Name.Into(func(holder any) any {
		return &holder.(*UserOrder).OrgName
	}, "org_name")
	UserOrder_UserEmail = User_Email.Into(func(holder any) any {
		return &holder.(*UserOrder).UserEmail
	}, "user_email")
	UserOrder_UserID = User_ID.Into(func(holder any) any {
		return &holder.(*UserOrder).UserID
	}, "user_id")
	UserOrder_UserName = User_Name.Into(func(holder any) any {
		return &holder.(*UserOrder).UserName
	}, "user_name")
)

// Cols returns fileds of table UserOrder
func (uo UserOrder) Cols() []tsq.Column {
	return []tsq.Column{
		UserOrder_ItemCategory,
		UserOrder_ItemID,
		UserOrder_ItemName,
		UserOrder_ItemPrice,
		UserOrder_OrderAmount,
		UserOrder_OrderID,
		UserOrder_OrderPrice,
		UserOrder_OrderStatus,
		UserOrder_OrderTime,
		UserOrder_OrgName,
		UserOrder_UserEmail,
		UserOrder_UserID,
		UserOrder_UserName,
	}
}
